import { GuideCallout, GuideChecklist, GuideSection, GuideStep, GuideSteps } from "../../article-components";

export default function BuildAndApproveBudgetArticle() {
  return <div className="space-y-10">
    <GuideSection id="before-you-start" title="Before you start"><p>Confirm the entity, fiscal year or date range, budget owner, approved assumptions, account and cost-centre scope, period phasing, comparison basis, and approver.</p><GuideCallout tone="info" title="A budget does not post actual transactions">Budget lines provide planning and variance evidence. Actuals still come from journals and source documents.</GuideCallout></GuideSection>
    <GuideSection id="create-the-budget" title="Create the budget header"><GuideSteps><GuideStep title="Choose the scope">Use one entity and an unambiguous budget name and period.</GuideStep><GuideStep title="Record assumptions">State the approved planning basis and owner so reviewers can reproduce the numbers.</GuideStep><GuideStep title="Keep alternatives distinct">Use separate versions or forecasts rather than overwriting an approved basis without evidence.</GuideStep></GuideSteps></GuideSection>
    <GuideSection id="build-budget-lines" title="Build account and cost-centre lines"><p>Add postable accounts, optional cost centres, and period amounts. Check duplicates, signs, totals, phasing, and whether each line belongs to income, expense, asset, liability, or cash planning.</p></GuideSection>
    <GuideSection id="review-and-approve" title="Review and approve the plan"><p>Compare the complete total with the approved schedule, inspect material lines, and confirm ownership before approval. Approval freezes the agreed baseline for variance reporting.</p></GuideSection>
    <GuideSection id="monitor-variance" title="Monitor variance and the heatmap"><p>Use variance to compare planned and actual amounts for a selected period. Use the heatmap to find concentrated overruns, then trace the actual to its source transaction before changing the plan.</p></GuideSection>
    <GuideSection id="revise-or-remove" title="Revise or remove a draft safely"><GuideCallout tone="warning" title="Do not erase the approved baseline">Edit or delete only drafts and only with permission. Preserve the approved version and create a controlled forecast or revision when assumptions change.</GuideCallout></GuideSection>
    <GuideSection id="common-problems" title="Common problems"><ul className="list-disc space-y-2 pl-5"><li>Actuals are blank: check the entity, account, date range, and posted source transactions.</li><li>Variance looks reversed: confirm the account type and sign convention.</li><li>Approval is unavailable: check status, permission, and required lines.</li><li>Two lines overlap: remove the duplicate account and cost-centre combination before approval.</li></ul></GuideSection>
    <GuideSection id="completion-check" title="Completion check"><GuideChecklist items={["Scope, assumptions, owner, and period are explicit", "Lines and phasing match the approved schedule", "Duplicates and signs were reviewed", "The correct version was approved", "Material variances trace to source records"]} /></GuideSection>
  </div>;
}
