import { GuideCallout, GuideChecklist, GuideSection, GuideStep, GuideSteps } from "../../article-components";

export default function CollectOnlinePaymentsArticle() {
  return <div className="space-y-10">
    <GuideSection id="before-you-start" title="Before you start"><p>Confirm the active entity, customer, expected amount and currency, provider reference, destination account, virtual-account ownership, receipt or invoice, and the provider event status.</p><GuideCallout tone="warning" title="A provider success is not the whole accounting result">Verify the collection, its business receipt or allocation, the journal, and later bank settlement. Do not record a duplicate receipt because one screen is delayed.</GuideCallout></GuideSection>
    <GuideSection id="trace-the-collection" title="Trace the provider collection"><GuideSteps><GuideStep title="Find the provider event">Search by provider reference, customer, amount, date, and status.</GuideStep><GuideStep title="Check confirmation">Separate initiated or processing payments from confirmed, failed, or reversed outcomes.</GuideStep><GuideStep title="Trace the business record">Confirm the event created or linked the intended receipt and customer balance.</GuideStep></GuideSteps></GuideSection>
    <GuideSection id="manage-virtual-accounts" title="Create and manage virtual accounts"><p>Create an account only for the approved customer or purpose, confirm provider and currency, and avoid issuing duplicates. Deactivate or replace an account through its management controls, not by changing displayed details elsewhere.</p></GuideSection>
    <GuideSection id="check-business-posting" title="Check the receipt and ledger result"><p>For a confirmed collection, verify receipt amount, customer, unallocated balance, bank or clearing account, and journal. Allocate the receipt separately when it should settle invoices.</p></GuideSection>
    <GuideSection id="resolve-a-failed-event" title="Resolve a failed provider event"><p>Use Needs Attention to inspect the event, tenant, signature or validation result, linked object, error, and prior attempts. Correct the root cause first. Replay can book real money, so use it only with replay permission and only after proving the event has not already posted.</p></GuideSection>
    <GuideSection id="protect-payment-data" title="Protect sensitive payment data"><GuideCallout tone="warning" title="Share references, not secrets">Do not expose full virtual-account numbers, bank details, raw webhook payloads, signatures, access tokens, or customer personal data in screenshots and tickets. Use the safe event and document references.</GuideCallout></GuideSection>
    <GuideSection id="common-problems" title="Common problems"><ul className="list-disc space-y-2 pl-5"><li>Customer paid but balance is open: trace the receipt and allocation before creating anything new.</li><li>Collection is confirmed but bank line is absent: wait for settlement or import the statement, then reconcile.</li><li>Event is failed: correct its stated cause before replay.</li><li>Virtual account details are masked: request sensitive access only when the job requires full details.</li></ul></GuideSection>
    <GuideSection id="completion-check" title="Completion check"><GuideChecklist items={["Provider reference, customer, amount, and status agree", "Virtual account belongs to the intended scope", "Receipt, allocation, and journal were traced", "No duplicate payment or replay was created", "Only safe references were included in support evidence"]} /></GuideSection>
  </div>;
}
