import { GuideCallout, GuideChecklist, GuideSection, GuideStep, GuideSteps } from "../../article-components";

export default function FileAndPayTaxArticle() {
  return <div className="space-y-10">
    <GuideSection id="before-you-start" title="Before you start"><p>Confirm the entity, tax type, authority, liability account, filing frequency, period, due date, ledger balance, supporting schedules, filing reference, approved adjustments, bank account, and payment evidence.</p><GuideCallout tone="warning" title="Prepare, file, and pay are separate states">Preparing reads the ledger and creates a draft obligation. Filing records the authority submission. Payment moves cash and can be partial.</GuideCallout><p>Creating obligations, preparing filings, marking them filed and un-filing them act for the whole school, so they need someone who covers the whole school as well as the tax key.</p></GuideSection>
    <GuideSection id="create-the-obligation" title="Create the statutory obligation"><GuideSteps><GuideStep title="Identify the tax">Use the approved code, name, authority, frequency, and due-date rule.</GuideStep><GuideStep title="Map the payable">Choose the active postable liability account that accumulates this tax.</GuideStep><GuideStep title="Avoid duplicates">Check that the same entity and tax type do not already have an active obligation.</GuideStep></GuideSteps></GuideSection>
    <GuideSection id="prepare-the-filing" title="Prepare the filing from the ledger"><p>Select the obligation and period start and end dates. Review <strong>Owed</strong> (<strong>Owed for the period</strong> on the return), what the period built up in the obligation&rsquo;s liability account, recoverable amounts where applicable, due date, and balance before preparing the draft return.</p></GuideSection>
    <GuideSection id="read-the-return" title="Read what the return declares">
      <p>Open a return. <strong>What it declares</strong> counts its transaction lines and how many are late. Each line is declared once: a late item, recorded after its own month&rsquo;s return, is declared on the return for the month it was recorded in, so the next return is never short and a filed figure does not move.</p>
      <p>At books with several branches, <strong>Each branch&rsquo;s share</strong> shows every branch&rsquo;s tax, recoverable amount, penalty, what is due, paid and outstanding. A share labelled <strong>No branch yet</strong> means some lines carry no branch; give them a branch before filing, because a school with several branches files each branch&rsquo;s share.</p>
      <p>A PAYE, pension, NHF, NSITF or ITF return lists <strong>People on this return</strong>, with their tax ID or pension administrator, state, branch and amount, for roles that see every pay figure. It holds only what payroll deducted here; pay brought forward from earlier in the year is in no monthly return.</p>
      <GuideCallout tone="info" title="An example">
        A ₦75,000 VAT item dated September is posted on 8 October, after September&rsquo;s return was filed. It is declared on October&rsquo;s return and marked late, and September&rsquo;s filed figure stays as filed.
      </GuideCallout>
    </GuideSection>
    <GuideSection id="record-the-filing" title="Record the return filed with the authority"><p>Open the draft, select <strong>Mark as filed</strong>, and enter the actual filing date and reference. Add an adjustment only with approved evidence and the correct account. Filing can net recoverable tax or record a penalty, but it does not move cash. A penalty is shared by each branch&rsquo;s share of the tax unless you choose the <strong>Branch that bears it</strong>.</p></GuideSection>
    <GuideSection id="remit-the-liability" title="Remit the liability">
      <p>Open the filed return and choose <strong>Pay</strong>. Where the return has several branch shares, choose the <strong>Share to pay</strong>; only shares with a branch and something outstanding are offered, and a single payable share is chosen for you. <strong>Pay from (bank account)</strong> lists only that branch&rsquo;s accounts. Enter the payment date and amount.</p>
      <p>Partial payments are allowed, and the filing closes only after the balance is cleared.</p>
      <GuideCallout tone="info" title="An example">
        October&rsquo;s PAYE return is ₦1,200,000: Ikeja ₦700,000, Lekki ₦500,000. Uche Nnaji pays Ikeja&rsquo;s share from Ikeja&rsquo;s account, and Lekki&rsquo;s from Lekki&rsquo;s. The return closes when both are paid.
      </GuideCallout>
    </GuideSection>
    <GuideSection id="reverse-a-payment" title="Reverse a payment recorded in error">
      <p>Under <strong>Payments</strong> on the return, select <strong>Reverse</strong> on the payment and give a reason. It reverses the payment&rsquo;s journal and takes it off the return, which goes back to Filed with that share unpaid. It needs the tax payment key and someone who covers the whole school. The reversed row stays, showing when and why.</p>
    </GuideSection>
    <GuideSection id="annual-paye-return" title="The annual PAYE return">
      <p>Select <strong>Annual PAYE return</strong> on Tax Remittance and choose the tax year. It lists each person&rsquo;s pay and PAYE at this employer for the year, including this school&rsquo;s own months before its payroll ran on Console, and never a previous employer&rsquo;s pay. The payroll guide explains how earlier pay is recorded.</p>
    </GuideSection>
    <GuideSection id="correct-an-unpaid-filing" title="Correct an unpaid filing"><GuideCallout tone="warning" title="Un-file only before any payment">An unpaid filed return can be reverted to draft with <strong>Un-file</strong>, reversing its filing adjustment. Once cash has been remitted, reverse the payment first or use the authority and finance correction process.</GuideCallout></GuideSection>
    <GuideSection id="common-problems" title="Common problems"><ul className="list-disc space-y-2 pl-5"><li>Amount is wrong: reconcile the liability account and source postings for the exact period.</li><li>Filing date is rejected: choose an allowed date and open posting period.</li><li>Filing is refused at books with several branches: some lines have No branch yet. Give them a branch first.</li><li>Pay is unavailable: the return must be filed and the user needs tax payment permission.</li><li>A branch&rsquo;s share is missing from Share to pay: it has nothing outstanding, or it is the No branch yet share, which cannot be paid.</li><li>People on this return is hidden: your role does not see every pay figure on it.</li><li>Payroll liability remains: payroll schedules and tax remittance are separate; prepare the matching obligation and period.</li></ul></GuideSection>
    <GuideSection id="completion-check" title="Completion check"><GuideChecklist items={["Obligation and liability account are correct", "Prepared amount reconciles to the ledger and schedules", "Every line has a branch before filing", "Filing date, reference, and adjustment have evidence", "Each branch's share is paid from that branch's bank", "Outstanding balance and bank evidence agree"]} /></GuideSection>
  </div>;
}
