import { GuideCallout, GuideChecklist, GuideSection, GuideStep, GuideSteps } from "../../article-components";

export default function FileAndPayTaxArticle() {
  return <div className="space-y-10">
    <GuideSection id="before-you-start" title="Before you start"><p>Confirm the entity, tax type, authority, liability account, filing frequency, period, due date, ledger balance, supporting schedules, filing reference, approved adjustments, bank account, and payment evidence.</p><GuideCallout tone="warning" title="Prepare, file, and pay are separate states">Preparing reads the ledger and creates a draft obligation. Filing records the authority submission. Payment moves cash and can be partial.</GuideCallout></GuideSection>
    <GuideSection id="create-the-obligation" title="Create the statutory obligation"><GuideSteps><GuideStep title="Identify the tax">Use the approved code, name, authority, frequency, and due-date rule.</GuideStep><GuideStep title="Map the payable">Choose the active postable liability account that accumulates this tax.</GuideStep><GuideStep title="Avoid duplicates">Check that the same entity and tax type do not already have an active obligation.</GuideStep></GuideSteps></GuideSection>
    <GuideSection id="prepare-the-filing" title="Prepare the filing from the ledger"><p>Select the obligation and period start and end dates. Review the accrued liability, recoverable amounts where applicable, due date, and balance before preparing the draft return.</p></GuideSection>
    <GuideSection id="record-the-filing" title="Record the return filed with the authority"><p>Open the draft, select <strong>Mark as filed</strong>, and enter the actual filing date and reference. Add an adjustment only with approved evidence and the correct account. Filing can net recoverable tax or record a penalty, but it does not move cash.</p></GuideSection>
    <GuideSection id="remit-the-liability" title="Remit the liability"><p>Open the filed return, choose <strong>Pay</strong>, select the approved bank account, payment date, and amount. Partial payments are supported, and the filing closes only after the balance is cleared.</p></GuideSection>
    <GuideSection id="correct-an-unpaid-filing" title="Correct an unpaid filing"><GuideCallout tone="warning" title="Un-file only before any payment">An unpaid filed return can be reverted to draft, reversing its filing adjustment. Once cash has been remitted, use the authority and finance correction process instead of un-filing.</GuideCallout></GuideSection>
    <GuideSection id="common-problems" title="Common problems"><ul className="list-disc space-y-2 pl-5"><li>Amount is wrong: reconcile the liability account and source postings for the exact period.</li><li>Filing date is rejected: choose an allowed date and open posting period.</li><li>Pay is unavailable: the return must be filed and the user needs tax payment permission.</li><li>Payroll liability remains: payroll schedules and tax remittance are separate; prepare the matching obligation and period.</li></ul></GuideSection>
    <GuideSection id="completion-check" title="Completion check"><GuideChecklist items={["Obligation and liability account are correct", "Prepared amount reconciles to the ledger and schedules", "Filing date, reference, and adjustment have evidence", "Payment uses the approved bank, date, and amount", "Outstanding balance and bank evidence agree"]} /></GuideSection>
  </div>;
}
