import { GuideCallout, GuideChecklist, GuideSection, GuideStep, GuideSteps } from "../../article-components";

export default function ManageFixedAssetsArticle() {
  return <div className="space-y-10">
    <GuideSection id="before-you-start" title="Before you start"><p>Confirm the entity, asset identity, category, custodian or location, acquisition evidence, cost, funding account, useful life, residual value, depreciation start date, disposal evidence, and open fiscal period.</p><GuideCallout tone="warning" title="Use the asset register for the full lifecycle">Acquisition, depreciation, and disposal must update both the register and ledger. A manual journal alone leaves net book value and the schedule wrong.</GuideCallout></GuideSection>
    <GuideSection id="create-the-record" title="Create the asset record"><GuideSteps><GuideStep title="Identify the asset">Use a unique name and traceable serial, tag, category, custodian, or location.</GuideStep><GuideStep title="Define valuation">Enter cost, residual value, useful life, depreciation method, and start date from approved policy.</GuideStep><GuideStep title="Check accounts">Verify the fixed-asset, accumulated-depreciation, depreciation-expense, and gain or loss accounts.</GuideStep></GuideSteps></GuideSection>
    <GuideSection id="capitalise-the-asset" title="Capitalise the acquisition"><p>Open the draft asset, choose <strong>Acquire</strong>, confirm the funding account and date, and review the posting. Capitalisation debits property, plant and equipment, credits the funding account, and creates the straight-line schedule.</p></GuideSection>
    <GuideSection id="post-depreciation" title="Post due depreciation"><p>Use <strong>Depreciate to date</strong> for one asset or <strong>Run depreciation</strong> for the period-wide preview. Review eligible assets and amounts before posting. Never run the same period twice without checking the schedule status.</p></GuideSection>
    <GuideSection id="dispose-the-asset" title="Dispose of the asset"><p>Post all depreciation due through the disposal date first. Then confirm disposal date, proceeds, bank account when cash is received, and gain or loss account. Disposal removes cost and accumulated depreciation and records the resulting gain or loss.</p></GuideSection>
    <GuideSection id="verify-the-register" title="Verify the register and ledger"><p>Confirm asset status, cost, accumulated depreciation, net book value, schedule, disposal evidence, and related journals. Reconcile register totals to the fixed-asset and accumulated-depreciation accounts.</p></GuideSection>
    <GuideSection id="common-problems" title="Common problems"><ul className="list-disc space-y-2 pl-5"><li>Asset cannot be disposed: post depreciation due on or before the disposal date.</li><li>Depreciation is missing: check status, start date, useful life, and open period.</li><li>Net book value is unexpected: recheck cost, residual value, prior postings, and schedule.</li><li>Cash proceeds are missing: verify the bank account and disposal posting.</li></ul></GuideSection>
    <GuideSection id="completion-check" title="Completion check"><GuideChecklist items={["Asset identity and valuation match evidence", "Acquisition and account mappings were reviewed", "Only due depreciation was posted", "Disposal includes current depreciation and approved proceeds", "Register totals reconcile to the ledger"]} /></GuideSection>
  </div>;
}
