import { GuideCallout, GuideChecklist, GuideSection, GuideStep, GuideSteps } from "../../article-components";

export default function ManagePettyCashArticle() {
  return <div className="space-y-10">
    <GuideSection id="before-you-start" title="Before you start"><p>Confirm the entity, named custodian, petty-cash GL account, approved float ceiling, funding bank account, voucher evidence, and the date of the physical cash count.</p><GuideCallout tone="warning" title="Console does not replace the cash count">The register must agree with cash physically held by the custodian. Investigate a difference before replenishing it.</GuideCallout></GuideSection>
    <GuideSection id="establish-the-float" title="Establish the float"><GuideSteps><GuideStep title="Define the fund">Use a distinct name, custodian, and petty-cash account for the float. The fund belongs to the branch you choose, and is topped up from that branch&rsquo;s accounts.</GuideStep><GuideStep title="Set the ceiling">Use the formally approved imprest amount, not the amount currently requested.</GuideStep><GuideStep title="Fund it once">Choose the approved bank account and open posting date. Establishing the float moves cash from bank to petty cash.</GuideStep></GuideSteps></GuideSection>
    <GuideSection id="record-a-voucher" title="Record and post a voucher"><p>Create one voucher for supported spending, select the expense account, amount, date, tax code, and note, then save a draft for review. Posting debits expense and credits petty cash, reducing the live balance. A draft that is no longer needed can be cancelled; it never reaches the books.</p></GuideSection>
    <GuideSection id="monitor-the-register" title="Monitor the register and cash on hand"><p>Use Movement register to compare every inflow and outflow with vouchers and the physical count. The current balance is cash on hand, while To replenish is the shortfall from the ceiling. Money banked from the fund reads <strong>Returned to bank</strong>, and a count difference reads <strong>Count short</strong> or <strong>Count over</strong>.</p></GuideSection>
    <GuideSection id="replenish-the-float" title="Replenish the float"><p>Replenish only approved, posted spending. Confirm the shortfall, bank account, amount, and posting date. A normal imprest replenishment restores the fund to its ceiling rather than increasing the ceiling. Only the fund&rsquo;s own branch&rsquo;s bank accounts are offered.</p></GuideSection>
    <GuideSection id="reduce-the-float" title="Reduce the float and bank the extra">
      <p>When a fund needs less cash than it holds, <strong>Reduce float</strong> banks the extra. It needs the petty cash return key.</p>
      <GuideSteps>
        <GuideStep title="Count the tin first">Enter <strong>Cash counted</strong> and the <strong>New float</strong>. The drawer shows what the books say and the current float beside them.</GuideStep>
        <GuideStep title="Say why a count differs">If the count is not what the books say, <strong>Why the count differs</strong> appears and must be filled in. The difference goes to Cash over and short.</GuideStep>
        <GuideStep title="Bank it">Choose <strong>Into bank account</strong> (only the fund&rsquo;s own branch&rsquo;s accounts are offered), the date, and the deposit slip number as <strong>Reference</strong>, then select <strong>Bank</strong>, which names the amount. The deposit is an ordinary bank line, ready to match on reconciliation.</GuideStep>
      </GuideSteps>
      <GuideCallout tone="info" title="An example">
        Ikeja&rsquo;s fund has a ₦100,000 float and the books say it holds ₦80,000. Amaka Okafor, the custodian, counts ₦79,000 and the float is cut to ₦50,000. Amaka writes &ldquo;coins missing&rdquo; for the ₦1,000 short, which goes to Cash over and short. ₦29,000 is banked, and the tin keeps ₦50,000.
      </GuideCallout>
      <p>A float cut to nothing is a closure: use <strong>Close fund</strong> instead. If the count finds no more than the new float, there is nothing to bank; change the float with <strong>Edit fund</strong> instead.</p>
    </GuideSection>
    <GuideSection id="close-the-fund" title="Close a fund, and reopen it">
      <p><strong>Close fund</strong> banks every naira counted and stops the fund: it takes no vouchers, top-ups or float changes until it is reopened. Enter <strong>Cash counted</strong>, the date, and the bank account the cash goes into. A count that differs needs a reason, as for a reduction.</p>
      <p>It is refused while a voucher of the fund is not yet posted (draft, waiting for approval, or approved) or another return of the fund is still waiting on approval. The drawer lists what is in the way: post or cancel those vouchers, and settle the waiting return, first.</p>
      <p>A closed fund shows who closed it and when, and offers only <strong>Reopen</strong> and <strong>Edit fund</strong>. <strong>Reopen</strong> needs <strong>Why reopen it</strong>, and lets you set <strong>Float from now</strong>, which starts as the float before the closure. The fund comes back empty, ready for a top-up with Replenish, and the reopening is kept on the audit record with your reason.</p>
    </GuideSection>
    <GuideSection id="returns-and-void" title="Read returns, and void one">
      <p>The <strong>Returns</strong> tab lists every reduction and closure: <strong>Float reduced</strong> or <strong>Fund closed</strong>, what was banked, any difference, and its status. Open one to see the count, what the books said, why it differed, who counted it and who raised it.</p>
      <p><strong>Void</strong> reverses a return: the cash comes back on the fund&rsquo;s books and its float is restored, and voiding a closure reopens the fund. It needs the petty cash reverse key. A void is refused when:</p>
      <ul className="list-disc space-y-2 pl-5">
        <li>its bank line is matched on a reconciliation (unmatch it first);</li>
        <li>a later return of the same fund still stands (void that first);</li>
        <li>the fund&rsquo;s float has changed since, or a closed fund was reopened.</li>
      </ul>
      <p>A return an approver rejected comes back as a <strong>Draft</strong>. <strong>Cancel return</strong> removes it; it never reached the books, so nothing is reversed. Cancel return is not offered while the return&rsquo;s approval request is open, including after an approver sends it back: to drop one, withdraw the request under Workflow, My Submissions, which cancels the return.</p>
    </GuideSection>
    <GuideSection id="approval-route" title="Have a second person approve returns">
      <p>No school starts with an approval route for petty cash returns: with no route, a reduction or closure posts as soon as it is raised. The card <strong>Approval for petty cash returns</strong> on the Petty Cash screen offers a ready-made route the school may adopt. Reading the card needs the workflow template view key.</p>
      <GuideSteps>
        <GuideStep title="Choose the figure">Set <strong>Shortage that needs a second person</strong>. It starts at ₦5,000. The route stops a count more than that figure short, and every closure; anything else posts at once.</GuideStep>
        <GuideStep title="Adopt it">Select <strong>Adopt route</strong>. It needs the key to publish approval routes and someone who covers the whole school, because the route applies to every branch.</GuideStep>
        <GuideStep title="Fill the approver group">Adopting creates the group <strong>Finance Petty Cash Approver</strong> empty. Add the people who approve returns under <strong>Approver groups</strong>, or a return the route stops waits with nobody able to approve it.</GuideStep>
      </GuideSteps>
      <p>While a return waits, it reads that it is waiting for a second person, and it reaches the books once approved.</p>
      <p>If the approver sends a return back, its status reads <strong>Sent back</strong>, on its row in the returns list and when you open it. The status filter beside the fund filter offers <strong>All statuses</strong> or <strong>Sent back</strong>, to list only those. The person who sent it for approval sees <strong>Sent back to you</strong>, with the approver&rsquo;s reason, and <strong>Resume</strong>, which sends it back to the approver as it is. A return has no Edit: to change one, withdraw it under Workflow, My Submissions, which cancels it, and raise a new one. Nobody else gets Resume.</p>
    </GuideSection>
    <GuideSection id="correct-a-voucher" title="Correct a voucher posted in error"><GuideCallout tone="warning" title="Void the source voucher">Voiding reverses the expense posting and returns the amount to petty cash. Do not create an unrelated receipt or journal to hide the original mistake.</GuideCallout></GuideSection>
    <GuideSection id="common-problems" title="Common problems"><ul className="list-disc space-y-2 pl-5"><li>No fund appears: confirm the entity and petty-cash view access.</li><li>Voucher will not post: check the open period, account, amount, tax code, and permissions.</li><li>Replenishment exceeds the shortfall: recheck the physical count and approved exception.</li><li>Register and cash differ: stop and investigate missing, duplicated, or unposted vouchers.</li><li>Close fund lists vouchers not yet posted: post or cancel each one, then close again.</li><li>Edit fund refuses a lower float: the fund holds more than the new float. Reduce the float instead, which banks the extra.</li><li>Edit fund refuses to switch a fund off: it still holds cash. Close it instead, which banks the cash and records the count.</li><li>A return waits with nobody to approve it: the Finance Petty Cash Approver group is empty. Add its members.</li><li>Cancel return is missing on a draft return: its approval request is still open, perhaps sent back. Withdraw the request under Workflow, My Submissions instead: that cancels the return.</li></ul></GuideSection>
    <GuideSection id="completion-check" title="Completion check"><GuideChecklist items={["Custodian, ceiling, and GL account are approved", "Every spend has a posted voucher and evidence", "Register agrees with physical cash", "Replenishment restores only the approved shortfall", "Cash above the float was banked with a counted return", "Every count difference has a reason", "Corrections were made through the original voucher or return"]} /></GuideSection>
  </div>;
}
