import { GuideCallout, GuideChecklist, GuideSection, GuideStep, GuideSteps } from "../../article-components";

export default function ManagePettyCashArticle() {
  return <div className="space-y-10">
    <GuideSection id="before-you-start" title="Before you start"><p>Confirm the entity, named custodian, petty-cash GL account, approved float ceiling, funding bank account, voucher evidence, and the date of the physical cash count.</p><GuideCallout tone="warning" title="Console does not replace the cash count">The register must agree with cash physically held by the custodian. Investigate a difference before replenishing it.</GuideCallout></GuideSection>
    <GuideSection id="establish-the-float" title="Establish the float"><GuideSteps><GuideStep title="Define the fund">Use a distinct name, custodian, and petty-cash account for the float.</GuideStep><GuideStep title="Set the ceiling">Use the formally approved imprest amount, not the amount currently requested.</GuideStep><GuideStep title="Fund it once">Choose the approved bank account and open posting date. Establishing the float moves cash from bank to petty cash.</GuideStep></GuideSteps></GuideSection>
    <GuideSection id="record-a-voucher" title="Record and post a voucher"><p>Create one voucher for supported spending, select the expense account, amount, date, tax code, and note, then save a draft for review. Posting debits expense and credits petty cash, reducing the live balance.</p></GuideSection>
    <GuideSection id="monitor-the-register" title="Monitor the register and cash on hand"><p>Use Movement register to compare every inflow and outflow with vouchers and the physical count. The current balance is cash on hand, while To replenish is the shortfall from the ceiling.</p></GuideSection>
    <GuideSection id="replenish-the-float" title="Replenish the float"><p>Replenish only approved, posted spending. Confirm the shortfall, bank account, amount, and posting date. A normal imprest replenishment restores the fund to its ceiling rather than increasing the ceiling.</p></GuideSection>
    <GuideSection id="correct-a-voucher" title="Correct a voucher posted in error"><GuideCallout tone="warning" title="Void the source voucher">Voiding reverses the expense posting and returns the amount to petty cash. Do not create an unrelated receipt or journal to hide the original mistake.</GuideCallout></GuideSection>
    <GuideSection id="common-problems" title="Common problems"><ul className="list-disc space-y-2 pl-5"><li>No fund appears: confirm the entity and petty-cash view access.</li><li>Voucher will not post: check the open period, account, amount, tax code, and permissions.</li><li>Replenishment exceeds the shortfall: recheck the physical count and approved exception.</li><li>Register and cash differ: stop and investigate missing, duplicated, or unposted vouchers.</li></ul></GuideSection>
    <GuideSection id="completion-check" title="Completion check"><GuideChecklist items={["Custodian, ceiling, and GL account are approved", "Every spend has a posted voucher and evidence", "Register agrees with physical cash", "Replenishment restores only the approved shortfall", "Corrections were made through the original voucher"]} /></GuideSection>
  </div>;
}
