import { GuideCallout, GuideChecklist, GuideSection, GuideStep, GuideSteps } from "../../article-components";

export default function SendPayoutsAndResolveSettlementsArticle() {
  return <div className="space-y-10">
    <GuideSection id="before-you-start" title="Before you start">
      <p>Confirm the entity, payable, beneficiary name, bank and account details, amount, currency, narration, provider, approval route, maker-checker separation, and proof that the item has not already been paid.</p>
      <p><strong>Payouts</strong> and <strong>Batches</strong> pay out of online money the platform holds, so they only work where online payments are set to <strong>Held, then paid to each branch</strong>. Where they go <strong>Straight to each branch&rsquo;s bank</strong>, both screens show a notice instead: pay suppliers from the bank and record the payment. Earlier payouts stay listed in the Transactions Log.</p>
      <GuideCallout tone="warning" title="Never retry from appearance alone">A pending or failed display does not prove money did not leave. Check provider reference, transaction log, webhook history, settlement, and bank evidence before creating another payout.</GuideCallout>
    </GuideSection>
    <GuideSection id="prepare-the-beneficiary" title="Prepare the beneficiary and payable"><GuideSteps><GuideStep title="Verify the liability">Trace the payout to the approved vendor or free-form obligation and confirm remaining payable.</GuideStep><GuideStep title="Verify the beneficiary">Use independently confirmed bank details and respect field masking and access controls.</GuideStep><GuideStep title="Check duplicates">Search reference, beneficiary, amount, and date before sending.</GuideStep></GuideSteps></GuideSection>
    <GuideSection id="send-one-or-build-a-batch" title="Send one payout or build a batch"><p>Use New payout for one approved transfer. Use Batches for bulk disbursement, validate every row, totals, duplicates, and errors, then route the batch through maker-checker approval. The approver must review the actual file and total, not only its label.</p></GuideSection>
    <GuideSection id="follow-provider-status" title="Follow provider and posting status"><p>Created and processing mean settlement is not final. Settled means the provider confirmed the transfer and the journal was booked. Failed or reversed requires investigation of the provider reason and accounting effect.</p></GuideSection>
    <GuideSection id="reconcile-settlement" title="Book the provider's settlement">
      <p>A confirmed online payment waits in <strong>gateway clearing</strong> until the provider pays it on to the bank, less its fee. <strong>Settlement</strong> matches the provider&rsquo;s records to the imported bank lines and lets you book a bank line as the settlement of the payments it carries. Booking is the one thing this screen posts, and it needs the permission to book settlements.</p>
      <p>The screen has four views: <strong>To book</strong> (bank lines the system thinks carry waiting payments), <strong>Matched</strong>, <strong>Unsettled</strong> (confirmed, no bank line yet), and <strong>Unmatched bank lines</strong>. <strong>Re-run match</strong> checks again after a new statement import.</p>
      <GuideSteps>
        <GuideStep title="Open the bank line">In <strong>To book</strong>, select <strong>Book</strong> on a suggestion; its payments arrive already ticked. For a line the system did not suggest, open it under <strong>Unmatched bank lines</strong> and select <strong>Book as settlement</strong>; nothing is ticked.</GuideStep>
        <GuideStep title="Tick the payments it carries">Under <strong>Payments this line settles</strong>, tick every payment the provider paid in this line. The <strong>Settlement journal</strong> beneath shows what will post: Dr bank (what arrived), Dr <strong>Bank charges (provider fees)</strong> (the gap), Cr <strong>Gateway clearing</strong> (the payments).</GuideStep>
        <GuideStep title="Choose the date, then book">Leave <strong>Posting date (optional)</strong> blank to date the journal on the bank line&rsquo;s day, or the first open day after it. Select <strong>Book settlement</strong>. The journal posts in the bank account&rsquo;s branch.</GuideStep>
      </GuideSteps>
      <GuideCallout tone="info" title="An example">
        Bright Star&rsquo;s Ikeja account shows ₦985,000 from Paystack on Wednesday. Ada Nwosu ticks Tuesday&rsquo;s four online payments, ₦1,000,000 in all. The journal books ₦985,000 to the bank, ₦15,000 to bank charges, and takes ₦1,000,000 out of gateway clearing. Had Ada ticked only three payments worth ₦750,000, the dialog would say the line brings more than the payments picked, and <strong>Book settlement</strong> would stay off until they ticked the fourth.
      </GuideCallout>
      <p>The dialog stops a booking the figures cannot explain before you send it: a line that brings more than the payments ticked, provider fees that do not add up to the shortfall, or a line dated before a payment it claims to settle. The server also refuses a payment that is no longer waiting, that belongs to another branch, or that the platform held. To undo a booking, unmatch the line in <strong>Bank Reconciliation</strong>; that reverses the journal.</p>
      <p>Payments the platform held are paid to the branch by the platform&rsquo;s own run and are never booked here. The book-against-bank close still happens in <strong>Bank Reconciliation</strong>.</p>
    </GuideSection>
    <GuideSection id="recover-a-failure" title="Recover a failure without double-paying"><p>Use Transactions and Needs Attention to inspect reference, attempt history, error, and linked payout. Correct configuration or data first. Replay a provider event only after proving it has not posted. If the provider moved money but Console did not, escalate with safe references rather than sending again.</p></GuideSection>
    <GuideSection id="common-problems" title="Common problems"><ul className="list-disc space-y-2 pl-5"><li>Payout stays pending: check provider status and webhook history before retrying.</li><li>Batch cannot submit: resolve row errors, duplicates, total limits, and approval requirements.</li><li>Payouts shows a notice instead of a list: online payments go straight to each branch&rsquo;s bank, so there is nothing held to pay out of.</li><li>A bank line from the provider sits under Unmatched bank lines: open it and book it as a settlement, ticking the payments it carries.</li><li>Book settlement stays off: read the message under the journal. Usually a payment is missing from the ticks, or one ticked was received after the line&rsquo;s date.</li><li>There is no To book view and no Book button: booking needs the permission to book settlements.</li><li>Bank details are hidden: sensitive access is intentionally separate from payout view access.</li></ul></GuideSection>
    <GuideSection id="completion-check" title="Completion check"><GuideChecklist items={["Payable and beneficiary were independently verified", "Duplicate search and approval controls were completed", "Provider and accounting statuses agree", "Each provider bank line is booked against the payments it carries", "Nothing is left in gateway clearing longer than expected", "No retry or replay occurred without proof of non-posting"]} /></GuideSection>
  </div>;
}
