import { GuideCallout, GuideChecklist, GuideSection, GuideStep, GuideSteps } from "../../article-components";

export default function SendPayoutsAndResolveSettlementsArticle() {
  return <div className="space-y-10">
    <GuideSection id="before-you-start" title="Before you start">
      <p>Confirm the entity, payable, beneficiary name, bank and account details, amount, currency, narration, provider, approval route, maker-checker separation, and proof that the item has not already been paid.</p>
      <p><strong>Payouts</strong> and <strong>Batches</strong> pay out of online money the platform holds, so they only work where online payments are set to <strong>Held, then paid to each branch</strong>. Where they go <strong>Straight to each branch&rsquo;s bank</strong>, both screens show a notice instead: pay suppliers from the bank and record the payment. Earlier payouts stay listed in the Transactions Log, which lists the money coming in and going out.</p>
      <GuideCallout tone="warning" title="Never retry from appearance alone">A pending or failed display does not prove money did not leave. Check provider reference, Payment provider activity, Transactions Log, webhook history, settlement, and bank evidence before creating another payout.</GuideCallout>
    </GuideSection>
    <GuideSection id="choose-who-holds-payments" title="Choose who holds online payments">
      <p>Open <strong>Finance Settings, Banking and cash</strong>. The <strong>Online payments</strong> panel sets <strong>Who holds online payments</strong> for every branch at once:</p>
      <ul className="list-disc space-y-2 pl-5">
        <li><strong>Held, then paid to each branch</strong> (the default): payments are held and paid into each branch&rsquo;s bank every <strong>Settlement interval (days)</strong>, 1 to 7. Online payouts draw on what is held for the branch.</li>
        <li><strong>Straight to each branch&rsquo;s bank</strong>: each branch&rsquo;s collection account takes its own payments. There are no online payouts or online refunds; pay and refund from the bank.</li>
      </ul>
      <p>A change never takes effect at once. It waits for the first day of next month, and a move to direct also waits until nothing is held for the school. Moving to direct is refused until every branch&rsquo;s collection account is set up with the provider: the panel lists each branch&rsquo;s collection account with <strong>Create subaccount</strong> or <strong>Refresh subaccount</strong>, which asks for the bank&rsquo;s code at the provider (058 for GTBank, 057 for Zenith). <strong>Clearing warning (days)</strong>, 1 to 60, sets when the month-end checklist&rsquo;s <strong>Gateway clearing current (online payments paid into the bank)</strong> check warns about online payments still waiting to be paid into the bank longer than that.</p>
      <p>Reading the panel needs the payment settings view key. Changing it needs the payment settings update key and someone who covers the whole school, and a change of mode asks you to confirm before <strong>Save online payments</strong> applies it.</p>
      <GuideCallout tone="info" title="An example">
        On 12 March, Kemi Balogun switches Bright Star to straight to each branch&rsquo;s bank. Lekki&rsquo;s collection account is not set up with the provider yet, so the panel refuses and names Lekki. Kemi creates Lekki&rsquo;s subaccount and saves again. The change shows as waiting from 1 April, and Bright Star&rsquo;s payments are still held until then.
      </GuideCallout>
    </GuideSection>
    <GuideSection id="prepare-the-beneficiary" title="Prepare the beneficiary and payable"><GuideSteps><GuideStep title="Verify the liability">Trace the payout to the approved vendor or free-form obligation and confirm remaining payable.</GuideStep><GuideStep title="Verify the beneficiary">Use independently confirmed bank details and respect field masking and access controls.</GuideStep><GuideStep title="Check duplicates">Search reference, beneficiary, amount, and date before sending.</GuideStep></GuideSteps></GuideSection>
    <GuideSection id="send-one-or-build-a-batch" title="Send one payout or build a batch"><p>Use New payout for one approved transfer. Use Batches for bulk disbursement, validate every row, totals, duplicates, and errors, then route the batch through maker-checker approval. The approver must review the actual file and total, not only its label. In <strong>Build batch</strong>, each line&rsquo;s <strong>Withholding tax</strong> comes from the vendor&rsquo;s tax code unless you type it, and <strong>Withholding tax kept back</strong> totals it.</p><p>A batch with its approvers reads <strong>Awaiting approval</strong>, not Draft. The status filter on Batches offers <strong>Draft</strong>, <strong>Awaiting approval</strong>, <strong>Processing</strong>, <strong>Completed</strong>, <strong>Partly completed</strong>, <strong>Failed</strong> and <strong>Sent back</strong>, and each lists only the batches that read that word. The tiles beside <strong>Batches</strong>, <strong>Queued value</strong> and <strong>Completed (7d)</strong> count <strong>Drafts</strong> (not yet sent for approval), <strong>Awaiting approval</strong> (with the approver) and <strong>Sent back</strong> (back with whoever sent them).</p><p>If an approver sends a batch back, its status reads <strong>Sent back</strong>, on its row and in its drawer, and the drawer shows the approver&rsquo;s note. It is listed only under Sent back, never under Draft, and the Drafts tile does not count it. Whoever sent it for approval sees <strong>Resume</strong>, which sends it back to the approver as it is. A batch has no Edit: to change one, withdraw it under Workflow, My Submissions and send it again. <strong>Submit</strong> is not offered while the batch&rsquo;s approval request is open, whether it is with the approvers or sent back.</p></GuideSection>
    <GuideSection id="follow-provider-status" title="Follow provider and posting status"><p>Created and processing mean settlement is not final. Settled means the provider confirmed the transfer and the journal was booked. Failed or reversed requires investigation of the provider reason and accounting effect.</p></GuideSection>
    <GuideSection id="reconcile-settlement" title="Book the provider's settlement">
      <p>A confirmed online payment waits in <strong>Gateway clearing (online payments not yet in the bank)</strong> until the provider pays it on to the bank, less its fee. <strong>Settlement</strong> matches the provider&rsquo;s records to the imported bank lines and lets you book a bank line as the settlement of the payments it carries. Booking is the one thing this screen posts, and it needs the permission to book settlements.</p>
      <p>The screen has four views: <strong>To book</strong> (bank lines the system thinks carry waiting payments), <strong>Matched</strong>, <strong>Unsettled</strong> (confirmed, no bank line yet), and <strong>Unmatched bank lines</strong>. <strong>Re-run match</strong> checks again after a new statement import.</p>
      <GuideSteps>
        <GuideStep title="Open the bank line">In <strong>To book</strong>, select <strong>Book</strong> on a suggestion; its payments arrive already ticked. For a line the system did not suggest, open it under <strong>Unmatched bank lines</strong> and select <strong>Book as settlement</strong>; nothing is ticked.</GuideStep>
        <GuideStep title="Tick the payments it carries">Under <strong>Payments this line settles</strong>, tick every payment the provider paid in this line. The <strong>Settlement journal</strong> beneath shows what will post: Dr bank (what arrived), Dr <strong>Bank charges (provider fees)</strong> (the gap), Cr <strong>Gateway clearing (online payments not yet in the bank)</strong> (the payments).</GuideStep>
        <GuideStep title="Choose the date, then book">Leave <strong>Posting date (optional)</strong> blank to date the journal on the bank line&rsquo;s day, or the first open day after it. Select <strong>Book settlement</strong>. The journal posts in the bank account&rsquo;s branch.</GuideStep>
      </GuideSteps>
      <GuideCallout tone="info" title="An example">
        Bright Star&rsquo;s Ikeja account shows ₦985,000 from Paystack on Wednesday. Ada Nwosu ticks Tuesday&rsquo;s four online payments, ₦1,000,000 in all. The journal books ₦985,000 to the bank, ₦15,000 to bank charges, and takes ₦1,000,000 out of gateway clearing. Had Ada ticked only three payments worth ₦750,000, the dialog would say the line brings more than the payments picked, and <strong>Book settlement</strong> would stay off until they ticked the fourth.
      </GuideCallout>
      <p>The dialog stops a booking the figures cannot explain before you send it: a line that brings more than the payments ticked, provider fees that do not add up to the shortfall, or a line dated before a payment it claims to settle. The server also refuses a payment that is no longer waiting, that belongs to another branch, or that the platform held. To undo a booking, unmatch the line in <strong>Bank Reconciliation</strong>; that reverses the journal.</p>
      <p>Payments the platform held are paid to the branch by the platform&rsquo;s own run and are never booked here. The book-against-bank close still happens in <strong>Bank Reconciliation</strong>.</p>
    </GuideSection>
    <GuideSection id="held-settlements" title="Pay branches the money held for them">
      <p>At a school whose payments are held, <strong>Held Settlements</strong> shows what the platform paid each branch. A school&rsquo;s own finance team reads its list there, read-only. Platform staff with the platform settlement view key see every school&rsquo;s settlements that need acting on instead.</p>
      <GuideSteps>
        <GuideStep title="Find what is due">The list opens on <strong>Due now</strong>: every settlement not yet paid, and any built today. A morning run builds one settlement per branch whose payment day has come. Narrow it with the status filter and <strong>All schools</strong>.</GuideStep>
        <GuideStep title="Check the figures">Open a settlement. <strong>Payments covered</strong>, less the <strong>Provider fees</strong> and the <strong>Transfer fee</strong>, gives <strong>To send</strong>, paid into the branch&rsquo;s collection account. The branch bears both fees.</GuideStep>
        <GuideStep title="Put it forward">On a settlement that reads <strong>Ready to submit</strong>, select <strong>Submit for approval</strong>. It needs the key to submit platform settlements.</GuideStep>
        <GuideStep title="Two other people approve it">Two other platform people approve it in <strong>Workflow, Approvals</strong>. Whoever submits it cannot approve it. On the second approval the money is sent, and once it arrives the school&rsquo;s books record it at the branch by themselves: Dr bank, Dr bank charges, Cr <strong>Gateway clearing (online payments not yet in the bank)</strong>.</GuideStep>
      </GuideSteps>
      <p>A settlement reads <strong>Being prepared</strong>, <strong>Ready to submit</strong>, <strong>Waiting for approval</strong>, <strong>Approved, sending</strong>, <strong>Paid</strong> or <strong>Failed</strong>. A failed transfer&rsquo;s payments go into the next settlement. If nobody can approve the route yet, submitting says so and the settlement waits: releasing held money without its two approvers is not offered.</p>
      <GuideCallout tone="info" title="An example">
        Bright Star&rsquo;s Lekki Branch took ₦2,000,000 online this week. Paystack&rsquo;s fees came to ₦30,000 and the transfer fee is ₦50. Yusuf Bello submits the ₦1,969,950 settlement; Grace Eze and Ibrahim Musa approve it. Yusuf could not have been one of the two.
      </GuideCallout>
    </GuideSection>
    <GuideSection id="held-reconciliations" title="Check the money held against the provider">
      <p><strong>Held Reconciliations</strong> is for platform staff only. Under <strong>Daily checks</strong>, every morning the money held for schools is compared with the provider&rsquo;s balance: one row per provider, currency and day, showing what the <strong>Provider says</strong>, what the <strong>Books say</strong>, the <strong>Difference</strong>, and whether it <strong>Agrees</strong>, <strong>Disagrees</strong> or <strong>Could not check</strong>. A disagreement opens an incident under Health. Choose <strong>Disagreements</strong> to see only those, and open a row for the working behind each figure.</p>
      <p><strong>Paystack balance swept automatically</strong> is a setting of the platform&rsquo;s own merchant account, never a school&rsquo;s. Turn it on when Paystack settles the platform&rsquo;s balance to its bank by itself: the check then counts each sweep once and takes it off the books&rsquo; figure, so a sweep is not reported as a mismatch. A sweep is allowed for in the check, not booked as a journal.</p>
      <GuideSteps>
        <GuideStep title="Change the switch">Flip the switch. It needs the platform provider update key; with the view key alone the card reads <strong>You have read-only access</strong>.</GuideStep>
        <GuideStep title="Give a reason">Confirm with a reason, for example that Paystack confirmed automatic daily settlement is on for the account. The reason is kept on the audit trail with your name, and the change applies from the next check.</GuideStep>
      </GuideSteps>
      <p>The card also shows who set it, when it last changed, the <strong>Check tolerance</strong> (changed in Settings, Advanced catalogue, as <strong>Held-ledger Reconciliation Tolerance</strong>, typed in whole naira; 0 means the two must agree exactly), and <strong>Sweeps counted</strong>, with the list of sweeps the check has counted beneath it for readers who also hold the platform settlement view key.</p>
    </GuideSection>
    <GuideSection id="recover-a-failure" title="Recover a failure without double-paying"><p>Open <strong>Payment provider activity</strong>, under Payments, to see every request CodeX made to the payment provider, refused and failed ones included. Each row shows <strong>When</strong>, <strong>What</strong> was asked for, the <strong>Reference</strong> with a copy button, the <strong>Result</strong> (<strong>Succeeded</strong> or <strong>Failed</strong>), the <strong>Message</strong> and <strong>Who</strong> asked, or System when the platform acted by itself; a failed row&rsquo;s message is the provider&rsquo;s full reason, in red. Filter by what happened, such as <strong>Payout failed</strong> or <strong>Payout refused: held funds</strong>, and by <strong>Failed or refused</strong>. It needs the payment reports view key, and a reader tied to some branches sees only their branches&rsquo; activity. <strong>Transactions Log</strong> lists the money coming in and going out, and <strong>Needs Attention</strong> shows provider events that did not make it into the books, with why each one failed. Correct configuration or data first. Replay a provider event only after proving it has not posted. If the provider moved money but Console did not, escalate with safe references rather than sending again.</p><GuideCallout tone="info" title="An example">A payout to Zenith Stationers shows Failed on Payouts. Grace Eze chooses <strong>Payout failed</strong> on Payment provider activity and reads the provider&rsquo;s reason: the account number does not match the account name. No money left, so Grace has the vendor&rsquo;s bank details corrected and sends a new payout. Had the row read <strong>Payout confirmed</strong> and Succeeded, the money had left, and sending again would pay Zenith twice.</GuideCallout></GuideSection>
    <GuideSection id="common-problems" title="Common problems"><ul className="list-disc space-y-2 pl-5"><li>Payout stays pending: check provider status and webhook history before retrying.</li><li>Batch cannot submit: resolve row errors, duplicates, total limits, and approval requirements. Submit is not offered at all while the batch&rsquo;s approval request is open, including after it is sent back: resume it, or withdraw the request first.</li><li>Payouts shows a notice instead of a list: online payments go straight to each branch&rsquo;s bank, so there is nothing held to pay out of.</li><li>A bank line from the provider sits under Unmatched bank lines: open it and book it as a settlement, ticking the payments it carries.</li><li>Book settlement stays off: read the message under the journal. Usually a payment is missing from the ticks, or one ticked was received after the line&rsquo;s date.</li><li>There is no To book view and no Book button: booking needs the permission to book settlements.</li><li>The Online payments panel is greyed: changing it needs the payment settings update key and someone who covers the whole school.</li><li>A move to straight to each branch&rsquo;s bank is refused: a branch&rsquo;s collection account is missing or not set up with the provider. The panel names the branch.</li><li>A held settlement shows no Submit: it is still being prepared, already waiting for approval, or you lack the key to submit platform settlements.</li><li>A daily check disagrees every day since the platform&rsquo;s balance began being swept: turn on Paystack balance swept automatically, with a reason.</li><li>Bank details are hidden: sensitive access is intentionally separate from payout view access.</li></ul></GuideSection>
    <GuideSection id="completion-check" title="Completion check"><GuideChecklist items={["Payable and beneficiary were independently verified", "Duplicate search and approval controls were completed", "Provider and accounting statuses agree", "Each provider bank line is booked against the payments it carries", "Nothing is left in gateway clearing longer than expected", "Held settlements due today are submitted and approved by two other people", "Every daily check agrees, or its incident is being worked", "No retry or replay occurred without proof of non-posting"]} /></GuideSection>
  </div>;
}
