import { GuideCallout, GuideChecklist, GuideSection, GuideStep, GuideSteps } from "../../article-components";

export default function SendPayoutsAndResolveSettlementsArticle() {
  return <div className="space-y-10">
    <GuideSection id="before-you-start" title="Before you start"><p>Confirm the entity, payable, beneficiary name, bank and account details, amount, currency, narration, provider, approval route, maker-checker separation, and proof that the item has not already been paid.</p><GuideCallout tone="warning" title="Never retry from appearance alone">A pending or failed display does not prove money did not leave. Check provider reference, transaction log, webhook history, settlement, and bank evidence before creating another payout.</GuideCallout></GuideSection>
    <GuideSection id="prepare-the-beneficiary" title="Prepare the beneficiary and payable"><GuideSteps><GuideStep title="Verify the liability">Trace the payout to the approved vendor or free-form obligation and confirm remaining payable.</GuideStep><GuideStep title="Verify the beneficiary">Use independently confirmed bank details and respect field masking and access controls.</GuideStep><GuideStep title="Check duplicates">Search reference, beneficiary, amount, and date before sending.</GuideStep></GuideSteps></GuideSection>
    <GuideSection id="send-one-or-build-a-batch" title="Send one payout or build a batch"><p>Use New payout for one approved transfer. Use Batches for bulk disbursement, validate every row, totals, duplicates, and errors, then route the batch through maker-checker approval. The approver must review the actual file and total, not only its label.</p></GuideSection>
    <GuideSection id="follow-provider-status" title="Follow provider and posting status"><p>Created and processing mean settlement is not final. Settled means the provider confirmed the transfer and the journal was booked. Failed or reversed requires investigation of the provider reason and accounting effect.</p></GuideSection>
    <GuideSection id="reconcile-settlement" title="Reconcile settlement evidence"><p>Use Settlement to compare confirmed collections and payouts with imported bank lines. It is read-only and observes provider fees or unmatched movements. Complete the authoritative close in Bank Reconciliation.</p></GuideSection>
    <GuideSection id="recover-a-failure" title="Recover a failure without double-paying"><p>Use Transactions and Needs Attention to inspect reference, attempt history, error, and linked payout. Correct configuration or data first. Replay a provider event only after proving it has not posted. If the provider moved money but Console did not, escalate with safe references rather than sending again.</p></GuideSection>
    <GuideSection id="common-problems" title="Common problems"><ul className="list-disc space-y-2 pl-5"><li>Payout stays pending: check provider status and webhook history before retrying.</li><li>Batch cannot submit: resolve row errors, duplicates, total limits, and approval requirements.</li><li>Settlement line is unmatched: import the complete statement and use Bank Reconciliation.</li><li>Bank details are hidden: sensitive access is intentionally separate from payout view access.</li></ul></GuideSection>
    <GuideSection id="completion-check" title="Completion check"><GuideChecklist items={["Payable and beneficiary were independently verified", "Duplicate search and approval controls were completed", "Provider and accounting statuses agree", "Settlement was traced to bank evidence", "No retry or replay occurred without proof of non-posting"]} /></GuideSection>
  </div>;
}
