import { GuideCallout, GuideChecklist, GuideSection, GuideStep, GuideSteps } from "../../article-components";

export default function SubmitAndSettleExpenseClaimArticle() {
  return <div className="space-y-10">
    <GuideSection id="before-you-start" title="Before you start"><p>Confirm the active entity, claimant or payee, claim date, expense accounts, tax treatment, cost centres, supporting receipts, approval evidence, and settlement account.</p><GuideCallout tone="warning" title="Keep the source record complete">Use the expense claim for the expense and reimbursement. A manual journal can change the ledger without advancing the claim or preserving its receipt evidence.</GuideCallout></GuideSection>
    <GuideSection id="create-the-claim" title="Create the claim and its lines"><GuideSteps><GuideStep title="Identify the claimant">Choose the correct employee or payee and provide a traceable purpose and date.</GuideStep><GuideStep title="Enter supported lines">For each item, confirm description, expense account, amount, tax code, cost centre, and any required dimensions.</GuideStep><GuideStep title="Check totals">Compare the line total with the approved schedule before saving.</GuideStep></GuideSteps></GuideSection>
    <GuideSection id="attach-and-check-evidence" title="Attach and check receipts"><p>Attach the correct PDF or image to each line while the claim is still editable, then open it through your signed-in session. Confirm it belongs to the line and resolve any Missing badge before submission.</p></GuideSection>
    <GuideSection id="submit-and-review" title="Submit and review the claim"><p>Select Submit for approval after the coding and receipt evidence are complete. The claim enters the configured queue and each eligible approver receives a notice. Final approval posts the expense and the amount owed.</p><GuideCallout tone="info" title="Approval is the accrual">Awaiting approval has not reached the ledger. Approved means the expense and reimbursement liability are in the ledger, but cash has not left the bank.</GuideCallout></GuideSection>
    <GuideSection id="settle-the-claim" title="Settle the approved claim"><p>Open a posted claim, choose the approved bank account and payment date, and confirm the payee and amount. Settlement clears the payable against bank.</p></GuideSection>
    <GuideSection id="void-a-mistake" title="Void a claim raised in error"><GuideCallout tone="warning" title="Void is an accounting reversal">Void only the wrong claim, record the correction reason, and verify the reversal journal. If money has already left the bank, follow the authorized recovery process before treating the case as corrected.</GuideCallout></GuideSection>
    <GuideSection id="common-problems" title="Common problems"><ul className="list-disc space-y-2 pl-5"><li>Receipt will not open: retry while signed in, then confirm the file still exists.</li><li>No approval notice: confirm the claim was submitted, not merely saved as a draft, and that the approval role has an active holder.</li><li>Approval fails: check the period, accounts, tax code, and required dimensions.</li><li>Settlement is unavailable: confirm the claim is posted, unpaid, and within your permission scope.</li><li>The claimant is wrong: correct the draft or return it instead of paying and offsetting later.</li></ul></GuideSection>
    <GuideSection id="completion-check" title="Completion check"><GuideChecklist items={["Every line has approved evidence", "Accounts, tax, cost centres, and totals were reviewed", "The claim status matches the real stage", "Payee, bank, date, and amount agree", "Claim, journal, and bank evidence reconcile"]} /></GuideSection>
  </div>;
}
