import { GuideCallout, GuideChecklist, GuideSection, GuideStep, GuideSteps } from "../../article-components";

export default function SubmitAndSettleExpenseClaimArticle() {
  return <div className="space-y-10">
    <GuideSection id="before-you-start" title="Before you start"><p>Confirm the active entity, claimant or payee, claim date, expense accounts, tax treatment, cost centres, supporting receipts, approval evidence, and settlement account.</p><GuideCallout tone="warning" title="Keep the source record complete">Use the expense claim for the expense and reimbursement. A manual journal can change the ledger without advancing the claim or preserving its receipt evidence.</GuideCallout></GuideSection>
    <GuideSection id="create-the-claim" title="Create the claim and its lines"><GuideSteps><GuideStep title="Identify the claimant">Choose the correct employee or payee and provide a traceable purpose and date.</GuideStep><GuideStep title="Enter supported lines">For each item, confirm description, expense account, amount, tax code, cost centre, and any required dimensions.</GuideStep><GuideStep title="Check totals">Compare the line total with the approved schedule before saving.</GuideStep></GuideSteps></GuideSection>
    <GuideSection id="attach-and-check-evidence" title="Attach and check receipts"><p>Attach the correct PDF or image to each line while the claim is still editable, then open it through your signed-in session. Confirm it belongs to the line and resolve any Missing badge before submission.</p></GuideSection>
    <GuideSection id="submit-and-review" title="Submit and review the claim"><p>Select Submit for approval after the coding and receipt evidence are complete. The claim enters the configured queue and each eligible approver receives a notice. Final approval posts the expense and the amount owed.</p><p>If the approver sends a claim back, it reads <strong>Sent back</strong>, on its row and when you open it, and the status filter lists it only under <strong>Sent back</strong>, not under <strong>Draft</strong>. The person who sent it for approval sees <strong>Sent back to you</strong> on it, with the approver&rsquo;s reason. They can attach or remove receipts on its lines, then select <strong>Resume</strong> to send it back into the same approval. To change anything else, withdraw it under Workflow, My Submissions. Nobody else can change the receipts or resume it. Where a draft offers <strong>Approve</strong> and <strong>Reject</strong> directly, neither is offered while its approval request is open, such as after it is sent back: to reject it, withdraw the request first.</p><p>The status filter offers <strong>Draft</strong>, <strong>Awaiting approval</strong>, <strong>Approved</strong>, <strong>Part-paid</strong>, <strong>Paid</strong>, <strong>Rejected</strong> and <strong>Sent back</strong>, and each lists only the claims that read that word. <strong>Export</strong> takes the same filter, so the file holds the claims the list shows, Sent back included.</p><p>The <strong>Open claims</strong> tile counts what reads <strong>Draft</strong>, <strong>Awaiting approval</strong>, <strong>Approved</strong> or <strong>Part-paid</strong>, as its hint says: draft, awaiting approval or awaiting payment. A claim sent back is not counted there. <strong>Awaiting payment</strong> is what is still owed on approved and part-paid claims.</p><GuideCallout tone="info" title="Approval books what is owed">Awaiting approval has not reached the ledger. Approved means the expense is booked and the amount is owed to the claimant; inside the claim the <strong>Approved</strong> step reads <strong>Booked as owed to the staff member</strong>. No cash has left the bank yet. A claim reimbursed in part reads Part-paid instead.</GuideCallout></GuideSection>
    <GuideSection id="settle-the-claim" title="Settle the approved claim"><p>Open an approved claim and select <strong>Pay</strong>. Choose the approved bank account and payment date, and confirm the payee. <strong>Amount to pay</strong> starts at the whole balance due: pay all of it, or a smaller amount now and the rest later, and the line under the box says how much will be left. An amount over the balance due, or of nothing, is refused rather than cut down, and the button reads <strong>Pay</strong> with the amount typed. Each payment clears that much of what is owed against bank.</p><p>A claim paid in part reads <strong>Part-paid</strong> with what is left, for example <strong>Part-paid, ₦35,000.00 left</strong>, and its button reads <strong>Pay again</strong>. Inside the claim the amount tile reads <strong>Left to pay</strong>, with what has been paid so far beneath it, and the claim reads <strong>Paid</strong> once the balance is cleared.</p><GuideCallout tone="info" title="An example">Tobi Okafor&rsquo;s claim for a training trip is ₦50,000. Finance pays ₦15,000 on Monday, so the claim reads Part-paid, ₦35,000.00 left. On Friday Amaka Eze selects Pay again, and Amount to pay starts at ₦35,000. Had Amaka typed ₦40,000, the drawer would have said only ₦35,000.00 is left to pay on this claim, and Pay would have stayed off.</GuideCallout></GuideSection>
    <GuideSection id="void-a-mistake" title="Void a claim raised in error"><GuideCallout tone="warning" title="Void is an accounting reversal">Void only the wrong claim, record the correction reason, and verify the reversal journal. If money has already left the bank, follow the authorized recovery process before treating the case as corrected.</GuideCallout></GuideSection>
    <GuideSection id="common-problems" title="Common problems"><ul className="list-disc space-y-2 pl-5"><li>Receipt will not open: retry while signed in, then confirm the file still exists.</li><li>No approval notice: confirm the claim was submitted, not merely saved as a draft, and that the approval role has an active holder.</li><li>Approval fails: check the period, accounts, tax code, and required dimensions.</li><li>Settlement is unavailable: confirm the claim is approved, not yet paid in full, and within your permission scope.</li><li>Pay stays off in the drawer: choose a payment date, and enter an amount above nothing and no more than is left to pay.</li><li>Void is missing: a claim cannot be voided once any of it has been paid, so a Part-paid claim cannot be voided.</li><li>The claimant is wrong: correct the draft or return it instead of paying and offsetting later.</li></ul></GuideSection>
    <GuideSection id="completion-check" title="Completion check"><GuideChecklist items={["Every line has approved evidence", "Accounts, tax, cost centres, and totals were reviewed", "The claim status matches the real stage", "Payee, bank, date, and amount agree, and every part payment adds up to the claim", "Claim, journal, and bank evidence reconcile"]} /></GuideSection>
  </div>;
}
