const FINANCE_RECEIPTS_ALLOCATION = "/finance/receivables/receipts";

export const routesPath = {
  AUTH: {
    LOGIN: "/login",
    SIGNUP: "/signup",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password/:activation_key",
    RESET_PASSWORD_LINK: (key: string) => `/reset-password/${key}`,
    ACTIVATE: "/activate/:activation_key",
    ACTIVATE_LINK: (key: string) => `/activate/${key}`,
    // Literal prefix so this can never shadow other "/<segment>/login" URLs
    // (it previously matched /admin/login, /school/login, etc.).
    SPECIAL_LOGIN: "/sp-l/:email",
    SPECIAL_LOGIN_LINK: (email: string) => `/sp-l/${encodeURIComponent(email)}`,
    VENDOR_RFQ: "/vendor/rfq/:token",
    VENDOR_RFQ_LINK: (token: string) => `/vendor/rfq/${encodeURIComponent(token)}`,
  },
  PROTECTED: {
    OVERVIEW: { INDEX: "/overview" },
    NOTIFICATIONS: "/notifications",
    NOTIFICATIONS_ADMIN: "/notifications/admin",
    SETTINGS: { INDEX: "/settings" },
    SUPPORT: { INDEX: "/support", TICKETS: "/support/tickets", NEW: "/support/tickets/new", DETAIL_PATH: "/support/tickets/:id", DETAIL: (id:string)=>`/support/tickets/${id}` },
    HEALTH: { INDEX:"/health", UPTIME:"/health/uptime", API:"/health/api-endpoints", JOBS:"/health/jobs", INCIDENTS:"/health/incidents", TENANTS:"/health/tenants", SLOS:"/health/slos", PROVIDER_WEBHOOKS:"/health/provider-webhooks" },
    SCHOOL_MGT: {
      INDEX: "/school-management",
      CREATE: "/school-management/create",
      VIEW_PATH: "/school-management/:slug/view",
      VIEW: (slug: string) => `/school-management/${slug}/view`,
      EDIT_PATH: "/school-management/:slug/edit",
      EDIT: (slug: string) => `/school-management/${slug}/edit`,
      VIEW_BRANCH_PATH: "/school-management/:slug/branches/:code/view",
      VIEW_BRANCH: (slug: string, code: number) => `/school-management/${slug}/branches/${code}/view`,
      EDIT_BRANCH_PATH: "/school-management/:slug/branches/:code/edit",
      EDIT_BRANCH: (slug: string, code: number) => `/school-management/${slug}/branches/${code}/edit`,
      CREATE_BRANCH_PATH: "/school-management/:slug/branches/create",
      CREATE_BRANCH: (slug: string) => `/school-management/${slug}/branches/create`,
    },
    TEAM_MGT: {
      INDEX: "/users/cx",
      CX: "/users/cx",
      SCHOOL: "/users/schools",
      LEGACY: "/team-management",
      EDIT_PATH: "/users/:scope/:id/edit",
      EDIT: (id: string, scope: "cx" | "schools" = "cx") => `/users/${scope}/${id}/edit`,
      CREATE: "/users/cx/create",
      // View Details opens the staff profile (ORGANOGRAM.STAFF_BY_USER).
    },
    ROLES: {
      INDEX: "/roles",
      CREATE: "/roles/create",
      EDIT_PATH: "/roles/:id/edit",
      EDIT: (id: string) => `/roles/${id}/edit`,
      USER_ASSIGNMENTS: "/roles/user-assignments",
      CHANGE_REQUESTS: "/roles/change-requests",
      TRANSFER_SUPER_ADMIN: "/roles/transfer-super-admin",
      GROUPS: {
        INDEX: "/roles/permission-groups",
        CREATE: "/roles/permission-groups/create",
        EDIT_PATH: "/roles/permission-groups/:id/edit",
        EDIT: (id: string) => `/roles/permission-groups/${id}/edit`,
      },
    },
    PERMISSIONS: {
      INDEX: "/permissions",
      CREATE: "/permissions/create",
      EDIT_PATH: "/permissions/:key/edit",
      EDIT: (key: string) => `/permissions/${encodeURIComponent(key)}/edit`,
      MODULES: {
        INDEX: "/permissions/modules",
        CREATE: "/permissions/modules/create",
        EDIT_PATH: "/permissions/modules/:name/edit",
        EDIT: (name: string) => `/permissions/modules/${name}/edit`,
      },
      RESOURCES: {
        INDEX: "/permissions/resources",
        CREATE: "/permissions/resources/create",
        EDIT_PATH: "/permissions/resources/:id/edit",
        EDIT: (id: string) => `/permissions/resources/${id}/edit`,
      },
      ACTIONS: {
        INDEX: "/permissions/actions",
        CREATE: "/permissions/actions/create",
        EDIT_PATH: "/permissions/actions/:name/edit",
        EDIT: (name: string) => `/permissions/actions/${name}/edit`,
      },
      DEPENDENCIES: {
        INDEX: "/permissions/dependencies",
        CREATE: "/permissions/dependencies/create",
      },
    },
    DATA_IMPORTS: {
      BATCHES: {
        INDEX: "/data-imports/batches",
        NEW: "/data-imports/batches/new",
        VIEW_PATH: "/data-imports/batches/:id/view",
        VIEW: (id: string) => `/data-imports/batches/${id}/view`,
      },
      TEMPLATES: {
        INDEX: "/data-imports/templates",
        NEW: "/data-imports/templates/new",
        VIEW_PATH: "/data-imports/templates/:id/view",
        VIEW: (id: string | number) => `/data-imports/templates/${id}/view`,
        EDIT_PATH: "/data-imports/templates/:id/edit",
        EDIT: (id: string | number) => `/data-imports/templates/${id}/edit`,
      },
    },
    AUDIT: {
      DASHBOARD: "/audit",
      EVENTS: "/audit/events",
      EVENT_DETAIL_PATH: "/audit/events/:id",
      EVENT_DETAIL: (id: string) => `/audit/events/${id}`,
      ENTITY_TRAILS: "/audit/entity-trails",
      ENTITY_TRAIL_DETAIL_PATH: "/audit/entity-trails/:entity_type/:entity_id",
      ENTITY_TRAIL_DETAIL: (type: string, id: string) =>
        `/audit/entity-trails/${encodeURIComponent(type)}/${encodeURIComponent(id)}`,
      SESSIONS: "/audit/sessions",
      LOGIN_ATTEMPTS: "/audit/login-attempts",
      LOCKOUTS: "/audit/lockouts",
      PASSWORD_ACTIVITY: "/audit/password-activity",
      IMPERSONATIONS: "/audit/impersonations",
      EXPORTS: "/audit/exports",
      EXPORT_NEW: "/audit/exports/new",
      COMPLIANCE_RULES: "/audit/compliance-rules",
      COMPLIANCE_RULE_CREATE: "/audit/compliance-rules/create",
      COMPLIANCE_RULE_EDIT_PATH: "/audit/compliance-rules/:id/edit",
      COMPLIANCE_RULE_EDIT: (id: string) => `/audit/compliance-rules/${id}/edit`,
    },
    WORKFLOW: {
      APPROVALS: "/workflow/approvals",
      APPROVAL_DETAIL_PATH: "/workflow/approvals/:id",
      APPROVAL_DETAIL: (id: string) => `/workflow/approvals/${id}`,
      MY_SUBMISSIONS: "/workflow/my-submissions",
      SUBMISSION_DETAIL_PATH: "/workflow/my-submissions/:id",
      SUBMISSION_DETAIL: (id: string) => `/workflow/my-submissions/${id}`,
      INSTANCES: "/workflow/instances",
      INSTANCE_DETAIL_PATH: "/workflow/instances/:id",
      INSTANCE_DETAIL: (id: string) => `/workflow/instances/${id}`,
      TEAM_LOAD: "/workflow/team-load",
      DELEGATIONS: "/workflow/delegations",
      TEMPLATES: "/workflow/templates",
      TEMPLATE_NEW: "/workflow/templates/new",
      TEMPLATE_DETAIL_PATH: "/workflow/templates/:id",
      TEMPLATE_DETAIL: (id: string) => `/workflow/templates/${id}`,
      TEMPLATE_EDIT_PATH: "/workflow/templates/:id/edit",
      TEMPLATE_EDIT: (id: string) => `/workflow/templates/${id}/edit`,
    },
    ME_SECURITY: {
      OVERVIEW: "/me/security",
      SESSIONS: "/me/security/sessions",
      LOGIN_HISTORY: "/me/security/login-history",
      PASSWORD: "/me/security/password",
      ACTIVITY: "/me/security/activity",
      PRIVACY: "/me/security/privacy",
    },
    ME_PROFILE: {
      INDEX: "/me/profile",
    },
    // Code symbol stays TODO (maps to the vs_todo backend); the user-facing URL
    // and labels read "Tasks".
    TODO: {
      INDEX: "/tasks",
    },
    // Export menu - more entries will be appended as export features ship.
    // Overview and Exports arrive with the builder (slice 2).
    EXPORT: {
      QUEUES: "/export/queues",
      FILES: "/export/files",
      RUN_PATH: "/export/runs/:id",
      RUN: (id: string | number) => `/export/runs/${id}`,
      SAVED: "/export/saved",
      NEW: "/export/new",
      EDIT_PATH: "/export/:id/edit",
      EDIT: (id: string | number) => `/export/${id}/edit`,
    },
    ORGANOGRAM: {
      INDEX: "/organogram",
      MANAGE: "/organogram/manage",
      STAFF_CREATE: "/organogram/staff/create",
      STAFF_VIEW_PATH: "/organogram/staff/:id/view",
      STAFF_VIEW: (id: string | number) => `/organogram/staff/${id}/view`,
      // Profile looked up by the OWNING USER's id - Team Management's View
      // Details lands here (it knows user ids, not profile ids).
      STAFF_BY_USER_PATH: "/organogram/staff/by-user/:userId/view",
      STAFF_BY_USER: (userId: string | number) => `/organogram/staff/by-user/${userId}/view`,
      STAFF_EDIT_PATH: "/organogram/staff/:id/edit",
      STAFF_EDIT: (id: string | number) => `/organogram/staff/${id}/edit`,
    },
    // ── Finance & Operations: two separate consoles, each with its own
    // sub-navigation. Area index paths live here; detail routes are added per
    // build slice as their screens ship.
    FINANCE: {
      INDEX: "/finance",
      SETUP: "/finance/setup",
      LEDGER: "/finance/ledger",
      RECEIVABLES: "/finance/receivables",
      RECEIPTS_ALLOCATION: FINANCE_RECEIPTS_ALLOCATION,
      RECORD_PAYMENT: `${FINANCE_RECEIPTS_ALLOCATION}?action=new`,
      COLLECTIONS: "/finance/collections",
      PAYMENTS: "/finance/payments",
      BANKING: "/finance/banking",
      BANK_RECON: "/finance/bank-reconciliation",
      EXPENSES: "/finance/expenses",
      PAYROLL: "/finance/payroll",
      BUDGETS: "/finance/budgets",
      REPORTS: "/finance/reports",
      AUDIT: "/finance/audit",
      SETTINGS: "/finance/settings",
    },
    PROCUREMENT: {
      INDEX: "/procurement",
      VENDORS: "/procurement/vendors",
      REQUISITIONS: "/procurement/requisitions",
      PURCHASE_ORDERS: "/procurement/purchase-orders",
      GOODS_RECEIPTS: "/procurement/goods-receipts",
      VENDOR_INVOICES: "/procurement/vendor-invoices",
      VENDOR_PAYMENTS: "/procurement/vendor-payments",
      APPROVALS: "/procurement/approvals",
      SOURCING: "/procurement/sourcing",
      CONTRACTS: "/procurement/contracts",
      INVENTORY: "/procurement/inventory",
      ANALYTICS: "/procurement/analytics",
      SETTINGS: "/procurement/settings",
    },
  },
};
