export const routesPath = {
  AUTH: {
    LOGIN: "/login",
    SIGNUP: "/signup",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password/:activation_key",
    RESET_PASSWORD_LINK: (key: string) => `/reset-password/${key}`,
    ACTIVATE: "/activate/:activation_key",
    ACTIVATE_LINK: (key: string) => `/activate/${key}`,
    SPECIAL_LOGIN: "/:email/login",
    SPECIAL_LOGIN_LINK: (email: string) => `/${encodeURIComponent(email)}/login`,
  },
  PROTECTED: {
    OVERVIEW: { INDEX: "/overview" },
    SCHOOL_MGT: {
      INDEX: "/school-management",
      CREATE: "/school-management/create",
      VIEW_PATH: "/school-management/:slug/view",
      VIEW: (slug: string) => `/school-management/${slug}/view`,
      EDIT_PATH: "/school-management/:slug/edit",
      EDIT: (slug: string) => `/school-management/${slug}/edit`,
      VIEW_BRANCH_PATH: "/school-management/:slug/branches/:code/view",
      VIEW_BRANCH: (slug: string, code: number) => `/school-management/${slug}/branches/${code}/view`,
      EDIT_BRANCH_PATH: "/school-management/:slug/branches/:code/edit",
      EDIT_BRANCH: (slug: string, code: number) => `/school-management/${slug}/branches/${code}/edit`,
    },
    TEAM_MGT: {
      INDEX: '/team-management',
      EDIT_PATH: "/team-management/:id/edit",
      EDIT: (id:string) => `/team-management/${id}/edit`,
      CREATE: "/team-management/create",
      VIEW_PATH: "/team-management/:id/view",
      VIEW: (id: string) => `/team-management/${id}/view`,
    },
    ROLES: {
      INDEX: "/roles",
      CREATE: "/roles/create",
      EDIT_PATH: "/roles/:id/edit",
      EDIT: (id: string) => `/roles/${id}/edit`,
      USER_ASSIGNMENTS: "/roles/user-assignments",
      CHANGE_REQUESTS: "/roles/change-requests",
      GROUPS: {
        INDEX: "/roles/permission-groups",
        CREATE: "/roles/permission-groups/create",
        EDIT_PATH: "/roles/permission-groups/:id/edit",
        EDIT: (id: string) => `/roles/permission-groups/${id}/edit`,
      },
    },
    PERMISSIONS: {
      INDEX: "/permissions",
      CREATE: "/permissions/create",
      EDIT_PATH: "/permissions/:key/edit",
      EDIT: (key: string) => `/permissions/${encodeURIComponent(key)}/edit`,
      MODULES: {
        INDEX: "/permissions/modules",
        CREATE: "/permissions/modules/create",
        EDIT_PATH: "/permissions/modules/:name/edit",
        EDIT: (name: string) => `/permissions/modules/${name}/edit`,
      },
      RESOURCES: {
        INDEX: "/permissions/resources",
        CREATE: "/permissions/resources/create",
        EDIT_PATH: "/permissions/resources/:id/edit",
        EDIT: (id: string) => `/permissions/resources/${id}/edit`,
      },
      ACTIONS: {
        INDEX: "/permissions/actions",
        CREATE: "/permissions/actions/create",
        EDIT_PATH: "/permissions/actions/:name/edit",
        EDIT: (name: string) => `/permissions/actions/${name}/edit`,
      },
      DEPENDENCIES: { INDEX: "/permissions/dependencies" },
    },
    DATA_IMPORTS: {
      BATCHES: {
        INDEX: "/data-imports/batches",
        VIEW_PATH: "/data-imports/batches/:id/view",
        VIEW: (id: string) => `/data-imports/batches/${id}/view`,
      },
      TEMPLATES: {
        INDEX: "/data-imports/templates",
      },
      TEMPLATE_COLUMNS: {
        INDEX: "/data-imports/template-columns",
      },
    },
  },
};
