import { P } from "@/permissions";
import { routesPath } from "@/routes/routes-path";

import type { GuideRecord } from "./types";

const R = routesPath.PROTECTED;
const REVIEWED_AT = "2026-08-13";
const OWNER = "Console product team";

export const GUIDE_REGISTRY = [
  {
    id: "getting-started.console-basics",
    slug: "get-started-with-console",
    title: "Get started with Console",
    summary: "Learn the dashboard, navigation, workspace search, notifications, and support entry points.",
    category: "getting-started",
    tags: ["dashboard", "navigation", "search", "support"],
    aliases: ["console tour", "how console works", "new user"],
    audiences: ["all-users"],
    routes: [R.OVERVIEW.INDEX],
    actionIds: ["view-home", "view-notifications", "view-support"],
    access: { mode: "authenticated", permissions: [] },
    owner: OWNER,
    reviewedAt: REVIEWED_AT,
    risk: "low",
    featured: true,
    status: "draft",
  },
  {
    id: "schools.create-and-configure",
    slug: "create-and-configure-a-school",
    title: "Create and configure a school",
    summary: "Register a school, choose its package, add its first branch, and confirm its setup.",
    category: "schools-and-users",
    tags: ["school", "branch", "onboarding", "package"],
    aliases: ["onboard school", "register school", "school setup"],
    audiences: ["platform-administrator"],
    routes: [R.SCHOOL_MGT.INDEX, R.SCHOOL_MGT.CREATE],
    actionIds: ["view-schools", "create-school"],
    access: { mode: "any", permissions: [P.ONBOARD_SCHOOL] },
    walkthroughId: "walkthrough.schools.create-and-configure",
    owner: OWNER,
    reviewedAt: REVIEWED_AT,
    risk: "high",
    featured: true,
    status: "draft",
  },
  {
    id: "roles.create-and-assign",
    slug: "create-a-role-and-assign-it",
    title: "Create a role and assign it",
    summary: "Choose permissions deliberately, create a role, and assign it to the right user.",
    category: "roles-and-permissions",
    tags: ["roles", "permissions", "assignments", "access"],
    aliases: ["new role", "give user access", "assign permissions"],
    audiences: ["platform-administrator"],
    routes: [R.ROLES.INDEX, R.ROLES.CREATE, R.ROLES.USER_ASSIGNMENTS],
    actionIds: ["view-roles", "create-role", "view-role-assignments"],
    access: { mode: "all", permissions: [P.VIEW_ROLES, P.DEFINE_ROLE, P.ASSIGN_ROLE] },
    walkthroughId: "walkthrough.roles.create-and-assign",
    owner: OWNER,
    reviewedAt: REVIEWED_AT,
    risk: "high",
    featured: true,
    status: "draft",
  },
  {
    id: "organogram.build-structure",
    slug: "build-the-organogram",
    title: "Build the organogram",
    summary: "Create departments, positions, reporting lines, matrix relationships, and staff profiles.",
    category: "organogram-and-tasks",
    tags: ["organogram", "departments", "positions", "staff"],
    aliases: ["org chart", "reporting lines", "company structure"],
    audiences: ["platform-administrator"],
    routes: [R.ORGANOGRAM.INDEX, R.ORGANOGRAM.MANAGE],
    actionIds: ["view-org-chart", "manage-organogram"],
    access: { mode: "any", permissions: [P.MANAGE_ORGANOGRAM] },
    owner: OWNER,
    reviewedAt: REVIEWED_AT,
    risk: "medium",
    status: "draft",
  },
  {
    id: "workflow.build-template",
    slug: "build-an-approval-workflow-template",
    title: "Build an approval workflow template",
    summary: "Configure stages, conditions, approver sources, validation, and publishing safely.",
    category: "approvals-and-workflow",
    tags: ["workflow", "approval", "template", "approver"],
    aliases: ["new workflow", "approval stages", "approval template"],
    audiences: ["platform-administrator", "approver"],
    routes: [R.WORKFLOW.TEMPLATES, R.WORKFLOW.TEMPLATE_NEW],
    actionIds: ["view-workflow-templates", "create-workflow-template"],
    access: { mode: "all", permissions: [P.VIEW_WORKFLOW_TEMPLATES, P.MANAGE_WORKFLOW_TEMPLATES] },
    walkthroughId: "walkthrough.workflow.build-template",
    owner: OWNER,
    reviewedAt: REVIEWED_AT,
    risk: "high",
    featured: true,
    status: "draft",
  },
  {
    id: "finance.create-and-post-journal",
    slug: "create-and-post-a-journal",
    title: "Create and post a journal",
    summary: "Build balanced journal lines, choose an open period, submit, approve, and post as permitted.",
    category: "finance-and-payments",
    tags: ["finance", "journal", "ledger", "posting"],
    aliases: ["manual journal", "journal entry", "general ledger entry"],
    audiences: ["finance-officer", "approver"],
    routes: [R.FINANCE.LEDGER],
    actionIds: ["view-general-ledger", "new-journal-entry"],
    access: { mode: "any", permissions: [P.FIN_SUBMIT_JOURNAL, P.FIN_POST_JOURNAL] },
    walkthroughId: "walkthrough.finance.create-and-post-journal",
    owner: OWNER,
    reviewedAt: REVIEWED_AT,
    risk: "high",
    featured: true,
    status: "draft",
  },
  {
    id: "procurement.complete-procure-to-pay",
    slug: "complete-procure-to-pay",
    title: "Complete the procure-to-pay cycle",
    summary: "Move from requisition through purchase order, receipt, vendor invoice, and payment.",
    category: "procurement-and-inventory",
    tags: ["procurement", "requisition", "purchase order", "vendor payment"],
    aliases: ["p2p", "procure to pay", "purchase lifecycle"],
    audiences: ["procurement-officer", "approver", "finance-officer"],
    routes: [R.PROCUREMENT.REQUISITIONS, R.PROCUREMENT.PURCHASE_ORDERS, R.PROCUREMENT.GOODS_RECEIPTS, R.PROCUREMENT.VENDOR_INVOICES, R.PROCUREMENT.VENDOR_PAYMENTS],
    actionIds: ["create-requisition", "create-purchase-order", "post-goods-receipt", "create-vendor-invoice", "new-vendor-payment"],
    access: { mode: "any", permissions: [P.PROC_CREATE_REQUISITION, P.PROC_CREATE_PURCHASE_ORDER, P.PROC_CREATE_GOODS_RECEIPT, P.PROC_CREATE_VENDOR_INVOICE, P.PROC_CREATE_VENDOR_PAYMENT] },
    walkthroughId: "walkthrough.procurement.complete-procure-to-pay",
    owner: OWNER,
    reviewedAt: REVIEWED_AT,
    risk: "high",
    featured: true,
    status: "draft",
  },
  {
    id: "data.import-batch",
    slug: "upload-and-resolve-an-import-batch",
    title: "Upload and resolve an import batch",
    summary: "Prepare a file, validate its rows, resolve issues, and execute the import safely.",
    category: "data-imports-and-exports",
    tags: ["import", "spreadsheet", "validation", "batch"],
    aliases: ["bulk upload", "import data", "fix import errors"],
    audiences: ["platform-administrator", "support-and-operations"],
    routes: [R.DATA_IMPORTS.BATCHES.INDEX, R.DATA_IMPORTS.BATCHES.NEW, R.DATA_IMPORTS.BATCHES.VIEW_PATH],
    actionIds: ["view-import-batches", "upload-import-batch"],
    access: { mode: "all", permissions: [P.VIEW_IMPORT_BATCHES, P.UPLOAD_IMPORT_BATCH] },
    walkthroughId: "walkthrough.data.import-batch",
    owner: OWNER,
    reviewedAt: REVIEWED_AT,
    risk: "high",
    featured: true,
    status: "draft",
  },
  {
    id: "audit.investigate-event",
    slug: "investigate-an-audit-event",
    title: "Investigate an audit event",
    summary: "Filter events, inspect context, follow the entity trail, and preserve evidence.",
    category: "audit-and-security",
    tags: ["audit", "events", "entity trail", "investigation"],
    aliases: ["who changed this", "security event", "audit trail"],
    audiences: ["platform-administrator", "support-and-operations"],
    routes: [R.AUDIT.DASHBOARD, R.AUDIT.EVENTS, R.AUDIT.ENTITY_TRAILS],
    actionIds: ["view-security-dashboard", "view-audit-events", "view-entity-trails"],
    access: { mode: "any", permissions: [P.VIEW_AUDIT] },
    walkthroughId: "walkthrough.audit.investigate-event",
    owner: OWNER,
    reviewedAt: REVIEWED_AT,
    risk: "high",
    status: "draft",
  },
  {
    id: "platform.investigate-health",
    slug: "investigate-platform-health",
    title: "Investigate platform health",
    summary: "Use health signals to distinguish user, tenant, provider, job, and platform problems.",
    category: "platform-health-and-settings",
    tags: ["health", "incident", "job", "tenant", "provider"],
    aliases: ["system health", "platform outage", "failed job"],
    audiences: ["support-and-operations"],
    routes: [R.HEALTH.INDEX, R.HEALTH.JOBS, R.HEALTH.INCIDENTS, R.HEALTH.TENANTS],
    actionIds: ["view-system-health", "view-jobs-queues", "view-incidents", "view-tenant-health"],
    access: { mode: "any", permissions: [P.VIEW_HEALTH] },
    owner: OWNER,
    reviewedAt: REVIEWED_AT,
    risk: "high",
    status: "draft",
  },
  {
    id: "account.secure-account",
    slug: "secure-your-console-account",
    title: "Secure your Console account",
    summary: "Change your password, review sign-ins, and end sessions you do not recognize.",
    category: "account-and-personal-security",
    tags: ["account", "password", "session", "login history"],
    aliases: ["account security", "sign out another device", "change password"],
    audiences: ["all-users"],
    routes: [R.ME_SECURITY.OVERVIEW, R.ME_SECURITY.PASSWORD, R.ME_SECURITY.SESSIONS, R.ME_SECURITY.LOGIN_HISTORY],
    actionIds: ["view-my-security", "change-my-password"],
    access: { mode: "authenticated", permissions: [] },
    owner: OWNER,
    reviewedAt: REVIEWED_AT,
    risk: "medium",
    status: "draft",
  },
  {
    id: "troubleshooting.permission-denied",
    slug: "resolve-permission-denied-or-missing-navigation",
    title: "Resolve permission denied or missing navigation",
    summary: "Check account context, role assignment, permissions, and escalation details.",
    category: "troubleshooting",
    tags: ["permission denied", "forbidden", "missing menu", "access"],
    aliases: ["403", "cannot see page", "menu missing", "not allowed"],
    audiences: ["all-users", "platform-administrator", "support-and-operations"],
    routes: [R.SUPPORT.INDEX],
    actionIds: ["view-support", "raise-support-ticket"],
    access: { mode: "authenticated", permissions: [] },
    owner: OWNER,
    reviewedAt: REVIEWED_AT,
    risk: "medium",
    status: "draft",
  },
] as const satisfies readonly GuideRecord[];
