import { P } from "@/permissions";
import { routesPath } from "@/routes/routes-path";

import type { GuideRecord } from "./types";

const A = routesPath.AUTH;
const R = routesPath.PROTECTED;
const REVIEWED_AT = "2026-08-13";
const C4_REVIEWED_AT = "2026-08-14";
const C5_REVIEWED_AT = "2026-08-14";
const DOCS_REVIEWED_AT = "2026-08-15";
const GUIDE_EXPERIENCE_REVIEWED_AT = "2026-08-17";
const C6A_REVIEWED_AT = "2026-08-21";
const C6B_REVIEWED_AT = "2026-08-21";
const C6C_REVIEWED_AT = "2026-08-21";
const C7A_REVIEWED_AT = "2026-08-21";
const OWNER = "Console product team";

export const GUIDE_REGISTRY = [
  {
    id: "getting-started.console-basics",
    slug: "get-started-with-console",
    title: "Get started with Console",
    summary: "Learn the dashboard, navigation, workspace search, notifications, and support entry points.",
    category: "getting-started",
    tags: ["dashboard", "navigation", "search", "support", "today's focus"],
    aliases: [
      "console tour", "how console works", "new user",
      "todays focus", "action needed", "what needs my attention",
      "dismiss notice", "tickets assigned to me",
    ],
    audiences: ["all-users"],
    routes: [R.OVERVIEW.INDEX],
    actionIds: ["view-home", "view-notifications", "view-support"],
    access: { mode: "authenticated", permissions: [] },
    primaryRoute: R.OVERVIEW.INDEX,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "find-your-way-around", title: "Find your way around" },
      { id: "search-and-quick-actions", title: "Search and quick actions" },
      { id: "understand-your-access", title: "Understand your access" },
      { id: "todays-focus", title: "Today's focus" },
      { id: "attention-and-notifications", title: "Notifications and recent work" },
      { id: "get-help", title: "Get help" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["getting-started.activate-and-sign-in", "getting-started.reset-password", "account.secure-account", "troubleshooting.permission-denied"],
    walkthroughId: "walkthrough.getting-started.console-basics",
    estimatedMinutes: 6,
    owner: OWNER,
    reviewedAt: GUIDE_EXPERIENCE_REVIEWED_AT,
    risk: "low",
    featured: true,
    status: "published",
    article: () => import("./content/getting-started/console-basics"),
  },
  {
    id: "getting-started.activate-and-sign-in",
    slug: "activate-your-account-and-sign-in",
    title: "Activate your account and sign in",
    summary: "Use your invitation safely, create your first password, and enter Console for the first time.",
    category: "getting-started",
    tags: ["activation", "invitation", "login", "password", "account access"],
    aliases: ["activate account", "accept invite", "first login", "sign in", "invite expired"],
    audiences: ["all-users"],
    routes: [A.ACTIVATE, A.LOGIN],
    access: { mode: "authenticated", permissions: [] },
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "activate-your-account", title: "Activate your account" },
      { id: "sign-in", title: "Sign in" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["getting-started.console-basics", "getting-started.reset-password", "account.secure-account"],
    estimatedMinutes: 5,
    owner: OWNER,
    reviewedAt: REVIEWED_AT,
    risk: "medium",
    featured: true,
    status: "published",
    article: () => import("./content/getting-started/activate-and-sign-in"),
  },
  {
    id: "getting-started.reset-password",
    slug: "reset-a-forgotten-password",
    title: "Reset a forgotten password",
    summary: "Request a reset link, choose a valid new password, and recover safely from an expired link.",
    category: "getting-started",
    tags: ["forgot password", "password reset", "login", "email", "account recovery"],
    aliases: ["cannot login", "forgot my password", "reset link expired", "recover account"],
    audiences: ["all-users"],
    routes: [A.FORGOT_PASSWORD, A.RESET_PASSWORD, A.LOGIN],
    access: { mode: "authenticated", permissions: [] },
    primaryRoute: A.FORGOT_PASSWORD,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "request-a-reset-link", title: "Request a reset link" },
      { id: "set-a-new-password", title: "Set a new password" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["getting-started.activate-and-sign-in", "getting-started.console-basics", "account.secure-account"],
    estimatedMinutes: 4,
    owner: OWNER,
    reviewedAt: REVIEWED_AT,
    risk: "medium",
    featured: true,
    status: "published",
    article: () => import("./content/getting-started/reset-password"),
  },
  {
    id: "schools.create-and-configure",
    slug: "create-and-configure-a-school",
    title: "Create and configure a school",
    summary: "Register a school, choose its package, add its first branch, and confirm its setup.",
    category: "schools-and-users",
    tags: ["school", "branch", "administrator", "onboarding", "package", "modules", "capacity"],
    aliases: ["onboard school", "register school", "school setup", "add new school", "school admin"],
    audiences: ["platform-administrator"],
    routes: [R.SCHOOL_MGT.INDEX, R.SCHOOL_MGT.CREATE],
    actionIds: ["view-schools", "create-school", "view-go-live-requests"],
    access: { mode: "any", permissions: [P.ONBOARD_SCHOOL] },
    primaryRoute: R.SCHOOL_MGT.CREATE,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "add-school-details", title: "Add school details" },
      { id: "add-branches", title: "Add branches" },
      { id: "add-school-admin", title: "Add the school administrator" },
      { id: "configure-package", title: "Configure the package" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["schools.manage-schools-and-branches", "schools.invite-and-manage-users"],
    walkthroughId: "walkthrough.schools.create-and-configure",
    estimatedMinutes: 10,
    owner: OWNER,
    reviewedAt: C5_REVIEWED_AT,
    risk: "high",
    featured: true,
    status: "published",
    article: () => import("./content/schools-and-users/create-and-configure-school"),
  },
  {
    id: "schools.manage-schools-and-branches",
    slug: "manage-schools-and-branches",
    title: "Manage schools and branches",
    summary: "Find a school, review its setup, and create, view, or edit its branches.",
    category: "schools-and-users",
    tags: ["school list", "school details", "branches", "search", "sort", "status"],
    aliases: ["find school", "edit school", "add branch", "view branch", "school onboarding list"],
    audiences: ["platform-administrator", "school-administrator", "support-and-operations"],
    routes: [R.SCHOOL_MGT.INDEX, R.SCHOOL_MGT.GO_LIVE, R.SCHOOL_MGT.VIEW_PATH, R.SCHOOL_MGT.EDIT_PATH, R.SCHOOL_MGT.CREATE_BRANCH_PATH, R.SCHOOL_MGT.VIEW_BRANCH_PATH, R.SCHOOL_MGT.EDIT_BRANCH_PATH],
    actionIds: ["view-schools"],
    access: { mode: "any", permissions: [P.BROWSE_SCHOOLS, P.BROWSE_BRANCHES, P.ADD_BRANCH, P.MODIFY_SCHOOL, P.MODIFY_BRANCH] },
    primaryRoute: R.SCHOOL_MGT.INDEX,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "find-a-school", title: "Find a school" },
      { id: "review-and-edit", title: "Review and edit a school" },
      { id: "decide-go-live", title: "Decide a go-live request" },
      { id: "manage-branches", title: "Manage branches" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["schools.create-and-configure", "schools.invite-and-manage-users"],
    estimatedMinutes: 7,
    owner: OWNER,
    reviewedAt: REVIEWED_AT,
    risk: "medium",
    status: "published",
    article: () => import("./content/schools-and-users/manage-schools-and-branches"),
  },
  {
    id: "schools.invite-and-manage-users",
    slug: "invite-and-manage-cx-or-school-users",
    title: "Invite and manage CX or school users",
    summary: "Find user accounts, submit a CX user invitation, track its status, and resolve common access problems.",
    category: "schools-and-users",
    tags: ["users", "cx users", "school users", "invitation", "approval", "staff profile", "access"],
    aliases: ["add team member", "invite cx user", "edit user", "unlock user", "suspend user", "user invite status"],
    audiences: ["platform-administrator", "support-and-operations"],
    routes: [R.TEAM_MGT.CX, R.TEAM_MGT.SCHOOL, R.TEAM_MGT.CREATE, R.TEAM_MGT.EDIT_PATH],
    actionIds: ["view-cx-users", "view-school-users", "invite-cx-user"],
    access: { mode: "any", permissions: [P.ACCESS_TEAM_PANEL, P.INVITE_TEAM_MEMBER, P.MODIFY_TEAM_MEMBER] },
    primaryRoute: R.TEAM_MGT.CX,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "browse-users", title: "Browse users" },
      { id: "invite-a-cx-user", title: "Invite a CX user" },
      { id: "track-and-manage-access", title: "Track and manage access" },
      { id: "open-a-staff-profile", title: "Open a staff profile" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["schools.create-and-configure", "schools.manage-schools-and-branches"],
    estimatedMinutes: 8,
    owner: OWNER,
    reviewedAt: REVIEWED_AT,
    risk: "medium",
    status: "published",
    article: () => import("./content/schools-and-users/invite-and-manage-users"),
  },
  {
    id: "roles.create-and-assign",
    slug: "create-a-role-and-assign-it",
    title: "Create a role and assign it",
    summary: "Choose permissions deliberately, create a role, and assign it to the right user.",
    category: "roles-and-permissions",
    tags: ["roles", "permissions", "permission groups", "assignments", "access", "revoke"],
    aliases: ["new role", "give user access", "assign permissions", "change role", "revoke role"],
    audiences: ["platform-administrator"],
    routes: [R.ROLES.INDEX, R.ROLES.CREATE, R.ROLES.USER_ASSIGNMENTS],
    actionIds: ["view-roles", "create-role", "view-role-assignments"],
    access: { mode: "all", permissions: [P.VIEW_ROLES, P.DEFINE_ROLE, P.ASSIGN_ROLE] },
    primaryRoute: R.ROLES.CREATE,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "understand-role-access", title: "Understand role access" },
      { id: "create-the-role", title: "Create the role" },
      { id: "assign-or-change-a-role", title: "Assign or change a role" },
      { id: "revoke-an-assignment", title: "Revoke an assignment" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["roles.review-changes-and-transfer-super-admin", "roles.maintain-permission-catalogue", "troubleshooting.permission-denied"],
    walkthroughId: "walkthrough.roles.create-and-assign",
    estimatedMinutes: 10,
    owner: OWNER,
    reviewedAt: REVIEWED_AT,
    risk: "high",
    featured: true,
    status: "published",
    article: () => import("./content/roles-and-permissions/create-and-assign-role"),
  },
  {
    id: "roles.review-changes-and-transfer-super-admin",
    slug: "review-role-changes-and-transfer-super-admin",
    title: "Review role changes and transfer super admin",
    summary: "Propose and review permission deltas, then use the protected ownership-transfer path when required.",
    category: "roles-and-permissions",
    tags: ["role change request", "approval", "permission delta", "super admin", "ownership", "review"],
    aliases: ["approve role change", "deny role change", "transfer super admin", "change permissions request", "apply failed"],
    audiences: ["platform-administrator", "approver"],
    routes: [R.ROLES.CHANGE_REQUESTS, R.ROLES.TRANSFER_SUPER_ADMIN],
    actionIds: ["view-role-change-requests", "transfer-super-admin"],
    access: { mode: "any", permissions: [P.MODIFY_ROLE, P.TRANSFER_SUPER_ADMIN] },
    primaryRoute: R.ROLES.CHANGE_REQUESTS,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "submit-a-change-request", title: "Submit a change request" },
      { id: "review-and-decide", title: "Review and decide" },
      { id: "understand-request-status", title: "Understand request status" },
      { id: "transfer-super-admin", title: "Transfer super admin" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["roles.create-and-assign", "roles.maintain-permission-catalogue", "troubleshooting.permission-denied"],
    walkthroughId: "walkthrough.roles.transfer-super-admin",
    estimatedMinutes: 9,
    owner: OWNER,
    reviewedAt: REVIEWED_AT,
    risk: "high",
    featured: true,
    status: "published",
    article: () => import("./content/roles-and-permissions/review-changes-and-transfer-super-admin"),
  },
  {
    id: "roles.maintain-permission-catalogue",
    slug: "maintain-the-permission-catalogue-and-groups",
    title: "Maintain the permission catalogue and groups",
    summary: "Manage permission modules, resources, actions, keys, dependencies, and reusable groups safely.",
    category: "roles-and-permissions",
    tags: ["permission registry", "module", "resource", "action", "dependency", "permission group", "sensitivity"],
    aliases: ["create permission", "add dependency", "permission catalogue", "new permission group", "restricted permission"],
    audiences: ["platform-administrator"],
    routes: [R.PERMISSIONS.INDEX, R.PERMISSIONS.CREATE, R.PERMISSIONS.EDIT_PATH, R.PERMISSIONS.MODULES.INDEX, R.PERMISSIONS.MODULES.CREATE, R.PERMISSIONS.MODULES.EDIT_PATH, R.PERMISSIONS.RESOURCES.INDEX, R.PERMISSIONS.RESOURCES.CREATE, R.PERMISSIONS.RESOURCES.EDIT_PATH, R.PERMISSIONS.ACTIONS.INDEX, R.PERMISSIONS.ACTIONS.CREATE, R.PERMISSIONS.ACTIONS.EDIT_PATH, R.PERMISSIONS.DEPENDENCIES.INDEX, R.PERMISSIONS.DEPENDENCIES.CREATE, R.ROLES.GROUPS.INDEX, R.ROLES.GROUPS.CREATE, R.ROLES.GROUPS.EDIT_PATH],
    actionIds: ["view-permissions", "create-permission", "view-permission-modules", "view-permission-resources", "view-permission-actions", "view-permission-dependencies", "view-permission-groups", "create-permission-group"],
    access: { mode: "any", permissions: [P.VIEW_PERMISSIONS, P.CREATE_PERMISSION, P.MODIFY_PERMISSION, P.MANAGE_PERMISSIONS] },
    primaryRoute: R.PERMISSIONS.INDEX,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "understand-the-vocabulary", title: "Understand the vocabulary" },
      { id: "maintain-catalogue-parts", title: "Maintain catalogue parts" },
      { id: "create-a-permission", title: "Create a permission" },
      { id: "manage-dependencies", title: "Manage dependencies" },
      { id: "manage-permission-groups", title: "Manage permission groups" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["roles.create-and-assign", "roles.review-changes-and-transfer-super-admin", "troubleshooting.permission-denied"],
    walkthroughId: "walkthrough.roles.maintain-permission-catalogue",
    estimatedMinutes: 12,
    owner: OWNER,
    reviewedAt: REVIEWED_AT,
    risk: "high",
    featured: true,
    status: "published",
    article: () => import("./content/roles-and-permissions/maintain-permission-catalogue"),
  },
  {
    id: "organogram.build-structure",
    slug: "build-the-organogram",
    title: "Build the organogram",
    summary: "Create org units, positions, solid reporting lines, and matrix relationships in the right order.",
    category: "organogram-and-tasks",
    tags: ["organogram", "division", "department", "team", "position", "seat", "solid line", "matrix line"],
    aliases: ["org chart", "reporting lines", "company structure", "new org node", "new position", "dotted line"],
    audiences: ["platform-administrator"],
    routes: [R.ORGANOGRAM.INDEX, R.ORGANOGRAM.MANAGE],
    actionIds: ["view-org-chart", "manage-organogram"],
    access: { mode: "any", permissions: [P.MANAGE_ORGANOGRAM] },
    primaryRoute: R.ORGANOGRAM.MANAGE,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "understand-the-structure", title: "Understand the structure" },
      { id: "create-org-units", title: "Create org units" },
      { id: "create-positions", title: "Create positions and reporting lines" },
      { id: "add-matrix-lines", title: "Add matrix lines" },
      { id: "review-the-chart", title: "Review the chart" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["organogram.maintain-staff-profiles", "tasks.create-and-complete"],
    walkthroughId: "walkthrough.organogram.build-structure",
    estimatedMinutes: 11,
    owner: OWNER,
    reviewedAt: C4_REVIEWED_AT,
    risk: "medium",
    featured: true,
    status: "published",
    article: () => import("./content/organogram-and-tasks/build-organogram"),
  },
  {
    id: "organogram.maintain-staff-profiles",
    slug: "maintain-staff-profiles-and-seat-assignments",
    title: "Maintain staff profiles and seat assignments",
    summary: "Create or update a CX staff profile, assign its primary seat, and protect sensitive payroll details.",
    category: "organogram-and-tasks",
    tags: ["staff profile", "employee ID", "position", "seat assignment", "employment", "payroll", "position history"],
    aliases: ["create staff profile", "edit employee profile", "assign seat", "change position", "bank details", "HR profile"],
    audiences: ["platform-administrator", "support-and-operations"],
    routes: [R.ORGANOGRAM.STAFF_CREATE, R.ORGANOGRAM.STAFF_VIEW_PATH, R.ORGANOGRAM.STAFF_BY_USER_PATH, R.ORGANOGRAM.STAFF_EDIT_PATH],
    access: { mode: "any", permissions: [P.VIEW_STAFF_PROFILE, P.CREATE_STAFF_PROFILE, P.MODIFY_STAFF_PROFILE] },
    primaryRoute: R.ORGANOGRAM.STAFF_CREATE,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "understand-profile-access", title: "Understand profile access" },
      { id: "create-a-profile", title: "Create a staff profile" },
      { id: "update-a-profile", title: "Update a profile and seat" },
      { id: "protect-payroll-details", title: "Protect payroll details" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["organogram.build-structure", "schools.invite-and-manage-users", "tasks.create-and-complete"],
    walkthroughId: "walkthrough.organogram.maintain-staff-profiles",
    estimatedMinutes: 9,
    owner: OWNER,
    reviewedAt: C4_REVIEWED_AT,
    risk: "medium",
    status: "published",
    article: () => import("./content/organogram-and-tasks/maintain-staff-profiles"),
  },
  {
    id: "tasks.create-and-complete",
    slug: "create-assign-and-complete-tasks",
    title: "Create, assign, and complete tasks",
    summary: "Record a personal commitment, assign work down your reporting line, and track completion safely.",
    category: "organogram-and-tasks",
    tags: ["tasks", "KPI", "commitment", "deadline", "priority", "team tasks", "overdue", "completion"],
    aliases: ["add task", "assign task", "my tasks", "team tasks", "mark task done", "undo completion"],
    audiences: ["all-users"],
    routes: [R.TODO.INDEX],
    actionIds: ["view-tasks"],
    access: { mode: "authenticated", permissions: [] },
    primaryRoute: R.TODO.INDEX,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "understand-task-views", title: "Understand task views" },
      { id: "add-your-own-task", title: "Add your own task" },
      { id: "assign-a-task", title: "Assign a task" },
      { id: "track-and-complete", title: "Track and complete work" },
      { id: "edit-or-delete", title: "Edit or delete a task" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["organogram.build-structure", "organogram.maintain-staff-profiles"],
    estimatedMinutes: 7,
    owner: OWNER,
    reviewedAt: C4_REVIEWED_AT,
    risk: "low",
    featured: true,
    status: "published",
    article: () => import("./content/organogram-and-tasks/create-and-complete-tasks"),
  },
  {
    id: "workflow.review-and-act",
    slug: "review-and-act-on-an-approval",
    title: "Review and act on an approval",
    summary: "Find an approval, inspect its evidence and active stage, then approve, reject, or return it safely.",
    category: "approvals-and-workflow",
    tags: ["approval", "pending approvals", "approve", "reject", "return", "quorum", "workflow status"],
    aliases: ["my approval queue", "approve request", "reject request", "send back request", "approval unavailable", "stalled approval"],
    audiences: ["approver", "all-users"],
    routes: [R.WORKFLOW.APPROVALS, R.WORKFLOW.APPROVAL_DETAIL_PATH],
    actionIds: ["view-approvals"],
    access: { mode: "authenticated", permissions: [] },
    primaryRoute: R.WORKFLOW.APPROVALS,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "find-an-approval", title: "Find an approval" },
      { id: "review-the-request", title: "Review the request" },
      { id: "choose-a-decision", title: "Choose a decision" },
      { id: "understand-the-result", title: "Understand the result" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["workflow.delegate-and-track", "workflow.build-template", "troubleshooting.permission-denied"],
    walkthroughId: "walkthrough.workflow.review-and-act",
    estimatedMinutes: 7,
    owner: OWNER,
    reviewedAt: C5_REVIEWED_AT,
    risk: "high",
    featured: true,
    status: "published",
    article: () => import("./content/approvals-and-workflow/review-and-act-on-approval"),
  },
  {
    id: "workflow.delegate-and-track",
    slug: "delegate-and-track-approvals",
    title: "Delegate and track approvals",
    summary: "Track personal submissions, hand off approval coverage, and diagnose workflow status and load.",
    category: "approvals-and-workflow",
    tags: ["delegation", "my submissions", "workflow instances", "team load", "withdraw", "resubmit", "revoke"],
    aliases: ["out of office approver", "delegate approval", "track request", "returned submission", "all instances", "workflow load"],
    audiences: ["approver", "platform-administrator", "support-and-operations"],
    routes: [R.WORKFLOW.MY_SUBMISSIONS, R.WORKFLOW.SUBMISSION_DETAIL_PATH, R.WORKFLOW.DELEGATIONS, R.WORKFLOW.INSTANCES, R.WORKFLOW.INSTANCE_DETAIL_PATH, R.WORKFLOW.TEAM_LOAD],
    actionIds: ["view-my-submissions", "view-delegations", "view-workflow-instances", "view-team-load"],
    access: { mode: "authenticated", permissions: [] },
    primaryRoute: R.WORKFLOW.DELEGATIONS,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "track-a-submission", title: "Track a personal submission" },
      { id: "create-a-delegation", title: "Create a delegation" },
      { id: "monitor-workflow-load", title: "Monitor workflow instances and team load" },
      { id: "diagnose-workflow-status", title: "Diagnose workflow status" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["workflow.review-and-act", "workflow.build-template", "troubleshooting.permission-denied"],
    walkthroughId: "walkthrough.workflow.delegate-and-track",
    estimatedMinutes: 9,
    owner: OWNER,
    reviewedAt: C5_REVIEWED_AT,
    risk: "high",
    featured: true,
    status: "published",
    article: () => import("./content/approvals-and-workflow/delegate-and-track-approvals"),
  },
  {
    id: "workflow.build-template",
    slug: "build-an-approval-workflow-template",
    title: "Build an approval workflow template",
    summary: "Create approver groups, configure stages and conditions, validate resolution, and publish the right version safely.",
    category: "approvals-and-workflow",
    tags: ["workflow", "approval", "template", "approver group", "dynamic role", "conditions", "routing", "quorum"],
    aliases: ["new workflow", "approval stages", "approval template", "publish workflow", "stalled workflow", "auto skip approver", "school workflow version"],
    audiences: ["platform-administrator", "approver"],
    routes: [R.WORKFLOW.APPROVER_GROUPS, R.WORKFLOW.TEMPLATES, R.WORKFLOW.TEMPLATE_NEW, R.WORKFLOW.TEMPLATE_DETAIL_PATH, R.WORKFLOW.TEMPLATE_EDIT_PATH],
    actionIds: ["view-workflow-templates", "create-workflow-template"],
    access: { mode: "all", permissions: [P.VIEW_WORKFLOW_TEMPLATES, P.MANAGE_WORKFLOW_TEMPLATES] },
    primaryRoute: R.WORKFLOW.TEMPLATE_NEW,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "prepare-approver-sources", title: "Prepare approver groups and dynamic rules" },
      { id: "define-template-details", title: "Define template details" },
      { id: "build-stages", title: "Build stages and approvers" },
      { id: "validate-routing", title: "Validate routing and resolution" },
      { id: "publish-and-revise", title: "Publish and revise the template" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["workflow.review-and-act", "workflow.delegate-and-track", "troubleshooting.permission-denied"],
    walkthroughId: "walkthrough.workflow.build-template",
    estimatedMinutes: 12,
    owner: OWNER,
    reviewedAt: C5_REVIEWED_AT,
    risk: "high",
    featured: true,
    status: "published",
    article: () => import("./content/approvals-and-workflow/build-workflow-template"),
  },
  {
    id: "finance.configure-foundations",
    slug: "configure-finance-foundations",
    title: "Configure finance foundations",
    summary: "Set up the entity, fiscal calendar, chart, reference data, and posting defaults in the correct order.",
    category: "finance-and-payments",
    tags: ["finance setup", "entity", "chart of accounts", "currency", "tax", "cost centre", "dimension", "settings"],
    aliases: [
      "set up finance", "finance configuration", "new ledger entity", "create account",
      "account mapping", "fx rate", "tax code", "cost center", "analysis dimension",
    ],
    audiences: ["finance-officer", "platform-administrator"],
    routes: [
      R.FINANCE.SETUP,
      `${R.FINANCE.SETUP}/:section`,
      `${R.FINANCE.SETUP}/entities`,
      R.FINANCE.SETTINGS,
      `${R.FINANCE.SETTINGS}/:section`,
    ],
    actionIds: [
      "view-entities", "create-entity", "view-chart-of-accounts", "create-gl-account",
      "view-currencies-fx", "view-tax-codes", "create-tax-code", "view-cost-centres",
      "create-cost-centre", "view-dimensions", "view-finance-settings",
    ],
    access: { mode: "any", permissions: [
      P.FIN_VIEW_ENTITIES, P.FIN_VIEW_ACCOUNTS, P.FIN_VIEW_CURRENCIES,
      P.FIN_VIEW_TAX_CODES, P.FIN_VIEW_COST_CENTERS, P.FIN_VIEW_DIMENSIONS,
      P.FIN_VIEW_SETTINGS,
    ] },
    primaryRoute: `${R.FINANCE.SETUP}/entities`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "choose-the-scope", title: "Choose the entity and setup order" },
      { id: "create-the-entity", title: "Create the ledger entity and calendar" },
      { id: "build-the-chart", title: "Build and check the chart of accounts" },
      { id: "add-reference-data", title: "Add currencies, tax, cost centres, and dimensions" },
      { id: "map-posting-defaults", title: "Map posting defaults and policies" },
      { id: "verify-the-foundation", title: "Verify the foundation before live work" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["finance.create-and-post-journal", "finance.close-lock-or-reopen-period", "workflow.build-template"],
    walkthroughId: "walkthrough.finance.configure-foundations",
    estimatedMinutes: 11,
    owner: OWNER,
    reviewedAt: C6A_REVIEWED_AT,
    risk: "high",
    featured: true,
    status: "published",
    article: () => import("./content/finance-and-payments/configure-finance-foundations"),
  },
  {
    id: "finance.create-and-post-journal",
    slug: "create-and-post-a-journal",
    title: "Create and post a journal",
    summary: "Build balanced journal lines, choose an open period, submit, approve, and post as permitted.",
    category: "finance-and-payments",
    tags: ["finance", "journal", "ledger", "posting", "debit", "credit", "reversal"],
    aliases: ["manual journal", "journal entry", "general ledger entry", "direct entry", "post entry", "journal will not balance"],
    audiences: ["finance-officer", "approver"],
    routes: [R.FINANCE.LEDGER],
    actionIds: ["view-general-ledger", "new-journal-entry"],
    access: { mode: "any", permissions: [P.FIN_VIEW_JOURNALS, P.FIN_POST_DIRECT_ENTRY, P.FIN_SUBMIT_JOURNAL, P.FIN_REVERSE_JOURNAL] },
    primaryRoute: R.FINANCE.LEDGER,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "choose-the-journal-path", title: "Choose the correct journal path" },
      { id: "prepare-the-entry", title: "Prepare the entry" },
      { id: "build-balanced-lines", title: "Build balanced debit and credit lines" },
      { id: "tag-and-review", title: "Tag and review the journal" },
      { id: "post-or-submit", title: "Post a direct entry or submit a draft" },
      { id: "reverse-or-void", title: "Reverse or void safely" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["finance.configure-foundations", "finance.close-lock-or-reopen-period", "workflow.review-and-act"],
    walkthroughId: "walkthrough.finance.create-and-post-journal",
    estimatedMinutes: 9,
    owner: OWNER,
    reviewedAt: C6A_REVIEWED_AT,
    risk: "high",
    featured: true,
    status: "published",
    article: () => import("./content/finance-and-payments/create-and-post-journal"),
  },
  {
    id: "finance.close-lock-or-reopen-period",
    slug: "close-lock-or-reopen-a-fiscal-period",
    title: "Close, lock, or reopen a fiscal period",
    summary: "Use the close checklist, control posting windows, close the fiscal year, and understand permanent locks.",
    category: "finance-and-payments",
    tags: ["finance", "fiscal period", "month end", "close", "soft close", "lock", "reopen", "year end"],
    aliases: [
      "close period", "month end close", "soft close period", "reopen period",
      "lock period", "close fiscal year", "posting date rejected", "no fiscal period covers this date",
    ],
    audiences: ["finance-officer", "approver", "platform-administrator"],
    routes: [
      `${R.FINANCE.SETUP}/:section`,
      `${R.FINANCE.SETUP}/periods`,
      `${R.FINANCE.REPORTS}/:section`,
    ],
    actionIds: ["view-fiscal-periods"],
    access: { mode: "any", permissions: [P.FIN_VIEW_PERIODS, P.FIN_CLOSE_PERIOD, P.FIN_REOPEN_PERIOD, P.FIN_LOCK_PERIOD] },
    primaryRoute: `${R.FINANCE.SETUP}/periods`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "create-the-calendar", title: "Create and extend the fiscal calendar" },
      { id: "understand-period-statuses", title: "Understand period statuses" },
      { id: "inspect-the-checklist", title: "Inspect the close checklist" },
      { id: "soft-close-or-close", title: "Soft-close or run the period close" },
      { id: "close-the-fiscal-year", title: "Close the fiscal year" },
      { id: "reopen-or-lock", title: "Reopen or permanently lock" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["finance.configure-foundations", "finance.create-and-post-journal", "workflow.review-and-act"],
    walkthroughId: "walkthrough.finance.close-lock-or-reopen-period",
    estimatedMinutes: 10,
    owner: OWNER,
    reviewedAt: C6A_REVIEWED_AT,
    risk: "high",
    featured: true,
    status: "published",
    article: () => import("./content/finance-and-payments/close-lock-or-reopen-period"),
  },
  {
    id: "finance.invoice-and-allocate-receipt",
    slug: "invoice-a-customer-and-allocate-a-receipt",
    title: "Invoice a customer and allocate a receipt",
    summary: "Prepare customers and fees, issue an invoice, record money received, and settle the correct open items.",
    category: "finance-and-payments",
    tags: ["receivables", "customer", "fee structure", "invoice", "receipt", "allocation", "credit note", "refund", "write-off", "dunning"],
    aliases: [
      "raise customer invoice", "record customer payment", "apply receipt", "unallocated receipt",
      "customer credit", "invoice payment", "allocate oldest first", "reverse receipt",
      "fee waiver", "payment plan", "customer balance",
    ],
    audiences: ["finance-officer"],
    routes: [R.FINANCE.RECEIVABLES, `${R.FINANCE.RECEIVABLES}/:section`, `${R.FINANCE.RECEIVABLES}/receipts`],
    actionIds: [
      "view-customers", "create-customer", "view-fee-structures", "create-fee-structure",
      "view-ar-invoices", "create-ar-invoice", "view-receipts", "record-receipt",
      "view-credit-notes", "view-refunds", "view-payment-plans", "view-concessions", "view-dunning",
    ],
    access: { mode: "any", permissions: [P.FIN_VIEW_INVOICES, P.FIN_VIEW_PAYMENTS, P.FIN_VIEW_CUSTOMERS] },
    primaryRoute: `${R.FINANCE.RECEIVABLES}/receipts`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "prepare-the-customer-and-fees", title: "Prepare the customer and fees" },
      { id: "create-and-issue-the-invoice", title: "Create and issue the invoice" },
      { id: "record-the-receipt", title: "Record the receipt" },
      { id: "allocate-the-receipt", title: "Allocate the receipt" },
      { id: "adjust-or-recover-a-balance", title: "Adjust or recover a customer balance" },
      { id: "verify-the-ledger-result", title: "Verify the ledger result" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["finance.email-customer-documents", "finance.create-and-post-journal", "finance.run-financial-reports"],
    walkthroughId: "walkthrough.finance.invoice-and-allocate-receipt",
    estimatedMinutes: 11,
    owner: OWNER,
    reviewedAt: C6B_REVIEWED_AT,
    risk: "high",
    featured: true,
    status: "published",
    article: () => import("./content/finance-and-payments/invoice-and-allocate-receipt"),
  },
  {
    id: "finance.email-customer-documents",
    slug: "email-a-customer-an-invoice-receipt-or-statement",
    title: "Email a customer an invoice, receipt, or statement",
    summary: "Preview recipients and subject, send the correct finance document, and check delivery history before retrying.",
    category: "finance-and-payments",
    tags: ["email", "customer", "invoice", "receipt", "statement", "recipient", "delivery history", "retry"],
    aliases: [
      "send customer invoice", "email invoice", "email receipt", "send statement",
      "customer did not receive invoice", "delivery failed", "retry customer email", "wrong email address",
    ],
    audiences: ["finance-officer", "support-and-operations"],
    routes: [R.FINANCE.RECEIVABLES, `${R.FINANCE.RECEIVABLES}/:section`, `${R.FINANCE.RECEIVABLES}/invoices`],
    actionIds: ["view-ar-invoices", "view-receipts", "view-customers"],
    access: { mode: "any", permissions: [P.FIN_EMAIL_INVOICE, P.FIN_EMAIL_RECEIPT, P.FIN_EMAIL_STATEMENT] },
    primaryRoute: `${R.FINANCE.RECEIVABLES}/invoices`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "choose-the-document", title: "Choose the correct document" },
      { id: "preview-the-delivery", title: "Preview the delivery" },
      { id: "send-and-check-history", title: "Send and check delivery history" },
      { id: "retry-a-failed-delivery", title: "Retry a failed delivery" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["finance.invoice-and-allocate-receipt", "troubleshooting.permission-denied"],
    walkthroughId: "walkthrough.finance.email-customer-documents",
    estimatedMinutes: 6,
    owner: OWNER,
    reviewedAt: C6B_REVIEWED_AT,
    risk: "high",
    featured: true,
    status: "published",
    article: () => import("./content/finance-and-payments/email-customer-documents"),
  },
  {
    id: "finance.reconcile-bank-statement",
    slug: "reconcile-a-bank-statement",
    title: "Reconcile a bank statement",
    summary: "Import statement evidence, match it to book entries, resolve exceptions, and complete reconciliation safely.",
    category: "finance-and-payments",
    tags: ["bank", "statement", "reconciliation", "matching", "import", "book balance", "bank balance", "exception"],
    aliases: [
      "bank recon", "match bank line", "unreconciled difference", "statement import",
      "bank charge", "payment in transit", "ignored bank line", "complete reconciliation",
    ],
    audiences: ["finance-officer", "approver"],
    routes: [R.FINANCE.BANKING, R.FINANCE.BANK_RECON],
    actionIds: ["view-bank-accounts", "view-bank-reconciliation", "import-bank-statement"],
    access: { mode: "any", permissions: [P.FIN_VIEW_BANK_ACCOUNTS, P.FIN_IMPORT_STATEMENT, P.FIN_RECONCILE_BANK] },
    primaryRoute: R.FINANCE.BANK_RECON,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "prepare-the-account", title: "Prepare the bank account" },
      { id: "import-the-statement", title: "Import the statement" },
      { id: "match-clear-evidence", title: "Match clear evidence" },
      { id: "resolve-exceptions", title: "Resolve exceptions" },
      { id: "complete-and-review", title: "Complete and review reconciliation" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["finance.create-and-post-journal", "finance.close-lock-or-reopen-period", "finance.run-financial-reports"],
    walkthroughId: "walkthrough.finance.reconcile-bank-statement",
    estimatedMinutes: 10,
    owner: OWNER,
    reviewedAt: C6B_REVIEWED_AT,
    risk: "high",
    featured: true,
    status: "published",
    article: () => import("./content/finance-and-payments/reconcile-bank-statement"),
  },
  {
    id: "finance.run-financial-reports",
    slug: "run-and-interpret-financial-reports",
    title: "Run and interpret financial reports",
    summary: "Choose the right statement, scope its period, check reconciliation signals, compare results, and export evidence.",
    category: "finance-and-payments",
    tags: ["report", "trial balance", "income statement", "profit and loss", "balance sheet", "cash flow", "equity", "analytics", "export"],
    aliases: [
      "run financial report", "p and l", "p&l", "statement of financial position",
      "trial balance out of balance", "compare periods", "cost centre report", "dimension analysis",
    ],
    audiences: ["finance-officer", "approver"],
    routes: [R.FINANCE.REPORTS, `${R.FINANCE.REPORTS}/:section`, `${R.FINANCE.REPORTS}/trial-balance`],
    actionIds: [
      "view-trial-balance", "view-income-statement", "view-balance-sheet",
      "view-cash-flow", "view-changes-in-equity", "view-cost-dimension-analysis",
    ],
    access: { mode: "all", permissions: [P.FIN_VIEW_REPORTS] },
    primaryRoute: `${R.FINANCE.REPORTS}/trial-balance`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "choose-the-report", title: "Choose the report" },
      { id: "set-scope-and-comparison", title: "Set scope and comparison" },
      { id: "read-reconciliation-signals", title: "Read reconciliation signals" },
      { id: "export-and-share", title: "Export and share evidence" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["finance.invoice-and-allocate-receipt", "finance.reconcile-bank-statement", "finance.close-lock-or-reopen-period"],
    estimatedMinutes: 8,
    owner: OWNER,
    reviewedAt: C6B_REVIEWED_AT,
    risk: "medium",
    featured: true,
    status: "published",
    article: () => import("./content/finance-and-payments/run-financial-reports"),
  },
  {
    id: "finance.run-payroll",
    slug: "run-post-and-pay-payroll",
    title: "Run, post, and pay payroll",
    summary: "Prepare the salary roster, generate a payroll run, review deductions, post liabilities, pay net wages, and produce statutory evidence.",
    category: "finance-and-payments",
    tags: ["payroll", "salary", "payslip", "PAYE", "pension", "net wages", "salary structure", "statutory return", "payroll scope", "branch"],
    aliases: ["run payroll", "generate payroll", "pay salaries", "salary run", "employee salary", "print payslip", "payroll cancelled", "payroll figures hidden", "per branch payroll", "payroll scope", "branch payroll", "unassigned staff", "assign staff to a branch", "payroll run overlaps"],
    audiences: ["finance-officer", "approver"],
    routes: [R.FINANCE.PAYROLL, `${R.FINANCE.BUDGETS}/tax`],
    actionIds: ["view-payroll", "create-payroll-run", "view-tax-remittance"],
    access: { mode: "any", permissions: [P.FIN_VIEW_PAYROLL, P.FIN_CREATE_PAYROLL, P.FIN_POST_PAYROLL, P.FIN_PAY_PAYROLL] },
    primaryRoute: R.FINANCE.PAYROLL,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "prepare-the-roster", title: "Prepare salary structures and the employee roster" },
      { id: "generate-and-review", title: "Generate and review the payroll run" },
      { id: "post-the-run", title: "Calculate and post payroll" },
      { id: "pay-net-wages", title: "Pay net wages" },
      { id: "produce-evidence", title: "Produce payslips and statutory evidence" },
      { id: "correct-a-run", title: "Correct or cancel a payroll run" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["finance.file-and-pay-tax", "finance.create-and-post-journal", "finance.run-financial-reports"],
    walkthroughId: "walkthrough.finance.run-payroll",
    estimatedMinutes: 11,
    owner: OWNER,
    reviewedAt: C6C_REVIEWED_AT,
    risk: "high",
    featured: true,
    status: "published",
    article: () => import("./content/finance-and-payments/run-payroll"),
  },
  {
    id: "finance.submit-and-settle-expense-claim",
    slug: "submit-post-and-settle-an-expense-claim",
    title: "Submit, post, and settle an expense claim",
    summary: "Record supported expense lines, attach receipts, post the approved claim, and settle the employee or supplier safely.",
    category: "finance-and-payments",
    tags: ["expense", "claim", "receipt", "reimbursement", "employee", "posting", "settlement"],
    aliases: ["expense claim", "employee reimbursement", "attach expense receipt", "post expense", "pay expense claim", "reject claim", "void expense"],
    audiences: ["finance-officer", "approver"],
    routes: [R.FINANCE.EXPENSES, `${R.FINANCE.EXPENSES}/:section`, `${R.FINANCE.EXPENSES}/claims`],
    actionIds: ["view-expense-claims", "create-expense-claim"],
    access: { mode: "any", permissions: [P.FIN_VIEW_EXPENSE_CLAIMS, P.FIN_CREATE_EXPENSE_CLAIM, P.FIN_POST_EXPENSE_CLAIM, P.FIN_SETTLE_EXPENSE_CLAIM] },
    primaryRoute: `${R.FINANCE.EXPENSES}/claims`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "create-the-claim", title: "Create the claim and its lines" },
      { id: "attach-and-check-evidence", title: "Attach and check receipts" },
      { id: "post-or-reject", title: "Post or reject the claim" },
      { id: "settle-the-claim", title: "Settle the approved claim" },
      { id: "void-a-mistake", title: "Void a claim raised in error" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["finance.manage-petty-cash", "finance.create-and-post-journal", "workflow.review-and-act"],
    walkthroughId: "walkthrough.finance.submit-and-settle-expense-claim",
    estimatedMinutes: 9,
    owner: OWNER,
    reviewedAt: C6C_REVIEWED_AT,
    risk: "high",
    status: "published",
    article: () => import("./content/finance-and-payments/submit-and-settle-expense-claim"),
  },
  {
    id: "finance.manage-petty-cash",
    slug: "establish-spend-and-replenish-petty-cash",
    title: "Establish, spend, and replenish petty cash",
    summary: "Set up an imprest float, post supported vouchers, monitor cash on hand, and replenish without overstating the fund.",
    category: "finance-and-payments",
    tags: ["petty cash", "imprest", "float", "voucher", "custodian", "replenishment", "cash on hand"],
    aliases: ["establish petty cash", "new petty cash voucher", "post voucher", "replenish float", "petty cash shortfall", "void voucher"],
    audiences: ["finance-officer", "approver"],
    routes: [R.FINANCE.EXPENSES, `${R.FINANCE.EXPENSES}/:section`, `${R.FINANCE.EXPENSES}/petty-cash`],
    actionIds: ["view-petty-cash", "new-petty-cash-voucher"],
    access: { mode: "any", permissions: [P.FIN_VIEW_PETTY_CASH, P.FIN_ESTABLISH_PETTY_CASH, P.FIN_CREATE_PETTY_CASH_VOUCHER, P.FIN_POST_PETTY_CASH_VOUCHER, P.FIN_REPLENISH_PETTY_CASH] },
    primaryRoute: `${R.FINANCE.EXPENSES}/petty-cash`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "establish-the-float", title: "Establish the float" },
      { id: "record-a-voucher", title: "Record and post a voucher" },
      { id: "monitor-the-register", title: "Monitor the register and cash on hand" },
      { id: "replenish-the-float", title: "Replenish the float" },
      { id: "correct-a-voucher", title: "Correct a voucher posted in error" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["finance.submit-and-settle-expense-claim", "finance.reconcile-bank-statement", "finance.run-financial-reports"],
    walkthroughId: "walkthrough.finance.manage-petty-cash",
    estimatedMinutes: 9,
    owner: OWNER,
    reviewedAt: C6C_REVIEWED_AT,
    risk: "high",
    status: "published",
    article: () => import("./content/finance-and-payments/manage-petty-cash"),
  },
  {
    id: "finance.build-and-approve-budget",
    slug: "build-approve-and-monitor-a-budget",
    title: "Build, approve, and monitor a budget",
    summary: "Define a budget period, add account and cost-centre lines, approve the plan, and investigate variance without changing actuals.",
    category: "finance-and-payments",
    tags: ["budget", "forecast", "variance", "heatmap", "cost centre", "planned", "actual"],
    aliases: ["create budget", "approve budget", "budget variance", "overspend", "forecast", "budget heatmap", "delete budget line"],
    audiences: ["finance-officer", "approver"],
    routes: [R.FINANCE.BUDGETS, `${R.FINANCE.BUDGETS}/:section`, `${R.FINANCE.BUDGETS}/budgets`],
    actionIds: ["view-budgets", "create-budget"],
    access: { mode: "any", permissions: [P.FIN_VIEW_BUDGETS, P.FIN_CREATE_BUDGET, P.FIN_EDIT_BUDGET, P.FIN_APPROVE_BUDGET] },
    primaryRoute: `${R.FINANCE.BUDGETS}/budgets`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "create-the-budget", title: "Create the budget header" },
      { id: "build-budget-lines", title: "Build account and cost-centre lines" },
      { id: "review-and-approve", title: "Review and approve the plan" },
      { id: "monitor-variance", title: "Monitor variance and the heatmap" },
      { id: "revise-or-remove", title: "Revise or remove a draft safely" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["finance.run-financial-reports", "finance.close-lock-or-reopen-period", "workflow.review-and-act"],
    walkthroughId: "walkthrough.finance.build-and-approve-budget",
    estimatedMinutes: 9,
    owner: OWNER,
    reviewedAt: C6C_REVIEWED_AT,
    risk: "high",
    status: "published",
    article: () => import("./content/finance-and-payments/build-and-approve-budget"),
  },
  {
    id: "finance.manage-fixed-assets",
    slug: "acquire-depreciate-and-dispose-of-a-fixed-asset",
    title: "Acquire, depreciate, and dispose of a fixed asset",
    summary: "Create the asset record, capitalise its cost, post due depreciation, and dispose of it with a complete audit trail.",
    category: "finance-and-payments",
    tags: ["fixed asset", "acquisition", "capitalise", "depreciation", "net book value", "disposal", "gain", "loss"],
    aliases: ["add asset", "acquire asset", "run depreciation", "depreciate to date", "dispose asset", "fully depreciated", "asset register"],
    audiences: ["finance-officer", "approver"],
    routes: [R.FINANCE.BUDGETS, `${R.FINANCE.BUDGETS}/:section`, `${R.FINANCE.BUDGETS}/assets`],
    actionIds: ["view-fixed-assets", "create-fixed-asset"],
    access: { mode: "any", permissions: [P.FIN_VIEW_FIXED_ASSETS, P.FIN_CREATE_FIXED_ASSET, P.FIN_ACQUIRE_FIXED_ASSET, P.FIN_DEPRECIATE_FIXED_ASSET, P.FIN_DISPOSE_FIXED_ASSET] },
    primaryRoute: `${R.FINANCE.BUDGETS}/assets`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "create-the-record", title: "Create the asset record" },
      { id: "capitalise-the-asset", title: "Capitalise the acquisition" },
      { id: "post-depreciation", title: "Post due depreciation" },
      { id: "dispose-the-asset", title: "Dispose of the asset" },
      { id: "verify-the-register", title: "Verify the register and ledger" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["finance.create-and-post-journal", "finance.run-financial-reports", "finance.close-lock-or-reopen-period"],
    walkthroughId: "walkthrough.finance.manage-fixed-assets",
    estimatedMinutes: 10,
    owner: OWNER,
    reviewedAt: C6C_REVIEWED_AT,
    risk: "high",
    status: "published",
    article: () => import("./content/finance-and-payments/manage-fixed-assets"),
  },
  {
    id: "finance.file-and-pay-tax",
    slug: "prepare-file-and-pay-a-tax-return",
    title: "Prepare, file, and pay a tax return",
    summary: "Create the obligation, prepare a return from the ledger, record filing evidence, remit the liability, and correct an unpaid filing.",
    category: "finance-and-payments",
    tags: ["tax", "filing", "remittance", "PAYE", "pension", "VAT", "WHT", "obligation", "authority"],
    aliases: ["file tax return", "pay tax", "tax remittance", "prepare filing", "unfile return", "partial tax payment", "filing reference"],
    audiences: ["finance-officer", "approver"],
    routes: [R.FINANCE.BUDGETS, `${R.FINANCE.BUDGETS}/:section`, `${R.FINANCE.BUDGETS}/tax`, R.FINANCE.PAYROLL],
    actionIds: ["view-tax-remittance", "view-payroll"],
    access: { mode: "any", permissions: [P.FIN_VIEW_TAX, P.FIN_MANAGE_TAX, P.FIN_FILE_TAX, P.FIN_PAY_TAX] },
    primaryRoute: `${R.FINANCE.BUDGETS}/tax`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "create-the-obligation", title: "Create the statutory obligation" },
      { id: "prepare-the-filing", title: "Prepare the filing from the ledger" },
      { id: "record-the-filing", title: "Record the return filed with the authority" },
      { id: "remit-the-liability", title: "Remit the liability" },
      { id: "correct-an-unpaid-filing", title: "Correct an unpaid filing" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["finance.run-payroll", "finance.create-and-post-journal", "finance.reconcile-bank-statement"],
    walkthroughId: "walkthrough.finance.file-and-pay-tax",
    estimatedMinutes: 9,
    owner: OWNER,
    reviewedAt: C6C_REVIEWED_AT,
    risk: "high",
    status: "published",
    article: () => import("./content/finance-and-payments/file-and-pay-tax"),
  },
  {
    id: "finance.collect-online-payments",
    slug: "collect-online-payments-and-manage-virtual-accounts",
    title: "Collect online payments and manage virtual accounts",
    summary: "Trace provider collections, issue scoped virtual accounts, protect bank details, and resolve a payment that has not reached its business record.",
    category: "finance-and-payments",
    tags: ["collection", "online payment", "gateway", "virtual account", "provider", "customer", "webhook", "settlement"],
    aliases: ["payment collection", "gateway payment", "virtual account", "customer paid online", "collection pending", "provider reference", "payment webhook failed"],
    audiences: ["finance-officer", "support-and-operations"],
    routes: [R.FINANCE.COLLECTIONS, `${R.FINANCE.COLLECTIONS}/:section`, `${R.FINANCE.COLLECTIONS}/virtual-accounts`, `${R.FINANCE.PAYMENTS}/webhooks`],
    actionIds: ["view-collections", "view-virtual-accounts", "create-virtual-account", "view-payment-webhooks"],
    access: { mode: "any", permissions: [P.PAY_VIEW_COLLECTIONS, P.PAY_VIEW_VIRTUAL_ACCOUNTS, P.PAY_CREATE_VIRTUAL_ACCOUNT, P.PAY_VIEW_WEBHOOKS] },
    primaryRoute: R.FINANCE.COLLECTIONS,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "trace-the-collection", title: "Trace the provider collection" },
      { id: "manage-virtual-accounts", title: "Create and manage virtual accounts" },
      { id: "check-business-posting", title: "Check the receipt and ledger result" },
      { id: "resolve-a-failed-event", title: "Resolve a failed provider event" },
      { id: "protect-payment-data", title: "Protect sensitive payment data" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["finance.invoice-and-allocate-receipt", "finance.send-payouts-and-resolve-settlements", "finance.reconcile-bank-statement"],
    walkthroughId: "walkthrough.finance.collect-online-payments",
    estimatedMinutes: 9,
    owner: OWNER,
    reviewedAt: C6C_REVIEWED_AT,
    risk: "high",
    featured: true,
    status: "published",
    article: () => import("./content/finance-and-payments/collect-online-payments"),
  },
  {
    id: "finance.send-payouts-and-resolve-settlements",
    slug: "send-payouts-and-resolve-settlement-failures",
    title: "Send payouts and resolve settlement failures",
    summary: "Prepare a payout or approval batch, follow provider confirmation, reconcile settlement evidence, and recover failed events without double-paying.",
    category: "finance-and-payments",
    tags: ["payout", "batch", "disbursement", "settlement", "provider", "webhook", "failed", "reversed", "beneficiary"],
    aliases: ["send payout", "pay vendor", "bulk disbursement", "payout batch", "payout failed", "settlement pending", "replay webhook", "payment reversed"],
    audiences: ["finance-officer", "approver", "support-and-operations"],
    routes: [R.FINANCE.PAYMENTS, `${R.FINANCE.PAYMENTS}/:section`, `${R.FINANCE.PAYMENTS}/payouts`, `${R.FINANCE.PAYMENTS}/settlement`, `${R.FINANCE.PAYMENTS}/webhooks`],
    actionIds: ["view-payouts", "new-payout", "view-payout-batches", "view-settlement", "view-transactions-log", "view-payment-webhooks"],
    access: { mode: "any", permissions: [P.PAY_VIEW_PAYOUTS, P.PAY_CREATE_PAYOUT, P.PAY_VIEW_PAYMENT_REPORTS, P.PAY_VIEW_WEBHOOKS] },
    primaryRoute: `${R.FINANCE.PAYMENTS}/payouts`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "prepare-the-beneficiary", title: "Prepare the beneficiary and payable" },
      { id: "send-one-or-build-a-batch", title: "Send one payout or build a batch" },
      { id: "follow-provider-status", title: "Follow provider and posting status" },
      { id: "reconcile-settlement", title: "Reconcile settlement evidence" },
      { id: "recover-a-failure", title: "Recover a failure without double-paying" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["finance.collect-online-payments", "finance.reconcile-bank-statement", "workflow.review-and-act"],
    walkthroughId: "walkthrough.finance.send-payouts-and-resolve-settlements",
    estimatedMinutes: 10,
    owner: OWNER,
    reviewedAt: C6C_REVIEWED_AT,
    risk: "high",
    featured: true,
    status: "published",
    article: () => import("./content/finance-and-payments/send-payouts-and-resolve-settlements"),
  },
  {
    id: "procurement.add-and-govern-vendor",
    slug: "add-and-govern-a-procurement-vendor",
    title: "Add and govern a procurement vendor",
    summary: "Create a supplier master, protect sensitive details, set purchasing eligibility, and review its commercial history.",
    category: "procurement-and-inventory",
    tags: ["vendor", "supplier", "KYC", "bank details", "payment terms", "on hold", "risk", "contacts"],
    aliases: ["add supplier", "register vendor", "supplier master", "vendor kyc", "put vendor on hold", "vendor bank details", "vendor rejected"],
    audiences: ["procurement-officer", "finance-officer", "approver"],
    routes: [R.PROCUREMENT.VENDORS, `${R.PROCUREMENT.VENDORS}/vendors`],
    actionIds: ["view-vendors", "create-vendor"],
    access: { mode: "any", permissions: [P.PROC_VIEW_VENDORS, P.PROC_CREATE_VENDOR, P.PROC_UPDATE_VENDOR, P.PROC_MANAGE_VENDOR] },
    primaryRoute: `${R.PROCUREMENT.VENDORS}/vendors`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "create-the-vendor", title: "Create the vendor master" },
      { id: "protect-sensitive-details", title: "Protect contact, tax, and bank details" },
      { id: "set-purchasing-governance", title: "Set KYC, risk, hold, and active status" },
      { id: "review-commercial-history", title: "Review history and performance" },
      { id: "change-or-retire-a-vendor", title: "Change or retire a vendor safely" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["procurement.manage-categories-and-catalogue", "procurement.run-rfq-and-award", "procurement.manage-contract-lifecycle"],
    walkthroughId: "walkthrough.procurement.add-and-govern-vendor",
    estimatedMinutes: 9,
    owner: OWNER,
    reviewedAt: C7A_REVIEWED_AT,
    risk: "high",
    featured: true,
    status: "published",
    article: () => import("./content/procurement-and-inventory/add-and-govern-vendor"),
  },
  {
    id: "procurement.manage-categories-and-catalogue",
    slug: "manage-procurement-categories-and-catalogue-items",
    title: "Manage procurement categories and catalogue items",
    summary: "Build a controlled category hierarchy and reusable item defaults without rewriting historical purchasing documents.",
    category: "procurement-and-inventory",
    tags: ["category", "catalogue", "catalog", "item", "SKU", "unit of measure", "preferred vendor", "expense account", "purchase tax"],
    aliases: ["new procurement category", "add catalog item", "add catalogue item", "product catalog", "item master", "change standard price", "uncategorised item"],
    audiences: ["procurement-officer", "finance-officer"],
    routes: [`${R.PROCUREMENT.VENDORS}/categories`, `${R.PROCUREMENT.VENDORS}/catalog`],
    actionIds: ["view-categories", "create-category", "view-catalog", "add-catalog-item"],
    access: { mode: "any", permissions: [P.PROC_VIEW_CATEGORIES, P.PROC_CREATE_CATEGORY, P.PROC_VIEW_CATALOG, P.PROC_CREATE_CATALOG_ITEM] },
    primaryRoute: `${R.PROCUREMENT.VENDORS}/categories`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "build-the-category-tree", title: "Build the category hierarchy" },
      { id: "set-category-defaults", title: "Set category accounting defaults" },
      { id: "create-a-catalogue-item", title: "Create a catalogue item" },
      { id: "understand-default-precedence", title: "Understand default precedence" },
      { id: "review-pricing-and-history", title: "Review pricing and purchase history" },
      { id: "retire-master-data", title: "Retire master data without changing history" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["procurement.add-and-govern-vendor", "procurement.run-rfq-and-award", "procurement.complete-procure-to-pay"],
    estimatedMinutes: 8,
    owner: OWNER,
    reviewedAt: C7A_REVIEWED_AT,
    risk: "medium",
    status: "published",
    article: () => import("./content/procurement-and-inventory/manage-categories-and-catalogue"),
  },
  {
    id: "procurement.run-rfq-and-award",
    slug: "run-an-rfq-compare-quotes-and-award-a-vendor",
    title: "Run an RFQ, compare quotes, and award a vendor",
    summary: "Issue a request to eligible vendors, record firm quotations, compare the bids, and award a draft purchase order.",
    category: "procurement-and-inventory",
    tags: ["RFQ", "quotation", "quote", "vendor invitation", "competition", "award", "purchase order", "sourcing"],
    aliases: ["request for quotation", "invite suppliers", "record supplier quote", "compare quotations", "award quotation", "bid minimum", "sole source exception"],
    audiences: ["procurement-officer", "approver"],
    routes: [R.PROCUREMENT.SOURCING, `${R.PROCUREMENT.SOURCING}/rfqs`, `${R.PROCUREMENT.SOURCING}/quotations`],
    actionIds: ["view-rfqs", "create-rfq", "view-quotations", "create-quotation"],
    access: { mode: "any", permissions: [P.PROC_VIEW_RFQS, P.PROC_CREATE_RFQ, P.PROC_ISSUE_RFQ, P.PROC_VIEW_QUOTATIONS, P.PROC_AWARD_QUOTATION] },
    primaryRoute: `${R.PROCUREMENT.SOURCING}/rfqs`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "prepare-the-rfq", title: "Prepare the RFQ scope" },
      { id: "invite-and-issue", title: "Invite eligible vendors and issue" },
      { id: "manage-live-sourcing", title: "Manage invitations, deadlines, and amendments" },
      { id: "record-firm-quotations", title: "Record and submit firm quotations" },
      { id: "compare-and-award", title: "Compare and award the winning quotation" },
      { id: "close-or-cancel", title: "Close or cancel without an award" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["procurement.add-and-govern-vendor", "procurement.manage-categories-and-catalogue", "procurement.complete-procure-to-pay"],
    walkthroughId: "walkthrough.procurement.run-rfq-and-award",
    estimatedMinutes: 11,
    owner: OWNER,
    reviewedAt: C7A_REVIEWED_AT,
    risk: "high",
    featured: true,
    status: "published",
    article: () => import("./content/procurement-and-inventory/run-rfq-and-award"),
  },
  {
    id: "procurement.manage-contract-lifecycle",
    slug: "create-activate-monitor-and-renew-a-procurement-contract",
    title: "Create, activate, monitor, and renew a procurement contract",
    summary: "Register a supplier agreement, activate its term, track milestones and call-offs, then renew or terminate it safely.",
    category: "procurement-and-inventory",
    tags: ["contract", "supplier agreement", "activation", "milestone", "renewal", "termination", "call-off", "auto-renew"],
    aliases: ["new supplier contract", "activate contract", "complete milestone", "renew contract", "terminate contract", "contract expired", "linked purchase order"],
    audiences: ["procurement-officer", "approver"],
    routes: [R.PROCUREMENT.CONTRACTS],
    actionIds: ["view-contracts", "create-contract"],
    access: { mode: "any", permissions: [P.PROC_VIEW_CONTRACTS, P.PROC_CREATE_CONTRACT, P.PROC_ACTIVATE_CONTRACT, P.PROC_RENEW_CONTRACT, P.PROC_TERMINATE_CONTRACT] },
    primaryRoute: R.PROCUREMENT.CONTRACTS,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "create-the-draft", title: "Create the contract draft" },
      { id: "activate-the-contract", title: "Activate the approved agreement" },
      { id: "monitor-milestones", title: "Monitor milestones and purchase-order use" },
      { id: "edit-active-terms", title: "Edit active terms deliberately" },
      { id: "renew-or-terminate", title: "Renew or terminate the agreement" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["procurement.add-and-govern-vendor", "procurement.run-rfq-and-award", "procurement.complete-procure-to-pay"],
    walkthroughId: "walkthrough.procurement.manage-contract-lifecycle",
    estimatedMinutes: 9,
    owner: OWNER,
    reviewedAt: C7A_REVIEWED_AT,
    risk: "high",
    status: "published",
    article: () => import("./content/procurement-and-inventory/manage-contract-lifecycle"),
  },
  {
    id: "procurement.complete-procure-to-pay",
    slug: "complete-procure-to-pay",
    title: "Complete the procure-to-pay cycle",
    summary: "Move from requisition through purchase order, receipt, vendor invoice, and payment.",
    category: "procurement-and-inventory",
    tags: ["procurement", "requisition", "purchase order", "vendor payment"],
    aliases: ["p2p", "procure to pay", "purchase lifecycle"],
    audiences: ["procurement-officer", "approver", "finance-officer"],
    routes: [R.PROCUREMENT.REQUISITIONS, R.PROCUREMENT.PURCHASE_ORDERS, R.PROCUREMENT.GOODS_RECEIPTS, R.PROCUREMENT.VENDOR_INVOICES, R.PROCUREMENT.VENDOR_PAYMENTS],
    actionIds: ["create-requisition", "create-purchase-order", "post-goods-receipt", "create-vendor-invoice", "new-vendor-payment"],
    access: { mode: "any", permissions: [P.PROC_CREATE_REQUISITION, P.PROC_CREATE_PURCHASE_ORDER, P.PROC_CREATE_GOODS_RECEIPT, P.PROC_CREATE_VENDOR_INVOICE, P.PROC_CREATE_VENDOR_PAYMENT] },
    walkthroughId: "walkthrough.procurement.complete-procure-to-pay",
    owner: OWNER,
    reviewedAt: REVIEWED_AT,
    risk: "high",
    featured: true,
    status: "draft",
  },
  {
    id: "procurement.stock-locations",
    slug: "hold-stock-in-more-than-one-store",
    title: "Hold stock in more than one store",
    summary: "Set up stock locations, see what each store holds, and issue or adjust against the right one.",
    category: "procurement-and-inventory",
    tags: ["inventory", "stock", "location", "store", "campus"],
    aliases: ["stock locations", "second store", "annex store", "multi-campus stock", "warehouses"],
    audiences: ["procurement-officer", "platform-administrator"],
    // The inventory sections share one parameterised route, which is what the
    // catalog carries; naming concrete sections would not match a real pattern.
    routes: [R.PROCUREMENT.INVENTORY, `${R.PROCUREMENT.INVENTORY}/:section`],
    actionIds: ["view-stock-locations", "create-stock-location"],
    access: { mode: "any", permissions: [P.PROC_VIEW_STOCK, P.PROC_MANAGE_STOCK] },
    owner: OWNER,
    reviewedAt: REVIEWED_AT,
    // Movements post real journals, but the location dimension itself adds no new
    // posting: it decides which store a movement draws from. The risky actions
    // (issue, adjust) are covered where they already were.
    risk: "medium",
    // Registered so the workflow is discoverable and shows in the coverage report;
    // the article is unwritten, as it is for every guide in this category.
    status: "draft",
  },
  {
    id: "data.import-batch",
    slug: "upload-and-resolve-an-import-batch",
    title: "Upload and resolve an import batch",
    summary: "Prepare a file, validate its rows, resolve issues, and execute the import safely.",
    category: "data-imports-and-exports",
    tags: ["import", "spreadsheet", "validation", "batch"],
    aliases: ["bulk upload", "import data", "fix import errors"],
    audiences: ["platform-administrator", "support-and-operations"],
    routes: [R.DATA_IMPORTS.BATCHES.INDEX, R.DATA_IMPORTS.BATCHES.NEW, R.DATA_IMPORTS.BATCHES.VIEW_PATH],
    actionIds: ["view-import-batches", "upload-import-batch"],
    access: { mode: "all", permissions: [P.VIEW_IMPORT_BATCHES, P.UPLOAD_IMPORT_BATCH] },
    walkthroughId: "walkthrough.data.import-batch",
    owner: OWNER,
    reviewedAt: REVIEWED_AT,
    risk: "high",
    featured: true,
    status: "draft",
  },
  {
    id: "data.quick-export",
    slug: "export-what-a-table-is-showing",
    title: "Export what a table is showing",
    summary:
      "Use the Export button on a list screen to send that table's own filters to a background export, and read the warning when the file would be wider than the table.",
    category: "data-imports-and-exports",
    tags: ["export", "download", "csv", "excel", "filters"],
    aliases: [
      "export this table", "export filtered list", "download this list",
      "export to excel", "export to csv", "quick export",
    ],
    audiences: [
      "platform-administrator", "finance-officer", "procurement-officer",
      "support-and-operations",
    ],
    // The drawer has no route of its own - it opens over whichever list screen
    // started it. The routes here are where the RESULT lands, which is what a
    // reader looking for their file actually needs.
    routes: [R.EXPORT.FILES, R.EXPORT.QUEUES, R.EXPORT.NEW],
    primaryRoute: R.EXPORT.FILES,
    actionIds: ["view-export-queues"],
    access: { mode: "all", permissions: [P.VIEW_EXPORT_CATALOGUE, P.RUN_EXPORT] },
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "export-a-table", title: "Export what a table is showing" },
      { id: "when-the-file-is-wider", title: "When the file holds more than the table" },
      { id: "dates-and-row-counts", title: "Date windows and row counts" },
      { id: "find-your-file", title: "Find and download your file" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    article: () => import("./content/data-imports-and-exports/quick-export"),
    owner: OWNER,
    reviewedAt: DOCS_REVIEWED_AT,
    // Read-only: it produces a file, posts nothing. Medium rather than low
    // because an export can carry personal data out of the building, and
    // because the "wider than the table" case has to be understood, not skipped.
    risk: "medium",
    status: "published",
  },
  {
    id: "audit.investigate-event",
    slug: "investigate-an-audit-event",
    title: "Investigate an audit event",
    summary: "Filter events, inspect context, follow the entity trail, and preserve evidence.",
    category: "audit-and-security",
    tags: ["audit", "events", "entity trail", "investigation"],
    aliases: ["who changed this", "security event", "audit trail"],
    audiences: ["platform-administrator", "support-and-operations"],
    routes: [R.AUDIT.DASHBOARD, R.AUDIT.EVENTS, R.AUDIT.ENTITY_TRAILS],
    actionIds: ["view-security-dashboard", "view-audit-events", "view-entity-trails"],
    access: { mode: "any", permissions: [P.VIEW_AUDIT] },
    walkthroughId: "walkthrough.audit.investigate-event",
    owner: OWNER,
    reviewedAt: REVIEWED_AT,
    risk: "high",
    status: "draft",
  },
  {
    id: "platform.investigate-health",
    slug: "investigate-platform-health",
    title: "Investigate platform health",
    summary: "Use health signals to distinguish user, tenant, provider, job, and platform problems.",
    category: "platform-health-and-settings",
    tags: ["health", "incident", "job", "tenant", "provider"],
    aliases: ["system health", "platform outage", "failed job"],
    audiences: ["support-and-operations"],
    routes: [R.HEALTH.INDEX, R.HEALTH.JOBS, R.HEALTH.INCIDENTS, R.HEALTH.TENANTS],
    actionIds: ["view-system-health", "view-jobs-queues", "view-incidents", "view-tenant-health"],
    access: { mode: "any", permissions: [P.VIEW_HEALTH] },
    owner: OWNER,
    reviewedAt: REVIEWED_AT,
    risk: "high",
    status: "draft",
  },
  {
    id: "account.secure-account",
    slug: "secure-your-console-account",
    title: "Secure your Console account",
    summary: "Change your password, review sign-ins, and end sessions you do not recognize.",
    category: "account-and-personal-security",
    tags: ["account", "password", "session", "login history"],
    aliases: ["account security", "sign out another device", "change password"],
    audiences: ["all-users"],
    routes: [R.ME_SECURITY.OVERVIEW, R.ME_SECURITY.PASSWORD, R.ME_SECURITY.SESSIONS, R.ME_SECURITY.LOGIN_HISTORY],
    actionIds: ["view-my-security", "change-my-password"],
    access: { mode: "authenticated", permissions: [] },
    owner: OWNER,
    reviewedAt: REVIEWED_AT,
    risk: "medium",
    status: "draft",
  },
  {
    id: "platform.requirements-library",
    slug: "find-and-download-requirements-documents",
    title: "Find and download requirements documents",
    summary: "Browse the MRD and the module FRDs, download the current version, and pull up an earlier revision.",
    category: "platform-health-and-settings",
    tags: ["documents", "requirements", "MRD", "FRD", "specifications"],
    aliases: [
      "requirements document", "module requirements", "functional requirements",
      "product specs", "where are the docs", "download FRD", "MRD",
    ],
    audiences: ["platform-administrator", "support-and-operations"],
    routes: [R.DOCUMENTS.INDEX],
    actionIds: ["view-requirements-documents"],
    access: { mode: "any", permissions: [P.VIEW_REQUIREMENTS_DOCS] },
    primaryRoute: R.DOCUMENTS.INDEX,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "find-a-document", title: "Find a document" },
      { id: "download-a-document", title: "Download a document" },
      { id: "read-an-earlier-version", title: "Read an earlier version" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["troubleshooting.permission-denied"],
    estimatedMinutes: 3,
    owner: OWNER,
    reviewedAt: DOCS_REVIEWED_AT,
    // Read-only: the screen browses and downloads, and writes nothing. No
    // walkthrough - there is no consequential action to guide anyone through.
    risk: "low",
    status: "published",
    article: () => import("./content/platform-health-and-settings/requirements-library"),
  },
  {
    id: "troubleshooting.permission-denied",
    slug: "resolve-permission-denied-or-missing-navigation",
    title: "Resolve permission denied or missing navigation",
    summary: "Check account context, role assignment, permissions, and escalation details.",
    category: "troubleshooting",
    tags: ["permission denied", "forbidden", "missing menu", "access"],
    aliases: ["403", "cannot see page", "menu missing", "not allowed"],
    audiences: ["all-users", "platform-administrator", "support-and-operations"],
    routes: [R.SUPPORT.INDEX],
    actionIds: ["view-support", "raise-support-ticket"],
    access: { mode: "authenticated", permissions: [] },
    owner: OWNER,
    reviewedAt: REVIEWED_AT,
    risk: "medium",
    status: "draft",
  },
] as const satisfies readonly GuideRecord[];
