import { GuideCallout, GuideChecklist, GuideSection, GuideStep, GuideSteps } from "../../article-components";

export default function AddAndGovernVendorArticle() {
  return <div className="space-y-10">
    <GuideSection id="before-you-start" title="Before you start"><p>Confirm the entity, legal supplier name, category, payment terms, payable and expense accounts, approved contacts, tax details, independently verified bank details, KYC decision, and risk owner.</p><GuideCallout tone="warning" title="Separate vendor access from sensitive access">Vendor view access does not reveal contact, tax, or bank fields. Sensitive vendor access is deliberate, and the backend removes those fields for everyone else.</GuideCallout></GuideSection>
    <GuideSection id="create-the-vendor" title="Create the vendor master"><GuideSteps><GuideStep title="Choose the entity">The vendor belongs to the active ledger entity. Check it before entering any details.</GuideStep><GuideStep title="Set purchasing defaults">Add the category, payable account, expense account, withholding tax, and payment terms that should seed new documents.</GuideStep><GuideStep title="Create the record">New vendors start with KYC pending. Creation does not make an unverified supplier eligible for every purchasing or payment action.</GuideStep></GuideSteps></GuideSection>
    <GuideSection id="protect-sensitive-details" title="Protect contact, tax, and bank details"><p>Add only approved contacts and choose who should receive RFQs or purchase orders. Mark one primary contact. Verify bank details through an independent channel before saving and again before the first payment. Do not copy full account numbers into screenshots, exports, or support tickets.</p></GuideSection>
    <GuideSection id="set-purchasing-governance" title="Set KYC, risk, hold, and active status"><p>Vendor management access controls KYC, risk, and hold status. Inactive, on-hold, and KYC-rejected vendors cannot receive new purchasing commitments. Payments additionally require KYC verified. Record the real decision instead of changing a status only to pass a transaction.</p></GuideSection>
    <GuideSection id="review-commercial-history" title="Review history and performance"><p>Open a vendor to review profile, contacts, masked bank data, contracts, purchase orders, invoices, and performance. Financial insights require procurement report access. Compare the vendor master with real purchasing evidence before changing commercial defaults.</p></GuideSection>
    <GuideSection id="change-or-retire-a-vendor" title="Change or retire a vendor safely"><p>Editing a vendor changes future defaults and eligibility, not historical documents. Use On hold for a temporary purchasing stop and Active off when the supplier is retired. Preserve the original record so past RFQs, orders, invoices, payments, and audit activity remain traceable.</p></GuideSection>
    <GuideSection id="common-problems" title="Common problems"><ul className="list-disc space-y-2 pl-5"><li>Contact or bank fields are missing: request sensitive vendor access only when the job requires it.</li><li>Vendor cannot be invited: confirm Active, not On hold, and KYC is not Rejected.</li><li>Vendor cannot be paid: confirm KYC is Verified and the payable and bank details are valid.</li><li>History looks incomplete: contract, purchase-order, invoice, and report access are checked separately.</li></ul></GuideSection>
    <GuideSection id="completion-check" title="Completion check"><GuideChecklist items={["Entity and supplier identity are correct", "Accounting and payment defaults were reviewed", "Contacts and bank details were independently verified", "KYC, risk, hold, and active states match the approved decision", "Historical records remain under the original vendor"]} /></GuideSection>
  </div>;
}
