import { GuideCallout, GuideChecklist, GuideSection, GuideStep, GuideSteps } from "../../article-components";

export default function CompleteProcureToPayArticle() {
  return <div className="space-y-10">
    <GuideSection id="before-you-start" title="Before you start"><p>Confirm the active entity, approved need, requester, cost centre, budget evidence, item or service specification, delivery date, eligible vendor, receiving evidence, vendor invoice, approval route, payment account, and posting periods.</p><GuideCallout tone="warning" title="Each stage has a different purpose">A requisition requests spend, a purchase order commits it, a goods receipt records accepted delivery, a vendor invoice creates the payable, and a vendor payment settles it. Do not skip or duplicate a stage to force the cycle forward.</GuideCallout></GuideSection>
    <GuideSection id="raise-and-approve-the-need" title="Raise and approve the requisition"><GuideSteps><GuideStep title="Describe the business need">Enter a clear title, requester, request and needed-by dates, cost centre, purpose, and supported lines. Use catalogue defaults only after checking quantity, price estimate, tax, and accounting context.</GuideStep><GuideStep title="Check budget evidence">Review the live availability warning against the intended cost centre and period. A warning informs the approval decision; it does not replace the approved budget or authority.</GuideStep><GuideStep title="Submit once the draft is complete">Submission freezes the version routed through workflow. If no eligible approver resolves, use the workflow owner to correct routing rather than creating a duplicate request.</GuideStep></GuideSteps><GuideCallout tone="info" title="When an approver sends a document back">This applies to requisitions, purchase orders, vendor invoices, vendor payments and vendor credit notes alike. The person who sent it for approval sees <strong>Sent back to you</strong> in its drawer, with the approver&rsquo;s reason. <strong>Edit</strong> corrects it in place, and <strong>Resume</strong> sends the corrected version back into the same approval, where the approvers see the corrected version. Nobody else gets these buttons, and while the document is with its approvers nobody can change it. Meanwhile a badge reading <strong>Sent back</strong>, in its own colour, shows on its row and in its drawer: the status badge on a requisition or purchase order, and the approval badge on invoices, payments and vendor credit notes. A document still with its approver keeps its usual word. To find them, requisitions, purchase orders, vendor invoices and vendor credit notes have a <strong>Sent back</strong> tab, and vendor payments a filter offering <strong>All payments</strong> or <strong>Sent back</strong>. A document sent back is listed only there: not under <strong>Pending Approval</strong> on requisitions and purchase orders, nor under <strong>Awaiting approval</strong> on vendor invoices.</GuideCallout><GuideCallout tone="info" title="Exporting a tab">On requisitions, purchase orders and vendor invoices, <strong>Export</strong> follows the tab you are on, <strong>Sent back</strong> and <strong>Partly received</strong> included, so the file holds what the tab lists.</GuideCallout></GuideSection>
    <GuideSection id="commit-with-a-purchase-order" title="Commit with a purchase order"><p>Create the order from an approved requisition in the same entity. Confirm the purchase-eligible vendor, order and expected dates, delivery address, payment terms, contract where applicable, quantities, prices, tax, and total before submitting for approval. While its approvers have it, the order reads <strong>Pending Approval</strong>, on its row and in its drawer, and the <strong>Pending Approval</strong> tab lists it, never Draft. Email the vendor only after the approved order and recipient preview are correct.</p></GuideSection>
    <GuideSection id="record-the-delivery" title="Record accepted and rejected delivery"><p>Select the open purchase order and record the actual received date, delivery reference, accepted quantity, rejected quantity, inspection result, and quality notes. Partial delivery remains partial. Post only the accepted evidence; the posting updates fulfilment, inventory where tracked, and GR/IR clearing (goods received, not yet billed).</p><GuideCallout tone="danger" title="Posting a receipt changes stock and the ledger">The walkthrough never creates or posts a goods receipt. Verify the physical delivery, correct store, open period, and line quantities before confirming.</GuideCallout></GuideSection>
    <GuideSection id="match-and-post-the-invoice" title="Match, approve, and post the vendor invoice"><GuideSteps><GuideStep title="Capture the supplier document">Use the exact vendor invoice number, invoice and due dates, vendor, linked purchase order where one exists, supported lines, tax, and attachment. Investigate duplicate-number warnings before saving.</GuideStep><GuideStep title="Run the three-way match">Compare cumulative ordered, accepted, and invoiced quantities plus unit price. Quantity, missing-receipt, and disabled non-PO outcomes can block posting. Price variance posts to the configured variance account when allowed.</GuideStep><GuideStep title="Approve before posting">Submission and approval are separate from posting. A blocking variance needs correction at its source or the dedicated audited override permission. Posting creates Accounts Payable and revalidates approval and match evidence under lock.</GuideStep></GuideSteps></GuideSection>
    <GuideSection id="approve-and-post-payment" title="Approve and post the vendor payment"><p>Select the verified, active, eligible vendor and approved posted invoices. Check allocations, gross amount, withholding tax, net cash, bank or payment account, value date, method, reference, and receipt evidence. <strong>Withholding tax kept back</strong> is worked out from the <strong>Withholding tax code</strong> on the bills, before VAT; a figure typed over it reads <em>Entered by hand</em>, and <strong>Work it out again</strong> puts the worked-out figure back, on a new payment or when editing one. Submit for independent approval, then post once. Apply a genuine advance only to later bills for the same vendor. Reverse only with authority and evidence because it restores invoice balances.</p></GuideSection>
    <GuideSection id="correct-a-supplier-bill" title="Correct a posted supplier bill">
      <p>Open a posted bill on <strong>Vendor Invoices</strong>. There are two ways to correct it:</p>
      <GuideSteps>
        <GuideStep title="Void a bill nothing has touched">Select <strong>Void</strong>, then <strong>Void bill</strong>. It reverses the bill&rsquo;s posting and gives the purchase order back its billed quantities; the bill stays in history as voided. It needs the vendor invoice void key. Once anything has been paid against the bill or a credit note has settled part of it, the dialog says it cannot be voided and offers <strong>Raise a credit note</strong> instead.</GuideStep>
        <GuideStep title="Raise a credit note">Select <strong>Credit note</strong> and choose what to credit: <strong>Whole bill</strong> (everything it has left, for a bill keyed in error or sent twice), <strong>By amount</strong> (a price allowance spread across the bill; the goods stay received), or <strong>By line</strong> (a quantity, which also comes off the order&rsquo;s billed quantity, or a net amount per line). Give the date, the supplier&rsquo;s reference and a reason, then <strong>Save draft</strong>.</GuideStep>
        <GuideStep title="Approve and post it">Select <strong>Submit for approval</strong>; approvers decide it under Workflow, Approvals. Once approved, select <strong>Post credit note</strong>. It takes the bill&rsquo;s vendor and branch.</GuideStep>
      </GuideSteps>
      <p>On a bill already paid, the credit stays with the vendor for the same branch&rsquo;s later bills: use <strong>Apply credit</strong>, either <strong>Oldest bills first</strong> or <strong>Choose bills</strong>. The <strong>Credit notes</strong> view on Vendor Invoices lists every credit note with what is left of it. Voiding a credit note reverses it and every bill it was applied to.</p>
      <GuideCallout tone="info" title="An example">
        Lekki is billed ₦250,000 for 50 reams of paper and pays it. Ten reams arrive damaged. Ngozi Ibe raises a credit note by line for 10 reams, ₦50,000, with the reason &ldquo;10 reams returned damaged&rdquo;. Once approved and posted, the ₦50,000 waits as Lekki&rsquo;s credit with the supplier and settles Lekki&rsquo;s next bill from them.
      </GuideCallout>
    </GuideSection>
    <GuideSection id="return-goods" title="Return goods to the supplier">
      <p>On a posted goods receipt, select <strong>Return</strong>. Choose quantities line by line (each says how much can go back), or <strong>Everything still on it</strong>, then the return date and why the goods are going back, and select <strong>Return goods</strong>. Stock falls by what goes back at the receipt&rsquo;s cost, and the goods-received liability reverses with it. It needs the goods receipt reverse key.</p>
      <p>Goods already billed must be credited on the bill first, with a credit note; a return that reaches billed goods is refused. A return is never voided: if goods went back in error, or have come back, receive them again against the order.</p>
    </GuideSection>
    <GuideSection id="opening-supplier-bills" title="Bring in supplier bills unpaid before go-live">
      <p>On <strong>Vendor Invoices</strong>, select <strong>Opening bills</strong>. It needs the opening bill import key. Download the <strong>Template</strong> and fill one row per unpaid bill: <strong>vendor</strong>, <strong>invoice_date</strong>, <strong>due_date</strong>, <strong>vendor_reference</strong>, <strong>amount</strong> (naira), <strong>branch</strong> and <strong>narration</strong>, at most 500 bills per file. The branch column is required where the school runs several branches and you are not tied to one.</p>
      <p>Choose the CSV file, or paste the rows, and select <strong>Import</strong>. Each bill posts to Accounts Payable against retained earnings with no approval. One bad row refuses the whole file, and bills dated on or after the day the books went live are refused; raise those as ordinary bills.</p>
    </GuideSection>
    <GuideSection id="reconcile-the-cycle" title="Reconcile the complete cycle"><GuideChecklist items={["Requisition approval supports the purchase order commitment", "Order quantities and terms agree with the vendor instruction", "Accepted receipt quantities agree with physical evidence", "Invoice match and posting agree with the PO and receipt", "Payment allocation and withholding agree with the approved payable", "Document statuses, journals, attachments, and activity form one audit trail"]} /></GuideSection>
    <GuideSection id="common-problems" title="Common problems"><ul className="list-disc space-y-2 pl-5"><li>Approved requisition is missing from the PO picker: confirm entity, approval state, remaining convertible lines, and your access.</li><li>Receipt cannot post: check the PO status, remaining quantity, receipt policy, location, date, and open period.</li><li>Invoice is blocked: open 3-Way Match and correct the earliest missing or excess source evidence.</li><li>Payment cannot post: confirm approval, vendor eligibility, invoice balance, payment account mapping, and posting date.</li><li>Edit and Resume are missing on a document sent back: only the person who sent it for approval gets them, and Edit also needs the edit permission for that kind of document.</li><li>Void opens a dialog saying the bill cannot be voided: something was paid or credited against it. Raise a credit note instead.</li><li>A goods return is refused: the goods were already billed. Credit them on the bill first.</li><li>Opening bills refuses the file: read the line numbers it names, fix them, and import the whole file again.</li><li>Totals disagree: stop new documents and reconcile requisition, PO, receipt, invoice, payment, and journals in order.</li></ul></GuideSection>
    <GuideSection id="completion-check" title="Completion check"><GuideChecklist items={["The approved need became one supported commitment", "Accepted delivery and rejected quantity are recorded accurately", "The payable is matched, approved, and posted once", "Cash settlement is approved, posted, and allocated correctly", "Remaining order, GR/IR (goods received, not yet billed), AP (what is owed to suppliers), advance, and stock balances are explained"]} /></GuideSection>
  </div>;
}
