import { GuideCallout, GuideChecklist, GuideSection, GuideStep, GuideSteps } from "../../article-components";

export default function CompleteProcureToPayArticle() {
  return <div className="space-y-10">
    <GuideSection id="before-you-start" title="Before you start"><p>Confirm the active entity, approved need, requester, cost centre, budget evidence, item or service specification, delivery date, eligible vendor, receiving evidence, vendor invoice, approval route, payment account, and posting periods.</p><GuideCallout tone="warning" title="Each stage has a different purpose">A requisition requests spend, a purchase order commits it, a goods receipt records accepted delivery, a vendor invoice creates the payable, and a vendor payment settles it. Do not skip or duplicate a stage to force the cycle forward.</GuideCallout></GuideSection>
    <GuideSection id="raise-and-approve-the-need" title="Raise and approve the requisition"><GuideSteps><GuideStep title="Describe the business need">Enter a clear title, requester, request and needed-by dates, cost centre, purpose, and supported lines. Use catalogue defaults only after checking quantity, price estimate, tax, and accounting context.</GuideStep><GuideStep title="Check budget evidence">Review the live availability warning against the intended cost centre and period. A warning informs the approval decision; it does not replace the approved budget or authority.</GuideStep><GuideStep title="Submit once the draft is complete">Submission freezes the version routed through workflow. If no eligible approver resolves, use the workflow owner to correct routing rather than creating a duplicate request.</GuideStep></GuideSteps></GuideSection>
    <GuideSection id="commit-with-a-purchase-order" title="Commit with a purchase order"><p>Create the order from an approved requisition in the same entity. Confirm the purchase-eligible vendor, order and expected dates, delivery address, payment terms, contract where applicable, quantities, prices, tax, and total before submitting for approval. Email the vendor only after the approved order and recipient preview are correct.</p></GuideSection>
    <GuideSection id="record-the-delivery" title="Record accepted and rejected delivery"><p>Select the open purchase order and record the actual received date, delivery reference, accepted quantity, rejected quantity, inspection result, and quality notes. Partial delivery remains partial. Post only the accepted evidence; the posting updates fulfilment, inventory where tracked, and GR/IR control.</p><GuideCallout tone="danger" title="Posting a receipt changes stock and the ledger">The walkthrough never creates or posts a goods receipt. Verify the physical delivery, correct store, open period, and line quantities before confirming.</GuideCallout></GuideSection>
    <GuideSection id="match-and-post-the-invoice" title="Match, approve, and post the vendor invoice"><GuideSteps><GuideStep title="Capture the supplier document">Use the exact vendor invoice number, invoice and due dates, vendor, linked purchase order where one exists, supported lines, tax, and attachment. Investigate duplicate-number warnings before saving.</GuideStep><GuideStep title="Run the three-way match">Compare cumulative ordered, accepted, and invoiced quantities plus unit price. Quantity, missing-receipt, and disabled non-PO outcomes can block posting. Price variance posts to the configured variance account when allowed.</GuideStep><GuideStep title="Approve before posting">Submission and approval are separate from posting. A blocking variance needs correction at its source or the dedicated audited override permission. Posting creates Accounts Payable and revalidates approval and match evidence under lock.</GuideStep></GuideSteps></GuideSection>
    <GuideSection id="approve-and-post-payment" title="Approve and post the vendor payment"><p>Select the verified, active, eligible vendor and approved posted invoices. Check allocations, gross amount, withholding tax, net cash, bank or payment account, value date, method, reference, and receipt evidence. Submit for independent approval, then post once. Apply a genuine advance only to later bills for the same vendor. Reverse only with authority and evidence because it restores invoice balances.</p></GuideSection>
    <GuideSection id="reconcile-the-cycle" title="Reconcile the complete cycle"><GuideChecklist items={["Requisition approval supports the purchase order commitment", "Order quantities and terms agree with the vendor instruction", "Accepted receipt quantities agree with physical evidence", "Invoice match and posting agree with the PO and receipt", "Payment allocation and withholding agree with the approved payable", "Document statuses, journals, attachments, and activity form one audit trail"]} /></GuideSection>
    <GuideSection id="common-problems" title="Common problems"><ul className="list-disc space-y-2 pl-5"><li>Approved requisition is missing from the PO picker: confirm entity, approval state, remaining convertible lines, and your access.</li><li>Receipt cannot post: check the PO status, remaining quantity, receipt policy, location, date, and open period.</li><li>Invoice is blocked: open 3-Way Match and correct the earliest missing or excess source evidence.</li><li>Payment cannot post: confirm approval, vendor eligibility, invoice balance, payment account mapping, and posting date.</li><li>Totals disagree: stop new documents and reconcile requisition, PO, receipt, invoice, payment, and journals in order.</li></ul></GuideSection>
    <GuideSection id="completion-check" title="Completion check"><GuideChecklist items={["The approved need became one supported commitment", "Accepted delivery and rejected quantity are recorded accurately", "The payable is matched, approved, and posted once", "Cash settlement is approved, posted, and allocated correctly", "Remaining PO, GR/IR, AP, advance, and stock balances are explained"]} /></GuideSection>
  </div>;
}
