import { GuideCallout, GuideChecklist, GuideSection, GuideStep, GuideSteps } from "../../article-components";

export default function ConfigureSettingsArticle() {
  return <div className="space-y-10">
    <GuideSection id="before-you-start" title="Before you start"><p>Confirm the active entity, approved purchasing policy, vendor eligibility standard, lead times, receiving rule, sourcing minimums, invoice tolerances, Finance account mappings, approval templates, change owner, effective date, and rollback decision.</p><GuideCallout tone="danger" title="Settings change future control decisions">A saved policy can immediately change which vendors, receipts, RFQs, awards, matches, and new documents are allowed. Review the affected consumers and audit history before saving.</GuideCallout></GuideSection>
    <GuideSection id="confirm-scope-and-inheritance" title="Confirm entity scope and inherited controls"><p>Start at Overview and verify the active entity and reporting currency. Procurement shares entity isolation and fiscal posting windows with Finance. Accounting mappings are Finance-owned. Approval routing is shared with Workflow. A Procurement setting must not be used to work around either boundary.</p></GuideSection>
    <GuideSection id="set-purchasing-and-lifecycle" title="Set purchasing and lifecycle defaults"><GuideSteps><GuideStep title="General defaults">Choose the payment terms copied to new vendors and contracts and the delivery address offered on new purchase orders. Buyers can still enter supported document-specific values.</GuideStep><GuideStep title="Purchasing policy">Set whether buyers may use pending-KYC vendors, default requisition lead days, and whether receipts require a purchase order. Approved requisition and eligible-vendor payment controls remain enforced.</GuideStep><GuideStep title="Sourcing and lifecycle">Set default RFQ response days, closing-soon horizon, and contract renewal notice. Explicit record dates win, and existing RFQs and contracts keep their stored terms.</GuideStep></GuideSteps></GuideSection>
    <GuideSection id="set-competition-and-matching" title="Set competition and matching policy"><p>Set minimum invited vendors and submitted quotations between 1 and 50. Raising the threshold affects the next issue or award decision. A below-minimum exception still needs the separate critical permission and a written audited reason. Set quantity and price tolerance between 0 and 100 percent and decide whether non-PO invoices are allowed. Blocking outcomes still need source correction or the dedicated audited override.</p></GuideSection>
    <GuideSection id="check-accounting-and-approvals" title="Check accounting mappings and approval routes"><p>Verify Accounts Payable, GR/IR, withholding tax, inventory asset, inventory adjustment, and purchase price variance mappings in Finance Settings. Review workflow templates for requisitions, purchase orders, vendor invoices, and vendor payments, including branch, tenant, platform scope, senior thresholds, eligibility, and no-approver handling.</p></GuideSection>
    <GuideSection id="understand-when-changes-apply" title="Understand when changes apply"><GuideChecklist items={["The active entity and approved effective date are explicit", "Consumer hints identify the workflows affected by each value", "Existing documents that keep stored values are identified", "Future issue, award, match, receipt, and create decisions are understood", "Audit history records only the intended changed values", "A rollback value and owner are known before save"]} /></GuideSection>
    <GuideSection id="common-problems" title="Common problems"><ul className="list-disc space-y-2 pl-5"><li>Settings are read-only: you may hold view permission without update permission.</li><li>An account shows Missing: repair the Finance-owned mapping before posting.</li><li>An RFQ or award is still blocked: settings do not grant the separate competition override permission.</li><li>An old document did not change: stored dates and terms are intentionally preserved.</li><li>A new invoice is blocked: rerun the match under the current tolerance and non-PO policy, then correct the source evidence.</li></ul></GuideSection>
    <GuideSection id="completion-check" title="Completion check"><GuideChecklist items={["Entity, Finance inheritance, and workflow ownership are clear", "Purchasing, lifecycle, competition, and matching values match policy", "Permissions remain separate from configuration values", "Existing and future document behaviour is understood", "Audit history and rollback ownership are available"]} /></GuideSection>
  </div>;
}
