import { GuideCallout, GuideChecklist, GuideSection, GuideStep, GuideSteps } from "../../article-components";

export default function ManageCategoriesAndCatalogueArticle() {
  return <div className="space-y-10">
    <GuideSection id="before-you-start" title="Before you start"><p>Confirm the entity, approved category structure, item names and units, optional external codes, purchasing owners, preferred vendors, standard prices, lead times, expense accounts, and purchase-tax defaults.</p><GuideCallout tone="info" title="Defaults are starting points">Category and catalogue values seed new purchasing lines. They do not replace a quotation, approval, invoice match, or accounting review.</GuideCallout></GuideSection>
    <GuideSection id="build-the-category-tree" title="Build the category hierarchy"><GuideSteps><GuideStep title="Start with broad roots">Create stable spend families that users can recognize.</GuideStep><GuideStep title="Add only useful children">The hierarchy supports three levels. Avoid duplicate branches with slightly different names.</GuideStep><GuideStep title="Keep codes stable">A clear code and name make search, reporting, and future integrations easier to reconcile.</GuideStep></GuideSteps></GuideSection>
    <GuideSection id="set-category-defaults" title="Set category accounting defaults"><p>Choose the default expense account and withholding tax only when they are valid for most purchases in that category. The category must remain active to be assigned to new vendors. Spend insights use posted vendor invoices and require procurement report access.</p></GuideSection>
    <GuideSection id="create-a-catalogue-item" title="Create a catalogue item"><p>Open Catalog, choose New Item, then enter the item name, unit of measure, optional SKU, description, category, preferred vendor, standard price, lead time, expense account, and purchase tax. Use a consistent unit such as each, box, litre, or hour so quantities remain comparable.</p></GuideSection>
    <GuideSection id="understand-default-precedence" title="Understand default precedence"><p>An item expense account overrides its active category default. The item tax and preferred vendor seed only new lines and remain overridable. A standard price is an indicative reference, not a firm vendor bid.</p></GuideSection>
    <GuideSection id="review-pricing-and-history" title="Review pricing and purchase history"><p>Open an item to compare its master reference with observed approved purchase-order pricing and linked history. Investigate material differences instead of silently changing the standard price to match one unusual order.</p></GuideSection>
    <GuideSection id="retire-master-data" title="Retire master data without changing history"><p>Mark unused categories or items inactive. Historical requisitions, orders, receipts, invoices, stock movements, and journals keep their recorded values. Rename or remap a live item only after checking reports and downstream users.</p></GuideSection>
    <GuideSection id="common-problems" title="Common problems"><ul className="list-disc space-y-2 pl-5"><li>A parent category is unavailable: confirm it is active and the hierarchy would stay within three levels.</li><li>A preferred vendor is unavailable: confirm that supplier is purchase-eligible.</li><li>An expense or tax default is unavailable: use an active postable expense account and active purchase tax code.</li><li>Pricing or history is restricted: procurement report access is separate from catalogue view access.</li></ul></GuideSection>
    <GuideSection id="completion-check" title="Completion check"><GuideChecklist items={["Category names and codes are distinct", "Hierarchy stays within three useful levels", "Item unit and purchasing defaults are correct", "Accounting defaults follow the intended precedence", "Unused master data was made inactive instead of deleted or repurposed"]} /></GuideSection>
  </div>;
}
