import { GuideCallout, GuideChecklist, GuideSection, GuideStep, GuideSteps } from "../../article-components";

export default function ManageContractLifecycleArticle() {
  return <div className="space-y-10">
    <GuideSection id="before-you-start" title="Before you start"><p>Confirm the entity, eligible vendor, approved signed agreement, contract type, start and end dates, value, payment terms, renewal notice, auto-renew decision, milestones, owner, and termination authority.</p><GuideCallout tone="warning" title="The register is not the signed agreement">Console tracks the commercial controls and activity. Retain the authoritative agreement and approval evidence in the approved records system.</GuideCallout></GuideSection>
    <GuideSection id="create-the-draft" title="Create the contract draft"><GuideSteps><GuideStep title="Choose the vendor">The vendor must remain purchase-eligible. Check for an existing active contract of the same type.</GuideStep><GuideStep title="Record the commercial term">Enter dates, value, payment terms, renewal notice, auto-renew decision, and concise notes.</GuideStep><GuideStep title="Add measurable milestones">Use clear deliverables, due dates, and amounts where milestone monitoring is part of the agreement.</GuideStep></GuideSteps></GuideSection>
    <GuideSection id="activate-the-contract" title="Activate the approved agreement"><p>Activation requires valid start and end dates and an eligible vendor. Save a draft while approval or evidence is incomplete. Create &amp; activate, or Activate from the detail view, only after the registered term agrees with the signed document.</p></GuideSection>
    <GuideSection id="monitor-milestones" title="Monitor milestones and purchase-order use"><p>Use Milestones to track agreed delivery events. Complete a milestone only when the evidence confirms delivery. Linked purchase orders are explicit call-offs; In-term purchase orders are only vendor and date associations and should not be mistaken for contractual links.</p></GuideSection>
    <GuideSection id="edit-active-terms" title="Edit active terms deliberately"><p>Active and expired contracts can be edited under contract update access. New milestones are appended rather than replacing old ones. Reconcile any date, value, or renewal change with the approved amendment and affected purchase orders.</p></GuideSection>
    <GuideSection id="renew-or-terminate" title="Renew or terminate the agreement"><p>Renew creates a successor contract and marks the current one renewed. Choose the new dates and value, and copy pending milestones only when the renewal truly carries them forward. Terminate ends the agreement early and cannot be undone, so record the reason and confirm downstream purchasing has stopped.</p></GuideSection>
    <GuideSection id="common-problems" title="Common problems"><ul className="list-disc space-y-2 pl-5"><li>Contract cannot activate: check both dates, their order, and vendor eligibility.</li><li>Duplicate warning appears: review the existing active contract; multiple contracts are allowed, but overlap must be intentional.</li><li>Purchase order shows In-term: it shares the vendor and dates but has no explicit contract link.</li><li>Renewal is unavailable: confirm contract status and renewal permission.</li></ul></GuideSection>
    <GuideSection id="completion-check" title="Completion check"><GuideChecklist items={["Register agrees with the approved signed agreement", "Vendor and term are eligible for activation", "Milestones are measurable and evidence-backed", "Linked and merely in-term purchase orders are distinguished", "Renewal or termination preserves a clear successor and audit trail"]} /></GuideSection>
  </div>;
}
