import { GuideCallout, GuideChecklist, GuideSection, GuideStep, GuideSteps } from "../../article-components";

export default function ManageStockAndMovementsArticle() {
  return <div className="space-y-10">
    <GuideSection id="before-you-start" title="Before you start"><p>Confirm the entity, catalogue or SKU identity, unit of measure, inventory and expense accounts, reorder threshold, physical store, counted quantity, movement date, evidence, and authority to issue or adjust stock.</p><GuideCallout tone="warning" title="Stock is held by store">With more than one active location, every receipt, issue, and adjustment must identify the physical store. Entity totals cannot be used to issue stock that is standing somewhere else.</GuideCallout></GuideSection>
    <GuideSection id="set-up-stock-and-locations" title="Set up stock items and locations"><GuideSteps><GuideStep title="Register the item">Use a durable SKU when available, a clear name and unit, a postable inventory asset account, optional issue expense account, and realistic reorder level and quantity.</GuideStep><GuideStep title="Create real stores">Create a location for each controlled place stock is held. Link a branch when useful, keep exactly one active default, and do not deactivate a store that still holds value.</GuideStep><GuideStep title="Keep history stable">Editing a name, account, or threshold does not change existing movements. Item and location codes remain the audit identity.</GuideStep></GuideSteps></GuideSection>
    <GuideSection id="receive-stock" title="Receive stock through purchasing"><p>Use Goods Receipts against the approved purchase order. Select the actual store when the entity has multiple locations. Accepted tracked quantities create the receipt movement and update that store's weighted-average cost. Rejected quantities do not become available stock.</p></GuideSection>
    <GuideSection id="issue-stock" title="Issue stock at weighted-average cost"><p>Open the exact item, select Issue, choose the source store, enter a supported quantity no greater than that store's balance, use an open movement date, confirm the expense account, choose who it was issued to (an optional cost centre such as the kitchen or a department), and add a meaningful reference and narration. The issue debits expense and credits inventory using the current average cost at that store; the cost centre is kept on the movement and on the expense line, so the issue shows under that department on the Procurement dashboard and on spending by cost centre.</p><GuideCallout tone="danger" title="Issue posts a real journal">An issue cannot be undone by editing the stock item. If evidence was wrong, stop and follow the approved correction process instead of hiding it with an unsupported adjustment.</GuideCallout></GuideSection>
    <GuideSection id="transfer-stock" title="Transfer stock to another store">
      <p>Open the item and select <strong>Transfer</strong>. It needs the key to issue stock, and it appears only when there is more than one store or more than one branch.</p>
      <GuideSteps>
        <GuideStep title="Choose where it goes">Pick the <strong>From store</strong>, then the receiving store under <strong>To store</strong>, or type <strong>the code of a store at another branch</strong> (for example LEK-MAIN).</GuideStep>
        <GuideStep title="Enter the quantity">The hint shows how much is available in the sending store. Add the movement date, a reference and a narration, then select <strong>Transfer</strong>.</GuideStep>
      </GuideSteps>
      <p>Stock moves at the sending store&rsquo;s moving-average cost. Between two stores of one branch nothing is booked. Between two branches, the receiving branch owes the sending branch the value moved, through the inter-branch account, and it shows on Inter-branch Balances.</p>
      <GuideCallout tone="info" title="An example">
        Ikeja sends 50 exercise books at ₦300 each to Lekki&rsquo;s store LEK-MAIN. Ikeja&rsquo;s stock value falls by ₦15,000, Lekki&rsquo;s rises by ₦15,000, and Lekki owes Ikeja ₦15,000. Moving the same books between two Ikeja stores would book nothing.
      </GuideCallout>
      <p>A transfer is never voided. To reverse one, transfer the goods back the other way.</p>
    </GuideSection>
    <GuideSection id="adjust-a-count" title="Adjust a verified stock count"><p>Adjust only after a controlled physical count identifies a real difference. Choose the store and direction. A decrease relieves inventory at the current average. An increase uses the entered unit cost when the store is empty, or the current average when available. Confirm the adjustment account and preserve count evidence.</p></GuideSection>
    <GuideSection id="review-movements-and-value" title="Review movements, reorder signals, and value"><p>Use Stock Items for on-hand quantity, reorder status, location breakdown, average cost, and total value. Use Movements as the read-only ledger of receipts, issues, and adjustments, filtered by type and store. Reconcile quantity and value from the first unexpected movement, not by overwriting the item.</p><p>The Procurement dashboard's Stock and receiving tab lists items running low with how many days each will last and a suggested order. Draft a requisition for all creates one draft requisition with a line per low item at its suggested quantity and last known cost, then opens it; nothing is submitted until you review, edit and submit it.</p></GuideSection>
    <GuideSection id="common-problems" title="Common problems"><ul className="list-disc space-y-2 pl-5"><li>Not enough stock here: another store may hold it; select the correct source rather than using the entity total.</li><li>A location cannot deactivate: make another active location default and clear the remaining balance first.</li><li>Issue value is zero: confirm positive stock value and an expense account.</li><li>Increase from zero is disabled: enter the supported unit cost.</li><li>Reorder totals look wrong: check whether a store filter is active and compare its threshold with its own balance.</li><li>Transfer is missing: there is only one store at one branch, or you lack the key to issue stock.</li><li>A store at another branch is not in the To store list: type its code instead.</li></ul></GuideSection>
    <GuideSection id="completion-check" title="Completion check"><GuideChecklist items={["Each item has stable identity, unit, and valid accounts", "Every controlled store exists and one is default", "Receipts use accepted delivery evidence and the correct store", "Issues and adjustments have dates, references, accounts, and authority", "Movement quantity, store balance, valuation, and general ledger agree"]} /></GuideSection>
  </div>;
}
