import { GuideCallout, GuideChecklist, GuideSection, GuideStep, GuideSteps } from "../../article-components";

export default function ReviewAnalyticsArticle() {
  return <div className="space-y-10">
    <GuideSection id="before-you-start" title="Before you start"><p>Confirm the active entity, reporting date or window, fiscal context, source-document permissions, and the question you need the report to answer. Procurement analytics use posted operational records and do not repair them.</p><GuideCallout tone="info" title="A report points to the source">Use the report to find the responsible purchase order, receipt, invoice, payment, vendor, or assessment. Correct approved source data through its own workflow.</GuideCallout></GuideSection>
    <GuideSection id="read-the-overview" title="Read the Procurement overview"><p>The Procurement dashboard shows where things stand today, with a switch at the top (This month, This term, Year to date) that changes spend, spend by category, top vendors and what was paid; a term is read by its dates.</p><GuideSteps><GuideStep title="Purchase to payment">Each stage counts what is open in its own list right now: requisitions not yet ordered, RFQs out, orders not fully received, goods received but not billed, bills to pay, and payments made in the window. Select a stage to open that list.</GuideStep><GuideStep title="Committed vs spent">Compares purchase orders raised with vendor bills posted, month by month through the fiscal year. Point at a month to read both figures.</GuideStep><GuideStep title="Control exceptions">Lists only the checks with something in them: bills whose three-way match failed, bills priced above the order, bills from a vendor on hold, and goods received with no bill after 30 days.</GuideStep><GuideStep title="Spend and suppliers">The second tab sets spend against the approved school budget on the accounts purchasing posts to (a branch reader and books without an approved plan compare with the window before instead), shows how few vendors take most of the spend, on-time delivery and accepted share at receipt, spend on bills without a purchase order against the school's limit, a vendor scorecard with the latest assessment grade, open RFQs, what competition saved against the highest quote, spend by branch, the median days each buying step takes, and the vendor base.</GuideStep><GuideStep title="Stock and receiving">The third tab covers the stores you work in: stock value by store, items below their reorder level or out, days left and suggested orders, expected deliveries and late ones, stock issued to each department, recent movements, stock turns, the share of received lines that came short or rejected, stock adjustments, and goods received that are still waiting for a bill.</GuideStep><GuideStep title="Bills and contracts">Bills falling due are unpaid bills by how late they are; its <strong>Unpaid bills by age</strong> link opens the report of that name. Contracts ending soon shows active contracts ending in the next 90 days and how much has been ordered on each; a reader who sees only some branches sees the contract's worth but not every branch's orders against it.</GuideStep></GuideSteps><GuideCallout tone="info" title="What you see depends on your access">Each card and each pipeline stage appears only when you may open the list behind it, and a branch reader's figures cover their branches. Waiting on your approval is always your own queue.</GuideCallout></GuideSection>
    <GuideSection id="use-ap-aging" title="Use Unpaid bills by age to plan settlement"><p>Open <strong>Unpaid bills by age</strong> under Analytics. The report reads <strong>Unpaid bills by age (AP aging)</strong>: what is owed to suppliers, grouped by how late it is. Choose the As of date, then compare total payable, overdue, due this week, and paid-in-advance balances. Open a vendor to review invoice date, due date, days overdue, bucket, outstanding amount, advance credit, and net payable before planning settlement.</p></GuideSection>
    <GuideSection id="clear-grir" title="Investigate GR/IR differences"><p>Open <strong>Goods not yet billed</strong> under Analytics. The report compares goods received with supplier invoices.</p><GuideSteps><GuideStep title="Received, not invoiced">Find accepted deliveries awaiting a supplier invoice. Confirm the receipt, PO line, vendor, age, and whether the invoice is genuinely outstanding.</GuideStep><GuideStep title="Invoiced, not received">Find billed quantities ahead of accepted delivery. Verify the vendor invoice and physical receipt evidence before posting or overriding anything.</GuideStep><GuideStep title="Explain the control balance">Compare received and invoiced values, open line detail, age, and the <strong>GR/IR clearing</strong> balance. Resolve the first source mismatch rather than journaling the report total away.</GuideStep></GuideSteps></GuideSection>
    <GuideSection id="read-spend" title="Read posted spend without overstating it"><p>Set the date range and compare gross, net, tax, invoice count, category, vendor, and monthly trend. The report includes posted vendor invoices in the window. It is not a requisition, PO commitment, cash-payment, or unposted-invoice report.</p></GuideSection>
    <GuideSection id="review-vendor-performance" title="Review delivery and vendor assessments"><p>Use the same reporting window to compare purchase orders, on-time and late receipts, invoiced and paid values, and average payment days. On-time delivery is computed from posted records. Quality, invoice accuracy, responsiveness, and grade come from the latest recorded assessment, so keep assessment date, evidence, reviewer, and notes clear.</p></GuideSection>
    <GuideSection id="act-on-source-records" title="Act on the source record"><GuideChecklist items={["Open the exact vendor or document behind the report line", "Confirm entity, date range, status, and amount before acting", "Use receipt, invoice, payment, vendor, or workflow permissions at the source", "Preserve evidence for assessments and exceptions", "Rerun the report after the source workflow completes"]} /></GuideSection>
    <GuideSection id="common-problems" title="Common problems"><ul className="list-disc space-y-2 pl-5"><li>No report data: confirm entity, dates, the procurement analytics permission, and whether source documents are posted.</li><li>Spend differs from payments: spend is posted invoice value; payment timing and advances are separate.</li><li>GR/IR (goods received, not yet billed) does not clear: compare cumulative quantities and values at PO-line level.</li><li>Vendor has no score: operational history may exist without a recorded assessment.</li><li>Aging changed after the date moved: bucket and overdue status are calculated as of the selected date.</li></ul></GuideSection>
    <GuideSection id="completion-check" title="Completion check"><GuideChecklist items={["The entity and reporting period answer the intended question", "Every exception is traced to a named source record", "Posted spend, what is owed to suppliers, goods received not yet billed, and payments are kept separate", "Vendor assessments distinguish computed facts from reviewer scores", "Corrected source records are reflected when the report is rerun"]} /></GuideSection>
  </div>;
}
