import { GuideCallout, GuideChecklist, GuideSection, GuideStep, GuideSteps } from "../../article-components";

export default function ReviewAnalyticsArticle() {
  return <div className="space-y-10">
    <GuideSection id="before-you-start" title="Before you start"><p>Confirm the active entity, reporting date or window, fiscal context, source-document permissions, and the question you need the report to answer. Procurement analytics use posted operational records and do not repair them.</p><GuideCallout tone="info" title="A report points to the source">Use the report to find the responsible purchase order, receipt, invoice, payment, vendor, or assessment. Correct approved source data through its own workflow.</GuideCallout></GuideSection>
    <GuideSection id="use-ap-aging" title="Use AP aging to plan settlement"><p>Choose the As of date, then compare total payable, overdue, due this week, and paid-in-advance balances. Open a vendor to review invoice date, due date, days overdue, bucket, outstanding amount, advance credit, and net payable before planning settlement.</p></GuideSection>
    <GuideSection id="clear-grir" title="Investigate GR/IR differences"><GuideSteps><GuideStep title="Received, not invoiced">Find accepted deliveries awaiting a supplier invoice. Confirm the receipt, PO line, vendor, age, and whether the invoice is genuinely outstanding.</GuideStep><GuideStep title="Invoiced, not received">Find billed quantities ahead of accepted delivery. Verify the vendor invoice and physical receipt evidence before posting or overriding anything.</GuideStep><GuideStep title="Explain the control balance">Compare received and invoiced values, open line detail, age, and the GR/IR clearing account. Resolve the first source mismatch rather than journaling the report total away.</GuideStep></GuideSteps></GuideSection>
    <GuideSection id="read-spend" title="Read posted spend without overstating it"><p>Set the date range and compare gross, net, tax, invoice count, category, vendor, and monthly trend. The report includes posted vendor invoices in the window. It is not a requisition, PO commitment, cash-payment, or unposted-invoice report.</p></GuideSection>
    <GuideSection id="review-vendor-performance" title="Review delivery and vendor assessments"><p>Use the same reporting window to compare purchase orders, on-time and late receipts, invoiced and paid values, and average payment days. On-time delivery is computed from posted records. Quality, invoice accuracy, responsiveness, and grade come from the latest recorded assessment, so keep assessment date, evidence, reviewer, and notes clear.</p></GuideSection>
    <GuideSection id="act-on-source-records" title="Act on the source record"><GuideChecklist items={["Open the exact vendor or document behind the report line", "Confirm entity, date range, status, and amount before acting", "Use receipt, invoice, payment, vendor, or workflow permissions at the source", "Preserve evidence for assessments and exceptions", "Rerun the report after the source workflow completes"]} /></GuideSection>
    <GuideSection id="common-problems" title="Common problems"><ul className="list-disc space-y-2 pl-5"><li>No report data: confirm entity, dates, report permission, and whether source documents are posted.</li><li>Spend differs from payments: spend is posted invoice value; payment timing and advances are separate.</li><li>GR/IR does not clear: compare cumulative quantities and values at PO-line level.</li><li>Vendor has no score: operational history may exist without a recorded assessment.</li><li>Aging changed after the date moved: bucket and overdue status are calculated as of the selected date.</li></ul></GuideSection>
    <GuideSection id="completion-check" title="Completion check"><GuideChecklist items={["The entity and reporting period answer the intended question", "Every exception is traced to a named source record", "Posted spend, payable, GR/IR, and payment concepts are kept separate", "Vendor assessments distinguish computed facts from reviewer scores", "Corrected source records are reflected when the report is rerun"]} /></GuideSection>
  </div>;
}
