import { GuideCallout, GuideChecklist, GuideSection, GuideStep, GuideSteps } from "../../article-components";

export default function RunRfqAndAwardArticle() {
  return <div className="space-y-10">
    <GuideSection id="before-you-start" title="Before you start"><p>Confirm the entity, approved requirement or requisition, unpriced specification lines, issue and response dates, budget estimate, eligible vendor shortlist, RFQ contacts, competition policy, evaluation criteria, and award authority.</p><GuideCallout tone="warning" title="Award creates the next purchasing document">Awarding a submitted quotation rejects the competing quotations and raises a draft purchase order from the winning lines. Review the commercial and competition evidence before confirmation.</GuideCallout></GuideSection>
    <GuideSection id="prepare-the-rfq" title="Prepare the RFQ scope"><GuideSteps><GuideStep title="Use an approved requirement">Link a requisition when available, then confirm that each RFQ line still describes the requested need and quantity.</GuideStep><GuideStep title="Keep RFQ lines unpriced">The RFQ asks vendors for prices. Add descriptions, quantities, and optional accounting or tax context, but do not turn the request into a supplier quote.</GuideStep><GuideStep title="Set a workable deadline">The response date cannot be before issue. Allow enough time for every invited vendor to prepare comparable evidence.</GuideStep></GuideSteps></GuideSection>
    <GuideSection id="buy-together" title="Buy together across branches">
      <p>When several branches need the same things, one RFQ can ask vendors to quote for all of them. On <strong>New RFQ</strong>, set <strong>Who is buying</strong> to <strong>Several branches together</strong>. It is offered at books with several branches, to someone who covers the whole school or at least two branches.</p>
      <GuideSteps>
        <GuideStep title="Pick the approved lines">Under <strong>Approved requisition lines to buy together</strong>, tick requisitions, or single lines within them. Each line goes on whole. A line already on an RFQ or a purchase order is not offered, and the lines must come from at least two branches.</GuideStep>
        <GuideStep title="Check what vendors see">The preview shows what vendors are asked to quote, with matching lines merged. Vendors see one RFQ.</GuideStep>
        <GuideStep title="Award as usual">The award raises one purchase order for each branch buying together, so each branch receives, owes and reports its own share.</GuideStep>
      </GuideSteps>
      <GuideCallout tone="info" title="An example">
        Ikeja needs 40 chairs and Lekki 60. Both requisitions are approved. Rotimi Ade raises one shared RFQ for 100 chairs. The winning vendor is awarded, and Ikeja gets a purchase order for 40 chairs and Lekki one for 60.
      </GuideCallout>
      <p>A shared RFQ&rsquo;s lines stay as allocated: they cannot be edited on a draft or amended once issued. To change them, cancel it and raise a new one.</p>
    </GuideSection>
    <GuideSection id="invite-and-issue" title="Invite eligible vendors and issue"><p>Add at least one active, purchase-eligible vendor. Console uses each vendor contact marked to receive RFQs, or the primary vendor email when no dedicated contact exists. Save Draft for review, or Create &amp; Issue only when the specification, recipients, and competition requirement are ready.</p></GuideSection>
    <GuideSection id="manage-live-sourcing" title="Manage invitations, deadlines, and amendments"><p>After issue, track delivery and response status. Resend only when a recipient needs the same invitation. Extend a specific vendor deadline deliberately. Publish an amendment with a clear summary so the previous version and existing submissions remain auditable.</p></GuideSection>
    <GuideSection id="record-firm-quotations" title="Record and submit firm quotations"><p>In Quotations, select the issued RFQ and one of its invited vendors, then enter the vendor reference, dates, lead time, priced lines, tax, notes, and approved attachments. A draft can be corrected. Submit records it as the vendor&apos;s firm offer in contention.</p><p>The invited vendor can also use the emailed link and verification code to respond. The portal shows the RFQ version and the local closing date and time. The vendor enters a quantity offered for each priced line, which may be less than requested; a no-bid line offers zero. Whole quantities display without trailing decimals, while fractional quantities remain available. Images open in a viewer with previous and next controls. A submitted response alerts the authorized buyer in-app.</p></GuideSection>
    <GuideSection id="compare-and-award" title="Compare and award the winning quotation"><p>Compare all submitted bids for the same RFQ. Open a quotation, select Evidence, and use View image under Attachments to inspect the vendor&apos;s images in a viewer with Previous and Next controls. Review price, tax, total, lead time, expiry, specification fit, and non-price criteria. If competition is below the configured minimum, only an authorized override with a truthful reason may proceed.</p></GuideSection>
    <GuideSection id="close-or-cancel" title="Close or cancel without an award"><p>Close finishes an issued RFQ without an award and rejects remaining quotations. Cancel abandons a draft or issued RFQ and cannot be undone. Use the action that matches the actual sourcing decision and preserve its explanation.</p></GuideSection>
    <GuideSection id="common-problems" title="Common problems"><ul className="list-disc space-y-2 pl-5"><li>RFQ cannot issue: add at least one valid line and invited eligible vendor.</li><li>Vendor is missing: check active, hold, KYC, and RFQ-contact setup.</li><li>Quotation vendor is unavailable: choose the RFQ first; only invited vendors without an existing quote are offered.</li><li>Several branches together is not offered: the books run one branch, or you cover only one branch.</li><li>A requisition line is missing from the picker: it is not approved, it is already on an RFQ or purchase order, or it has no branch.</li><li>A shared RFQ&rsquo;s lines cannot be edited: cancel it and raise a new one.</li><li>Award is blocked: confirm the quotation is submitted, unexpired, not already awarded, and competition rules are satisfied.</li></ul></GuideSection>
    <GuideSection id="completion-check" title="Completion check"><GuideChecklist items={["Requirement, dates, and unpriced lines are correct", "Invited vendors and recipient contacts were verified", "Every firm quote is complete and supported", "Comparison and competition evidence were reviewed", "Awarded draft purchase order matches the winning quotation"]} /></GuideSection>
  </div>;
}
