import { routesPath } from "@/routes/routes-path";
import { P } from "@/permissions";

import type { Walkthrough } from "./types";

const R = routesPath.PROTECTED;

export const WALKTHROUGH_REGISTRY = [
  {
    id: "walkthrough.getting-started.console-basics",
    guideId: "getting-started.console-basics",
    route: R.OVERVIEW.INDEX,
    permissions: [],
    prerequisites: ["Sign in to Console."],
    version: 2,
    steps: [
      {
        id: "welcome",
        title: "Welcome to Console",
        body: "This short tour shows where to start work, find an action, and get help. It never submits anything for you.",
        advance: "next",
      },
      {
        // The panel renders nothing at all on a clear day, so the tour has to
        // branch around it rather than point at an element that is not there.
        id: "todays-focus-branch",
        kind: "branch",
        target: "overview.action-center",
        whenPresent: "todays-focus",
        whenMissing: "quick-actions-branch",
      },
      {
        id: "todays-focus",
        target: "overview.action-center",
        title: "See what needs you, and what to watch",
        body: "Today's focus separates work only you can clear - approvals, returned submissions, tasks, your tickets - from conditions across the organization. Counts cover unfinished work only, so finishing something removes it. Selecting a row opens exactly the records it counted.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "quick-actions-branch",
        kind: "branch",
        target: "overview.quick-actions",
        whenPresent: "quick-actions",
        whenMissing: "workspace-search",
      },
      {
        id: "quick-actions",
        target: "overview.quick-actions",
        title: "Open frequent work quickly",
        body: "Quick actions are permission-aware and adapt to the work you open most. Select an action only when you are ready to leave this page.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "workspace-search",
        target: "header.workspace-search",
        title: "Find pages, actions, people, and guides",
        body: "Workspace search uses task language. On a phone, this target opens the same search in a full-width panel.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "page-help",
        target: "header.page-help",
        title: "Get help without losing your place",
        body: "Opens a support ticket you can raise without leaving this screen. Guides matched to the page, walkthroughs and troubleshooting are one click below it.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "complete",
        title: "You know the main paths",
        body: "You can now start from quick actions, search the whole workspace, and open help that understands your current screen.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.schools.create-and-configure",
    guideId: "schools.create-and-configure",
    route: R.SCHOOL_MGT.CREATE,
    permissions: [P.ONBOARD_SCHOOL],
    prerequisites: [
      "Confirm the approved school, branch, administrator, and package details.",
      "Use working administrator email addresses that do not belong to existing accounts.",
    ],
    version: 2,
    steps: [
      {
        id: "welcome",
        title: "Plan the complete school setup",
        body: "This form creates the school, branches, administrators, package access, capacity limits, and invitations. This walkthrough explains the decisions but never fills a field or submits anything.",
        advance: "next",
      },
      {
        id: "school-details",
        target: "school-create.school-details",
        title: "Start with the school identity",
        body: "Enter the agreed name, stable slug, address, ownership type, term structure, and currency. Continue only after checking these values against the onboarding record.",
        placement: "top",
        search: "?step=school",
        advance: "manual",
      },
      {
        id: "branches",
        target: "school-create.branches",
        title: "Branches create location-specific invitations",
        body: "Add at least one branch, choose exactly one main branch, and verify each branch administrator email. The walkthrough has opened this view without changing or validating any field.",
        placement: "top",
        search: "?step=branch",
        advance: "manual",
      },
      {
        id: "school-admin",
        target: "school-create.school-admin",
        title: "Confirm the primary school administrator",
        body: "This administrator manages the school as a whole. Verify the person's identity and email before continuing. The walkthrough only opens the view and never sends an invitation.",
        placement: "top",
        search: "?step=admin",
        advance: "manual",
      },
      {
        id: "package-boundary",
        target: "school-create.package",
        title: "Package choices control access and limits",
        body: "On Package Setup, use only the approved plan, modules, capacities, and expiry. Console may add required module dependencies. Review earlier steps with Back before you submit.",
        placement: "top",
        search: "?step=plan",
        advance: "manual",
      },
      {
        id: "complete",
        title: "You keep control of the final action",
        body: "The walkthrough stops here. Submit creates business records and sends administrator invitations, so select it yourself only after the complete setup is approved.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.roles.create-and-assign",
    guideId: "roles.create-and-assign",
    route: R.ROLES.CREATE,
    permissions: [P.VIEW_ROLES, P.DEFINE_ROLE, P.ASSIGN_ROLE],
    prerequisites: [
      "Agree the role's job purpose and minimum required access.",
      "Review existing roles and permission groups before creating another role.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Build access from an approved job need",
        body: "This walkthrough explains how a role is composed and later assigned. It never selects permissions, creates the role, assigns access, changes a role, or revokes an assignment.",
        advance: "next",
      },
      {
        id: "basic-information",
        target: "role-create.basic-information",
        title: "Name the responsibility clearly",
        body: "Use a distinct role name, describe its intended job, and choose whether it should start Active. A clear purpose makes later reviews and revocations safer.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "permission-groups",
        target: "role-create.permission-groups",
        title: "Groups grant their complete permission set",
        body: "Select a group only when every included permission fits the job. Reusing approved groups improves consistency, but it can also grant more than the role needs.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "individual-permissions",
        target: "role-create.individual-permissions",
        title: "Add only the remaining individual access",
        body: "Search by key or description and select permissions that are required but not already represented by the chosen groups. Check dependencies before creation.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "complete",
        title: "Review before two separate actions",
        body: "Creating the role does not assign it. Review the final permission set before Create Role, then separately verify the user and their existing roles before Assign Role.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.roles.transfer-super-admin",
    guideId: "roles.review-changes-and-transfer-super-admin",
    route: R.ROLES.TRANSFER_SUPER_ADMIN,
    permissions: [P.TRANSFER_SUPER_ADMIN],
    prerequisites: [
      "Confirm the handover is authorized and the successor is an active CX staff member.",
      "Ensure the successor is ready to assume the platform's single highest-privilege role.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Protect the single Super Admin role",
        body: "This walkthrough explains the ownership handover. It never chooses a successor, types a confirmation email, transfers ownership, or bypasses the current-owner check.",
        advance: "next",
      },
      {
        id: "current-owner",
        target: "super-admin-transfer.current-owner",
        title: "Verify the current owner first",
        body: "The platform must have exactly one active Super Admin, and only that current owner can initiate a transfer. Stop and contact engineering if no active owner appears.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "successor",
        target: "super-admin-transfer.successor",
        title: "Choose an eligible, prepared successor",
        body: "Only active CX staff appear. Confirm identity, readiness, and authorization before selecting anyone. The current owner is excluded from the list.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "consequence",
        target: "super-admin-transfer.warning",
        title: "The access change is immediate",
        body: "The successor becomes the only Super Admin. The current owner becomes Platform Admin and immediately loses super-admin-only capabilities, including this transfer flow.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "complete",
        title: "The final confirmation stays with you",
        body: "The walkthrough stops here. Compare From and To, type the successor's email exactly, and confirm only when the authorized handover is ready to take effect.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.roles.maintain-permission-catalogue",
    guideId: "roles.maintain-permission-catalogue",
    route: R.PERMISSIONS.CREATE,
    permissions: [P.CREATE_PERMISSION],
    prerequisites: [
      "Confirm the backend already enforces the proposed permission key.",
      "Agree its module, resource, action, sensitivity, restrictions, and dependencies.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Treat the catalogue as a security contract",
        body: "This walkthrough explains permission composition and classification. It never chooses catalogue values, creates a key, changes dependencies, or edits a permission group.",
        advance: "next",
      },
      {
        id: "permission-key",
        target: "permission-create.key",
        title: "Compose the exact authorization key",
        body: "Select the approved module, one of its resources, and the action. Check the preview against the backend permission check and prevent duplicate keys.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "classification",
        target: "permission-create.classification",
        title: "Classify the consequence",
        body: "Describe what the permission allows, choose Normal, Sensitive, or Critical, decide whether it is Restricted, and choose whether it starts Active.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "backend-boundary",
        title: "Frontend visibility is not authorization",
        body: "Before creation, verify the backend rejects an unauthorized request and enforces tenant or entity scope. A key used only to hide a button does not secure the operation.",
        advance: "manual",
      },
      {
        id: "complete",
        title: "Creation remains a deliberate action",
        body: "The walkthrough stops before Create Permission. After creation, add required dependencies, review groups and roles, and test both permitted and denied requests.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.organogram.build-structure",
    guideId: "organogram.build-structure",
    route: R.ORGANOGRAM.MANAGE,
    permissions: [P.MANAGE_ORGANOGRAM],
    prerequisites: [
      "Agree the division, department, team, and position hierarchy before entering it.",
      "Identify the approved solid reporting lines separately from matrix relationships.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Build the structure from the top down",
        body: "This walkthrough explains the safe creation order. It never creates, edits, moves, or deletes an org unit, position, assignment, or matrix line.",
        advance: "next",
      },
      {
        id: "org-units",
        target: "organogram-manage.tab.units",
        title: "Create the parent chain first",
        body: "Use Org Units to create divisions, then departments inside divisions, then teams inside departments. Confirm each parent before selecting Create.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "positions",
        target: "organogram-manage.tab.positions",
        title: "Positions define seats and solid reporting",
        body: "Use Positions after the unit chain exists. A position belongs to a team, has a capacity, and may report solidly to another position. That line drives manager and task boundaries.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "matrix",
        target: "organogram-manage.tab.matrix",
        title: "Keep dotted lines separate",
        body: "Use Matrix only for an additional advisory relationship between different positions. It does not replace the solid manager or expand task assignment access.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "complete",
        title: "Review the chart before assigning people",
        body: "The walkthrough stops before any write. Open Organisation Chart, inspect People and Positions, and correct the structure before creating or moving staff seat assignments.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.organogram.maintain-staff-profiles",
    guideId: "organogram.maintain-staff-profiles",
    route: R.ORGANOGRAM.STAFF_CREATE,
    permissions: [P.CREATE_STAFF_PROFILE],
    prerequisites: [
      "Confirm the CX staff account already exists and has no staff profile.",
      "Create the intended position first and obtain approval for sensitive profile data.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Connect identity, employment, and structure carefully",
        body: "This walkthrough explains the profile and primary-seat boundaries. It never selects a person or seat, reads field values, uploads a photo, creates a profile, or changes an assignment.",
        advance: "next",
      },
      {
        id: "seat-identity",
        target: "staff-profile.seat-identity",
        title: "Verify both the person and the seat",
        body: "Select the exact CX staff account and approved primary position. Employee ID and job title describe the HR record, while the position controls the effective reporting seat.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "employment",
        target: "staff-profile.employment",
        title: "Record the current employment state",
        body: "Choose the approved employment type and status, then use joined and exited dates consistently. These values should match the authoritative HR decision.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "payroll",
        target: "staff-profile.payroll",
        title: "Payroll access remains separate",
        body: "Bank fields appear only with payroll-manage access. Keep those values out of general profile notes, tasks, screenshots, and support tickets.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "complete",
        title: "Creation and seat assignment remain deliberate",
        body: "The walkthrough stops before Create profile. After saving, confirm the profile exists and the separate primary-seat assignment succeeded in Position history and Organisation Chart.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.workflow.review-and-act",
    guideId: "workflow.review-and-act",
    route: R.WORKFLOW.APPROVALS,
    permissions: [],
    prerequisites: [
      "Confirm you are acting as yourself or through an authorized active delegation.",
      "Open the source record and gather the evidence required by the approval policy.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Review before recording a decision",
        body: "This walkthrough explains how to find and assess approval work. It never opens an item, chooses a decision, enters a reason, confirms a vote, or bypasses eligibility.",
        advance: "next",
      },
      {
        id: "filters",
        target: "workflow-approvals.filters",
        title: "Start with the right queue",
        body: "Choose a document type and whether you are viewing your own queue or items delegated on behalf of another approver. Counts reflect pending items you can currently act on.",
        placement: "right",
        advance: "manual",
      },
      {
        id: "queue",
        target: "workflow-approvals.queue",
        title: "Verify the request before Review",
        body: "Use the requester, document reference, active stage, and waiting time to identify the item. Review the source document and activity before making any decision.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "decision-boundary",
        title: "Approve, reject, and return have different outcomes",
        body: "Approve may advance or finish the workflow. Reject follows the template's terminal or return rule. Return asks the owner to correct and resubmit. Console requires your explicit confirmation for every choice.",
        advance: "next",
      },
      {
        id: "complete",
        title: "The walkthrough stops before the decision",
        body: "Open Review yourself, verify the document, workflow stage, approval rule, and audit history, then choose and confirm the authorized outcome. Never approve only to clear a queue.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.workflow.delegate-and-track",
    guideId: "workflow.delegate-and-track",
    route: R.WORKFLOW.DELEGATIONS,
    permissions: [],
    prerequisites: [
      "Choose an active approver who is authorized to cover the work.",
      "Agree the dates, document scope, and whether coverage is exclusive.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Delegate authority for a bounded period",
        body: "This walkthrough explains delegation scope and tracking. It never opens the form, selects a person, reads field values, saves or revokes a delegation, withdraws or resubmits a request, or performs an administrative recovery.",
        advance: "next",
      },
      {
        id: "new-delegation",
        target: "workflow-delegations.new",
        title: "Create coverage only when it is authorized",
        body: "New Delegation asks for the active approver, start and end dates, optional exact document type, exclusive setting, and reason. Review the summary before Save delegation.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "scope-tabs",
        target: "workflow-delegations.scope",
        title: "Separate authority you gave from authority you received",
        body: "My Delegations shows coverage you created. Delegated to me shows whose authority may place work in your On behalf of approval queue.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "records",
        target: "workflow-delegations.records",
        title: "Check status and scope",
        body: "Active and Scheduled delegations can be revoked by their owner. Expired and Revoked records remain visible. Confirm the dates, document type, and Exclusive label before relying on coverage.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "complete",
        title: "Track the result without bypassing the workflow",
        body: "Use My Submissions for your requests and authorized All Instances or Team Load views for administration. Cancellation and vote reversal remain exceptional, reasoned, explicit actions.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.workflow.build-template",
    guideId: "workflow.build-template",
    route: R.WORKFLOW.TEMPLATE_NEW,
    permissions: [P.VIEW_WORKFLOW_TEMPLATES, P.MANAGE_WORKFLOW_TEMPLATES],
    prerequisites: [
      "Write the approved stages, conditions, approver sources, rejection result, and notifications.",
      "Create required roles, approver groups, dynamic rules, and organogram positions first.",
      "Prepare representative requesters and document examples for validation.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Build the approval contract before publishing",
        body: "This walkthrough explains template identity, version scope, stage resolution, and validation. It never enters JSON, changes a field, adds or removes a stage, selects an approver, publishes, updates, forks, or switches a version.",
        advance: "next",
      },
      {
        id: "details",
        target: "workflow-template.details",
        title: "Set the stable identity and version context",
        body: "Name describes the path. Document type and Code identify it. Read the version banner carefully: Codex may publish a shared path, while a school adjustment creates that school's own version.",
        placement: "right",
        advance: "manual",
      },
      {
        id: "stages",
        target: "workflow-template.stages",
        title: "Resolve every stage deliberately",
        body: "For each Approval stage, verify its source, scope, advance rule, rejection result, empty-approver policy, and inclusion condition. Branch stages route without collecting votes.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "validation",
        target: "workflow-template.stages",
        title: "Preview representative requesters and branches",
        body: "Use Sample requester to check role, group, dynamic, and organogram resolution. Test specific conditions before fallback rules. New stages start with auto-skip on; switch it off unless approved policy explicitly permits an empty result.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "complete",
        title: "The final publish remains yours",
        body: "The walkthrough stops before Publish template. Review stages, routing JSON, notifications, tenant version, and validation evidence, then select the publish action yourself only when the contract is approved.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.finance.configure-foundations",
    guideId: "finance.configure-foundations",
    route: `${R.FINANCE.SETUP}/entities`,
    permissions: [P.FIN_VIEW_ENTITIES],
    prerequisites: [
      "Prepare the approved entity, base currency, fiscal calendar, chart structure, reference data, and posting mappings.",
      "Confirm which set of books should receive the configuration.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Build the accounting foundation in order",
        body: "This walkthrough explains the dependency order. It never creates an entity or account, changes reference data, saves a mapping, or performs a test posting.",
        advance: "next",
      },
      {
        id: "entity",
        target: "finance-setup.entities",
        title: "Start with one independent set of books",
        body: "Verify the entity code, reporting code, name, base currency, and fiscal calendar. Creating an entity also provisions a starter chart and its first calendar, so review all of those inputs before creation.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "chart",
        target: "finance-setup.heading",
        title: "Build the chart before transactions use it",
        body: "Use four-digit account codes: 1 Assets, 2 Liabilities, 3 Equity, 4 Income, and 5 Expenses. Decide which accounts are postable and keep parent accounts inside the same account type.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "reference-data",
        title: "Add only approved reference values",
        body: "Check FX direction and date, tax rates and posting accounts, cost-centre ownership, and constrained dimension values. These labels become journal and report inputs across Finance.",
        advance: "manual",
      },
      {
        id: "posting-defaults",
        title: "Map the services that will consume the chart",
        body: "Finance Settings maps stable posting roles to active postable accounts and controls document and banking defaults. A successful save takes effect for the next matching transaction in that entity.",
        advance: "manual",
      },
      {
        id: "complete",
        title: "The walkthrough stops before configuration",
        body: "Create and save each item yourself under its exact permission, then independently verify the calendar, chart, mappings, trial balance, and a controlled test result before live work begins.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.finance.create-and-post-journal",
    guideId: "finance.create-and-post-journal",
    route: R.FINANCE.LEDGER,
    permissions: [P.FIN_POST_DIRECT_ENTRY],
    prerequisites: [
      "Confirm the active entity and obtain approved evidence for the manual accounting entry.",
      "Prepare the accounts, debit and credit amounts, posting date, cost centres, and dimensions.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Use direct entry only for a real manual journal",
        body: "This walkthrough opens the editor and explains its checks. It never selects an account, reads or changes a field, adds a line, posts, submits, reverses, or voids anything.",
        advance: "next",
      },
      {
        id: "ledger",
        target: "finance-ledger.header",
        title: "Source documents should post their own journals",
        body: "Invoices, receipts, payroll, procurement, and bank work belong in their source screens. Use New journal only for an approved raw debit and credit entry that has no source-document workflow.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "open-editor",
        target: "finance-ledger.new-journal",
        title: "Open the editor without posting",
        body: "Select New journal to inspect the direct-entry form. Opening it changes no business data. The walkthrough will continue when the drawer opens.",
        placement: "bottom",
        advance: "target-click",
      },
      {
        id: "evidence",
        target: "finance-journal.header-fields",
        title: "Anchor the entry to evidence and an open date",
        body: "Confirm the active entity, choose the approved date inside an open posting period, and write a narration and reference that another reviewer can trace to the evidence.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "lines",
        target: "finance-journal.postings",
        title: "Build the accounting treatment line by line",
        body: "Each non-zero line needs one active postable account, a debit or credit side, an amount, and any required cost centre or dimensions. Balanced lines can still be wrong, so verify the accounting treatment separately.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "balance",
        target: "finance-journal.balance",
        title: "Balance is necessary, not sufficient",
        body: "Console requires equal debit and credit totals above zero. Recheck the entity, date, accounts, direction, amount, tags, narration, and evidence before the final action.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "complete",
        title: "Post entry remains your immediate action",
        body: "The walkthrough stops here. Post entry creates the posted journal immediately, without a draft or second confirmation. Select it yourself only after the complete review, then inspect the journal and report effect.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.finance.close-lock-or-reopen-period",
    guideId: "finance.close-lock-or-reopen-period",
    route: `${R.FINANCE.SETUP}/periods`,
    permissions: [P.FIN_VIEW_PERIODS],
    prerequisites: [
      "Confirm the active entity, fiscal year, period, approved close plan, and reconciliation evidence.",
      "Identify the owner of every draft journal, blocker, and warning before changing a period status.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Control the posting window deliberately",
        body: "This walkthrough explains the calendar, checklist, close, reopen, year-end, and permanent-lock boundaries. It never creates a year, selects a period for you, or confirms any state-changing action.",
        advance: "next",
      },
      {
        id: "calendar",
        target: "finance-periods.calendar-controls",
        title: "Work in one entity and fiscal year",
        body: "Verify the active entity and selected fiscal year. Create the next calendar before the last period expires, or every posting date beyond it will be rejected.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "period",
        target: "finance-periods.periods",
        title: "Select the exact posting period",
        body: "Open is ordinary posting, Soft-closed allows controlled close work, Closed is reopenable by permission, and Locked is permanent. Select the period you intend to inspect; opening it is read-only.",
        placement: "top",
        advance: "target-click",
      },
      {
        id: "checklist",
        target: "finance-periods.checklist",
        title: "Separate blockers from warning-only checks",
        body: "A failed blocker must be resolved before close. A warning remains visible for judgment but does not stop close. Reconcile the source records and evidence rather than forcing an offsetting entry.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "actions",
        title: "Each status action has a different consequence",
        body: "Soft close is reversible. Run close steps blocks posting after controls run. Reopen permits ordinary posting again and requires another full close. Lock cannot be reversed. Close the fiscal year before locking its final period.",
        advance: "manual",
      },
      {
        id: "complete",
        title: "Every confirmation remains with the authorized user",
        body: "The walkthrough stops before Soft close, Run close steps, Re-open, Close fiscal year, and Lock period. Verify scope, checklist, reports, approval, and correction plan, then confirm only the intended action yourself.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.finance.invoice-and-allocate-receipt",
    guideId: "finance.invoice-and-allocate-receipt",
    route: `${R.FINANCE.RECEIVABLES}/receipts`,
    permissions: [P.FIN_VIEW_PAYMENTS],
    prerequisites: [
      "Confirm the active entity and prepare the approved invoice, receipt evidence, customer, amount, method, and allocation instruction.",
      "Use an existing receipt for inspection. The walkthrough never records or changes one.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Trace money from invoice to settled balance",
        body: "This walkthrough explains receipt evidence and allocation controls. It never creates or posts an invoice, records a receipt, changes an allocation, applies customer credit, refunds, writes off, or voids a document.",
        advance: "next",
      },
      {
        id: "workspace",
        target: "finance-receipts.summary",
        title: "Confirm the entity and receipt population",
        body: "Use the active entity and filters to find the posted receipt supported by your bank, cash, card, cheque, online, or other approved evidence. Unallocated means money is still available as customer credit.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "record",
        target: "finance-receipts.record",
        title: "Recording money is a separate posting",
        body: "Record receipt captures the customer, date, method, amount, reference, and receiving account. It posts the cash event. This walkthrough does not open or submit that form.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "list",
        target: "finance-receipts.list",
        title: "Inspect an existing receipt",
        body: "Select a receipt row if you want to inspect its allocation drawer, then choose Next. Opening the drawer is read-only and lets you compare the receipt with the customer's open items.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "allocation-branch",
        kind: "branch",
        target: "finance-receipts.allocation",
        whenPresent: "allocation",
        whenMissing: "allocation-not-open",
      },
      {
        id: "allocation",
        target: "finance-receipts.allocation",
        title: "Review the suggested settlement",
        body: "Oldest-first or largest-first can suggest a split across open invoices and debit notes. Verify each item, amount, total, and remainder against remittance evidence. Applying the split posts a reclassification, so the walkthrough stops before Apply allocation.",
        placement: "left",
        advance: "next",
      },
      {
        id: "complete",
        title: "The allocation remains your decision",
        body: "Close the walkthrough, make any approved selection yourself, and apply only after receipt, customer, open items, totals, remainder, and GL effect agree. Reopen both documents and verify the final customer balance.",
        advance: "next",
      },
      {
        id: "allocation-not-open",
        title: "No receipt was opened",
        body: "The walkthrough will not choose a customer's receipt for you. Open one later to compare its remaining credit with open invoices or debit notes, then apply only the approved split. Nothing was changed here.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.finance.email-customer-documents",
    guideId: "finance.email-customer-documents",
    route: `${R.FINANCE.RECEIVABLES}/invoices`,
    permissions: [P.FIN_EMAIL_INVOICE],
    prerequisites: [
      "Confirm the active entity and identify a posted invoice that is safe to inspect.",
      "Verify the customer and document before opening the email preview.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Preview a customer delivery before it leaves Console",
        body: "This walkthrough may open a read-only invoice drawer and delivery preview. It never presses Send or Retry and never changes a customer, document, recipient, or note.",
        advance: "next",
      },
      {
        id: "invoices",
        target: "finance-invoices.list",
        title: "Open the exact posted invoice",
        body: "Select the invoice you intend to inspect, verify its customer, number, status, total, and balance, then choose Next. Opening the invoice does not send anything.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "email-branch",
        kind: "branch",
        target: "finance-email.action",
        whenPresent: "email-action",
        whenMissing: "invoice-not-open",
      },
      {
        id: "email-action",
        target: "finance-email.action",
        title: "Open the delivery preview",
        body: "Email invoice loads the subject, recipients, BCC list, and prior delivery history. Opening the preview is safe. Select the button to continue.",
        placement: "top",
        advance: "target-click",
      },
      {
        id: "preview-branch",
        kind: "branch",
        target: "finance-email.preview",
        whenPresent: "preview",
        whenMissing: "invoice-not-open",
      },
      {
        id: "preview",
        target: "finance-email.preview",
        title: "Verify every delivery detail",
        body: "Check subject, To, BCC, attached document, optional note, blocked reason, and previous attempts. Sent history does not prove the customer read it, and a retry creates a new attempt.",
        placement: "left",
        advance: "next",
      },
      {
        id: "complete",
        title: "Send remains an explicit human action",
        body: "The walkthrough stops before Send and Retry. Close it, correct any source problem, and use the final action yourself only when the document and every recipient are approved.",
        advance: "next",
      },
      {
        id: "invoice-not-open",
        title: "No eligible invoice preview is open",
        body: "The walkthrough will not choose a customer's document for you. Open a posted invoice later and verify its customer and amount before opening Email invoice. Nothing was sent here.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.finance.reconcile-bank-statement",
    guideId: "finance.reconcile-bank-statement",
    route: R.FINANCE.BANK_RECON,
    permissions: [P.FIN_VIEW_BANK_ACCOUNTS],
    prerequisites: [
      "Obtain the complete approved bank statement and confirm its account, currency, date range, opening balance, and closing balance.",
      "Confirm all expected source transactions and authorized adjustments are posted in the active entity.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Explain every difference between bank and books",
        body: "This walkthrough explains the reconciliation workbench. It never imports a statement, selects lines, changes a match, creates an adjustment, ignores evidence, runs auto-match, unmatches, or completes reconciliation.",
        advance: "next",
      },
      {
        id: "scope",
        target: "finance-bank-reconciliation.scope",
        title: "Start with the exact bank account",
        body: "Verify the active entity and select the bank account whose masked identity, currency, cash GL account, and statement period agree with your controlled source.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "workbench-branch",
        kind: "branch",
        target: "finance-bank-reconciliation.balances",
        whenPresent: "balances",
        whenMissing: "no-account",
      },
      {
        id: "balances",
        target: "finance-bank-reconciliation.balances",
        title: "Reconcile totals before individual lines",
        body: "Compare statement balance, book balance, unmatched count, and difference. Import evidence and post genuine missing transactions before trying to explain line-level exceptions.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "matching",
        target: "finance-bank-reconciliation.matching",
        title: "Match only equal, identical evidence",
        body: "One-to-one, group, and split matches must have equal totals and represent the same event. Check dates, references, parties, direction, and business purpose. Never force a pair just to reduce the difference.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "exceptions",
        target: "finance-bank-reconciliation.exceptions",
        title: "Explain exceptions without hiding them",
        body: "Leave real timing items unmatched, post approved missing entries through their source, and ignore only a known duplicate or opening line with evidence. Ignoring has no ledger effect.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "complete",
        title: "Completion remains with the authorized reconciler",
        body: "The walkthrough stops before every matching and completion action. Finish only when totals agree, every unmatched or ignored line is explained, approved adjustments are posted, and the report is ready for independent review.",
        advance: "next",
      },
      {
        id: "no-account",
        title: "No reconciliation workbench is available",
        body: "Select or create the approved bank account and confirm its GL mapping and imported statement before matching. The walkthrough did not create or change anything.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.finance.run-payroll",
    guideId: "finance.run-payroll",
    route: R.FINANCE.PAYROLL,
    permissions: [P.FIN_VIEW_PAYROLL],
    prerequisites: ["Confirm the entity, pay period, approved roster, structures, pay date, and payroll evidence.", "Use the walkthrough only where restricted payroll data can be viewed privately."],
    version: 1,
    steps: [
      { id: "welcome", title: "Review payroll without moving money", body: "This walkthrough explains the roster, draft, posting, payment, payslip, and statutory boundaries. It never opens an employee, reads a field, generates, posts, pays, cancels, voids, prints, or remits anything.", advance: "next" },
      { id: "scope", target: "finance-payroll.heading", title: "Confirm the payroll entity", body: "Payroll belongs to one active ledger entity. Verify the entity, period, date, and confidentiality before inspecting any run or employee figure.", placement: "bottom", advance: "manual" },
      { id: "sections", target: "finance-payroll.sections", title: "Prepare the roster before the run", body: "Salary structures define components, Employee salaries defines the active roster, Payroll runs creates the liability, Payslips provides employee evidence, and Statutory returns provides PAYE and pension schedules.", placement: "bottom", advance: "manual" },
      { id: "summary", target: "finance-payroll.summary", title: "Separate calculated payroll from cash paid", body: "Awaiting payment is a calculated run whose net-wages liability is still open. Posting creates salary and statutory liabilities; Pay net clears only net wages. Tax Remittance clears PAYE and pension separately.", placement: "top", advance: "manual" },
      { id: "complete", title: "Every payroll action remains explicit", body: "The walkthrough stops before New payroll run, Calculate & post, Pay net, Cancel, Void, printing, and tax remittance. Complete each only after independent review and under its exact permission.", advance: "next" },
    ],
  },
  {
    id: "walkthrough.finance.submit-and-settle-expense-claim",
    guideId: "finance.submit-and-settle-expense-claim",
    route: `${R.FINANCE.EXPENSES}/claims`,
    permissions: [P.FIN_VIEW_EXPENSE_CLAIMS],
    prerequisites: ["Confirm the entity and approved claimant, expense lines, receipts, coding, and settlement evidence."],
    version: 1,
    steps: [
      { id: "welcome", title: "Keep evidence, posting, and payment together", body: "This walkthrough explains claim states and controls. It never creates a claim, uploads or deletes evidence, opens a claimant record, posts, rejects, settles, voids, or exports anything.", advance: "next" },
      { id: "workspace", target: "finance-expense-claims.heading", title: "Work in the correct entity", body: "Confirm the entity before using the list. A claim, its expense journal, payable, and settlement must remain in the same set of books.", placement: "bottom", advance: "manual" },
      { id: "summary", target: "finance-expense-claims.summary", title: "Read the queue by accounting stage", body: "Open includes drafts or claims awaiting payment. Approved but unpaid claims have posted the expense and liability but have not moved cash.", placement: "top", advance: "manual" },
      { id: "controls", target: "finance-expense-claims.controls", title: "Find the exact claim before acting", body: "Search by claimant, purpose, or number and filter by status. Verify every receipt, account, tax code, cost centre, total, and payee before the next state change.", placement: "bottom", advance: "manual" },
      { id: "complete", title: "No claim was changed", body: "Post, Reject, Pay, and Void remain authorized user decisions. Use the source claim for corrections and verify its journal and bank result after action.", advance: "next" },
    ],
  },
  {
    id: "walkthrough.finance.manage-petty-cash",
    guideId: "finance.manage-petty-cash",
    route: `${R.FINANCE.EXPENSES}/petty-cash`,
    permissions: [P.FIN_VIEW_PETTY_CASH],
    prerequisites: ["Confirm the entity, approved float, custodian, physical count, voucher evidence, and funding account."],
    version: 1,
    steps: [
      { id: "welcome", title: "Reconcile the tin before replenishment", body: "This walkthrough explains the float, vouchers, register, and replenishment. It never establishes or funds a float, creates or posts a voucher, replenishes cash, or voids a voucher.", advance: "next" },
      { id: "workspace", target: "finance-petty-cash.heading", title: "Confirm the entity and fund", body: "Select the intended fund and custodian. Its ceiling, petty-cash account, register, and physical cash count must describe the same imprest tin.", placement: "bottom", advance: "manual" },
      { id: "fund-branch", kind: "branch", target: "finance-petty-cash.summary", whenPresent: "summary", whenMissing: "no-fund" },
      { id: "summary", target: "finance-petty-cash.summary", title: "Compare ceiling, cash, spend, and shortfall", body: "Current balance should agree with cash on hand. To replenish is the amount needed to restore the approved ceiling, not permission to increase it.", placement: "top", advance: "manual" },
      { id: "complete", title: "Cash actions remain with the custodian and approver", body: "The walkthrough stops before Establish float, New voucher, Save & post, Replenish, Post voucher, and Void. Count cash and verify evidence before any action.", advance: "next" },
      { id: "no-fund", target: "finance-petty-cash.empty", title: "No petty-cash float is established", body: "Prepare the approved custodian, ceiling, petty-cash GL account, funding bank account, and opening date. Establish float moves real cash, so the walkthrough does not open or submit it.", placement: "top", advance: "next" },
    ],
  },
  {
    id: "walkthrough.finance.build-and-approve-budget",
    guideId: "finance.build-and-approve-budget",
    route: `${R.FINANCE.BUDGETS}/budgets`,
    permissions: [P.FIN_VIEW_BUDGETS],
    prerequisites: ["Confirm the entity, fiscal year, approved assumptions, budget lines, owner, and approver."],
    version: 1,
    steps: [
      { id: "welcome", title: "Preserve the approved planning baseline", body: "This walkthrough explains budget construction, approval, variance, and revision. It never creates, edits, deletes, or approves a budget or line.", advance: "next" },
      { id: "workspace", target: "finance-budgets.heading", title: "Choose one planning scope", body: "Verify the entity, fiscal year, owner, assumptions, and version before comparing lines or actuals.", placement: "bottom", advance: "manual" },
      { id: "controls", target: "finance-budgets.controls", title: "Build lines in the chart's shape", body: "Each line combines an income or expense account, optional cost centre, and period amount. Check signs, phasing, duplicates, totals, and ownership before approval.", placement: "bottom", advance: "manual" },
      { id: "complete", title: "Approval and deletion remain explicit", body: "The walkthrough stops before New budget, line changes, Approve, and Delete. Preserve approved baselines and trace variance to posted source transactions.", advance: "next" },
    ],
  },
  {
    id: "walkthrough.finance.manage-fixed-assets",
    guideId: "finance.manage-fixed-assets",
    route: `${R.FINANCE.BUDGETS}/assets`,
    permissions: [P.FIN_VIEW_FIXED_ASSETS],
    prerequisites: ["Confirm the entity, asset evidence, valuation, accounts, useful life, dates, and disposal authorization."],
    version: 1,
    steps: [
      { id: "welcome", title: "Keep register and ledger synchronized", body: "This walkthrough explains creation, acquisition, depreciation, and disposal. It never adds, acquires, depreciates, disposes, or changes an asset.", advance: "next" },
      { id: "workspace", target: "finance-assets.heading", title: "Confirm the asset register scope", body: "Use one entity and verify asset identity, category, location or custodian, cost, residual value, useful life, start date, and mapped accounts.", placement: "bottom", advance: "manual" },
      { id: "summary", target: "finance-assets.summary", title: "Reconcile cost, depreciation, and net book value", body: "Register totals should agree with the fixed-asset and accumulated-depreciation accounts. Investigate gaps before running another posting.", placement: "top", advance: "manual" },
      { id: "controls", target: "finance-assets.controls", title: "Preview consequential lifecycle actions", body: "Run depreciation may post a compound period journal. Add asset starts a draft. Acquisition capitalises cost, and disposal records proceeds plus gain or loss.", placement: "bottom", advance: "manual" },
      { id: "complete", title: "No asset posting was performed", body: "The walkthrough stops before Add asset, Acquire, Depreciate to date, Run depreciation, and Dispose. Review the preview and evidence before each action.", advance: "next" },
    ],
  },
  {
    id: "walkthrough.finance.file-and-pay-tax",
    guideId: "finance.file-and-pay-tax",
    route: `${R.FINANCE.BUDGETS}/tax`,
    permissions: [P.FIN_VIEW_TAX],
    prerequisites: ["Confirm the entity, obligation, authority, period, liability account, schedules, filing evidence, and bank approval."],
    version: 1,
    steps: [
      { id: "welcome", title: "Separate preparation, filing, and cash remittance", body: "This walkthrough explains tax states and controls. It never creates an obligation, prepares, files, un-files, pays, or prints a return.", advance: "next" },
      { id: "workspace", target: "finance-tax.heading", title: "Confirm the statutory scope", body: "Verify the entity, tax type, authority, filing frequency, period, due date, and payable account before using the workbench.", placement: "bottom", advance: "manual" },
      { id: "summary", target: "finance-tax.summary", title: "Read outstanding liability by state", body: "Open is prepared but unfiled. Filed awaiting payment has authority evidence but an open cash liability. Paid is fully remitted; a partial payment remains open.", placement: "top", advance: "manual" },
      { id: "controls", target: "finance-tax.controls", title: "Use the correct control for the next state", body: "New obligation defines the statutory mapping. New filing prepares a period from the ledger. Filing records authority evidence, while Pay clears the liability against bank.", placement: "bottom", advance: "manual" },
      { id: "complete", title: "Every filing and payment remains explicit", body: "The walkthrough stops before New obligation, New filing, Mark as filed, Un-file, and Pay. Reconcile schedules, ledger, authority reference, and bank evidence first.", advance: "next" },
    ],
  },
  {
    id: "walkthrough.finance.collect-online-payments",
    guideId: "finance.collect-online-payments",
    route: R.FINANCE.COLLECTIONS,
    permissions: [P.PAY_VIEW_COLLECTIONS],
    prerequisites: ["Confirm the entity, customer, expected amount, provider reference, and intended invoice or receipt."],
    version: 1,
    steps: [
      { id: "welcome", title: "Trace provider money without duplicating it", body: "This walkthrough explains collection status, virtual accounts, business posting, and failed events. It never creates a checkout or virtual account, changes an account, replays an event, records a receipt, or allocates money.", advance: "next" },
      { id: "workspace", target: "finance-collections.heading", title: "Confirm the collection entity", body: "Find the event by safe provider reference, customer, amount, date, and currency. Keep full bank details and raw provider payloads out of screenshots and tickets.", placement: "bottom", advance: "manual" },
      { id: "summary", target: "finance-collections.summary", title: "Separate pending, failed, and settled money", body: "A pending event has not reached final provider confirmation. A settled collection should trace to its receipt, customer balance, journal, and later bank settlement.", placement: "top", advance: "manual" },
      { id: "controls", target: "finance-collections.controls", title: "Filter before creating anything new", body: "Search the existing provider and status population first. A delayed business record is not evidence that the customer must pay again.", placement: "bottom", advance: "manual" },
      { id: "complete", title: "No payment event was changed", body: "The walkthrough stops before New checkout, virtual-account changes, receipt allocation, and webhook replay. Correct the root cause and prove non-posting before replay.", advance: "next" },
    ],
  },
  {
    id: "walkthrough.finance.send-payouts-and-resolve-settlements",
    guideId: "finance.send-payouts-and-resolve-settlements",
    route: `${R.FINANCE.PAYMENTS}/payouts`,
    permissions: [P.PAY_VIEW_PAYOUTS],
    prerequisites: ["Confirm the entity, payable, beneficiary, independently verified bank details, amount, currency, and approval route."],
    version: 1,
    steps: [
      { id: "welcome", title: "Prevent duplicate disbursement", body: "This walkthrough explains payout, batch, provider, settlement, and recovery states. It never sends a payout, submits or approves a batch, replays an event, imports evidence, or changes a beneficiary.", advance: "next" },
      { id: "workspace", target: "finance-payments-payouts.heading", title: "Confirm the payout entity", body: "Search for an existing transfer by reference, beneficiary, amount, and date before raising another. Masked bank details require separate sensitive access.", placement: "bottom", advance: "manual" },
      { id: "summary", target: "finance-payouts.summary", title: "Status is evidence, not a retry instruction", body: "Pending may still settle. Failed or reversed requires the provider reason, transaction history, webhook evidence, accounting result, and bank evidence before any recovery action.", placement: "top", advance: "manual" },
      { id: "workbench", target: "finance-payouts.controls", title: "Choose single or maker-checker batch flow", body: "Use one payout for a single approved transfer and Batches for controlled bulk disbursement. Review every beneficiary, amount, duplicate, error, total, and approval requirement.", placement: "top", advance: "manual" },
      { id: "complete", title: "No payout or replay was performed", body: "The walkthrough stops before New payout, batch submission or approval, and webhook replay. Reconcile confirmed provider results to the bank, and escalate ambiguous cases instead of sending twice.", advance: "next" },
    ],
  },
] as const satisfies readonly Walkthrough[];

export function findWalkthrough(id: string): Walkthrough | undefined {
  return WALKTHROUGH_REGISTRY.find((walkthrough) => walkthrough.id === id);
}
