import { routesPath } from "@/routes/routes-path";
import { P } from "@/permissions";

import type { Walkthrough } from "./types";

const R = routesPath.PROTECTED;

export const WALKTHROUGH_REGISTRY = [
  {
    id: "walkthrough.getting-started.console-basics",
    guideId: "getting-started.console-basics",
    route: R.OVERVIEW.INDEX,
    permissions: [],
    prerequisites: ["Sign in to Console."],
    version: 2,
    steps: [
      {
        id: "welcome",
        title: "Welcome to Console",
        body: "This short tour shows where to start work, find an action, and get help. It never submits anything for you.",
        advance: "next",
      },
      {
        // The panel renders nothing at all on a clear day, so the tour has to
        // branch around it rather than point at an element that is not there.
        id: "todays-focus-branch",
        kind: "branch",
        target: "overview.action-center",
        whenPresent: "todays-focus",
        whenMissing: "quick-actions-branch",
      },
      {
        id: "todays-focus",
        target: "overview.action-center",
        title: "See what needs you, and what to watch",
        body: "Today's focus separates work only you can clear - approvals, returned submissions, tasks, your tickets - from conditions across the organization. Counts cover unfinished work only, so finishing something removes it. Selecting a row opens exactly the records it counted.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "quick-actions-branch",
        kind: "branch",
        target: "overview.quick-actions",
        whenPresent: "quick-actions",
        whenMissing: "workspace-search",
      },
      {
        id: "quick-actions",
        target: "overview.quick-actions",
        title: "Open frequent work quickly",
        body: "Quick actions are permission-aware and adapt to the work you open most. Select an action only when you are ready to leave this page.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "workspace-search",
        target: "header.workspace-search",
        title: "Find pages, actions, people, and guides",
        body: "Workspace search uses task language. On a phone, this target opens the same search in a full-width panel.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "page-help",
        target: "header.page-help",
        title: "Get help without losing your place",
        body: "Opens a support ticket you can raise without leaving this screen. Guides matched to the page, walkthroughs and troubleshooting are one click below it.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "complete",
        title: "You know the main paths",
        body: "You can now start from quick actions, search the whole workspace, and open help that understands your current screen.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.schools.create-and-configure",
    guideId: "schools.create-and-configure",
    route: R.SCHOOL_MGT.CREATE,
    permissions: [P.ONBOARD_SCHOOL],
    prerequisites: [
      "Confirm the approved school, branch, administrator, and package details.",
      "Use working administrator email addresses that do not belong to existing accounts.",
    ],
    version: 2,
    steps: [
      {
        id: "welcome",
        title: "Plan the complete school setup",
        body: "This form creates the school, branches, administrators, package access, capacity limits, and invitations. This walkthrough explains the decisions but never fills a field or submits anything.",
        advance: "next",
      },
      {
        id: "school-details",
        target: "school-create.school-details",
        title: "Start with the school identity",
        body: "Enter the agreed name, stable slug, address, ownership type, term structure, and currency. Continue only after checking these values against the onboarding record.",
        placement: "top",
        search: "?step=school",
        advance: "manual",
      },
      {
        id: "branches",
        target: "school-create.branches",
        title: "Branches create location-specific invitations",
        body: "Add at least one branch, choose exactly one main branch, and verify each branch administrator email. The walkthrough has opened this view without changing or validating any field.",
        placement: "top",
        search: "?step=branch",
        advance: "manual",
      },
      {
        id: "school-admin",
        target: "school-create.school-admin",
        title: "Confirm the primary school administrator",
        body: "This administrator manages the school as a whole. Verify the person's identity and email before continuing. The walkthrough only opens the view and never sends an invitation.",
        placement: "top",
        search: "?step=admin",
        advance: "manual",
      },
      {
        id: "package-boundary",
        target: "school-create.package",
        title: "Package choices control access and limits",
        body: "On Package Setup, use only the approved plan, modules, capacities, and expiry. Console may add required module dependencies. Review earlier steps with Back before you submit.",
        placement: "top",
        search: "?step=plan",
        advance: "manual",
      },
      {
        id: "complete",
        title: "You keep control of the final action",
        body: "The walkthrough stops here. Submit creates business records and sends administrator invitations, so select it yourself only after the complete setup is approved.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.roles.create-and-assign",
    guideId: "roles.create-and-assign",
    route: R.ROLES.CREATE,
    permissions: [P.VIEW_ROLES, P.DEFINE_ROLE, P.ASSIGN_ROLE],
    prerequisites: [
      "Agree the role's job purpose and minimum required access.",
      "Review existing roles and permission groups before creating another role.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Build access from an approved job need",
        body: "This walkthrough explains how a role is composed and later assigned. It never selects permissions, creates the role, assigns access, changes a role, or revokes an assignment.",
        advance: "next",
      },
      {
        id: "basic-information",
        target: "role-create.basic-information",
        title: "Name the responsibility clearly",
        body: "Use a distinct role name, describe its intended job, and choose whether it should start Active. A clear purpose makes later reviews and revocations safer.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "permission-groups",
        target: "role-create.permission-groups",
        title: "Groups grant their complete permission set",
        body: "Select a group only when every included permission fits the job. Reusing approved groups improves consistency, but it can also grant more than the role needs.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "individual-permissions",
        target: "role-create.individual-permissions",
        title: "Add only the remaining individual access",
        body: "Search by key or description and select permissions that are required but not already represented by the chosen groups. Check dependencies before creation.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "complete",
        title: "Review before two separate actions",
        body: "Creating the role does not assign it. Review the final permission set before Create Role, then separately verify the user and their existing roles before Assign Role.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.roles.transfer-super-admin",
    guideId: "roles.review-changes-and-transfer-super-admin",
    route: R.ROLES.TRANSFER_SUPER_ADMIN,
    permissions: [P.TRANSFER_SUPER_ADMIN],
    prerequisites: [
      "Confirm the handover is authorized and the successor is an active CX staff member.",
      "Ensure the successor is ready to assume the platform's single highest-privilege role.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Protect the single Super Admin role",
        body: "This walkthrough explains the ownership handover. It never chooses a successor, types a confirmation email, transfers ownership, or bypasses the current-owner check.",
        advance: "next",
      },
      {
        id: "current-owner",
        target: "super-admin-transfer.current-owner",
        title: "Verify the current owner first",
        body: "The platform must have exactly one active Super Admin, and only that current owner can initiate a transfer. Stop and contact engineering if no active owner appears.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "successor",
        target: "super-admin-transfer.successor",
        title: "Choose an eligible, prepared successor",
        body: "Only active CX staff appear. Confirm identity, readiness, and authorization before selecting anyone. The current owner is excluded from the list.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "consequence",
        target: "super-admin-transfer.warning",
        title: "The access change is immediate",
        body: "The successor becomes the only Super Admin. The current owner becomes Platform Admin and immediately loses super-admin-only capabilities, including this transfer flow.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "complete",
        title: "The final confirmation stays with you",
        body: "The walkthrough stops here. Compare From and To, type the successor's email exactly, and confirm only when the authorized handover is ready to take effect.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.roles.maintain-permission-catalogue",
    guideId: "roles.maintain-permission-catalogue",
    route: R.PERMISSIONS.CREATE,
    permissions: [P.CREATE_PERMISSION],
    prerequisites: [
      "Confirm the backend already enforces the proposed permission key.",
      "Agree its module, resource, action, sensitivity, restrictions, and dependencies.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Treat the catalogue as a security contract",
        body: "This walkthrough explains permission composition and classification. It never chooses catalogue values, creates a key, changes dependencies, or edits a permission group.",
        advance: "next",
      },
      {
        id: "permission-key",
        target: "permission-create.key",
        title: "Compose the exact authorization key",
        body: "Select the approved module, one of its resources, and the action. Check the preview against the backend permission check and prevent duplicate keys.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "classification",
        target: "permission-create.classification",
        title: "Classify the consequence",
        body: "Describe what the permission allows, choose Normal, Sensitive, or Critical, decide whether it is Restricted, and choose whether it starts Active.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "backend-boundary",
        title: "Frontend visibility is not authorization",
        body: "Before creation, verify the backend rejects an unauthorized request and enforces tenant or entity scope. A key used only to hide a button does not secure the operation.",
        advance: "manual",
      },
      {
        id: "complete",
        title: "Creation remains a deliberate action",
        body: "The walkthrough stops before Create Permission. After creation, add required dependencies, review groups and roles, and test both permitted and denied requests.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.organogram.build-structure",
    guideId: "organogram.build-structure",
    route: R.ORGANOGRAM.MANAGE,
    permissions: [P.MANAGE_ORGANOGRAM],
    prerequisites: [
      "Agree the division, department, team, and position hierarchy before entering it.",
      "Identify the approved solid reporting lines separately from matrix relationships.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Build the structure from the top down",
        body: "This walkthrough explains the safe creation order. It never creates, edits, moves, or deletes an org unit, position, assignment, or matrix line.",
        advance: "next",
      },
      {
        id: "org-units",
        target: "organogram-manage.tab.units",
        title: "Create the parent chain first",
        body: "Use Org Units to create divisions, then departments inside divisions, then teams inside departments. Confirm each parent before selecting Create.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "positions",
        target: "organogram-manage.tab.positions",
        title: "Positions define seats and solid reporting",
        body: "Use Positions after the unit chain exists. A position belongs to a team, has a capacity, and may report solidly to another position. That line drives manager and task boundaries.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "matrix",
        target: "organogram-manage.tab.matrix",
        title: "Keep dotted lines separate",
        body: "Use Matrix only for an additional advisory relationship between different positions. It does not replace the solid manager or expand task assignment access.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "complete",
        title: "Review the chart before assigning people",
        body: "The walkthrough stops before any write. Open Organisation Chart, inspect People and Positions, and correct the structure before creating or moving staff seat assignments.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.organogram.maintain-staff-profiles",
    guideId: "organogram.maintain-staff-profiles",
    route: R.ORGANOGRAM.STAFF_CREATE,
    permissions: [P.CREATE_STAFF_PROFILE],
    prerequisites: [
      "Confirm the CX staff account already exists and has no staff profile.",
      "Create the intended position first and obtain approval for sensitive profile data.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Connect identity, employment, and structure carefully",
        body: "This walkthrough explains the profile and primary-seat boundaries. It never selects a person or seat, reads field values, uploads a photo, creates a profile, or changes an assignment.",
        advance: "next",
      },
      {
        id: "seat-identity",
        target: "staff-profile.seat-identity",
        title: "Verify both the person and the seat",
        body: "Select the exact CX staff account and approved primary position. Employee ID and job title describe the HR record, while the position controls the effective reporting seat.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "employment",
        target: "staff-profile.employment",
        title: "Record the current employment state",
        body: "Choose the approved employment type and status, then use joined and exited dates consistently. These values should match the authoritative HR decision.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "payroll",
        target: "staff-profile.payroll",
        title: "Payroll access remains separate",
        body: "Bank fields appear only with payroll-manage access. Keep those values out of general profile notes, tasks, screenshots, and support tickets.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "complete",
        title: "Creation and seat assignment remain deliberate",
        body: "The walkthrough stops before Create profile. After saving, confirm the profile exists and the separate primary-seat assignment succeeded in Position history and Organisation Chart.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.workflow.review-and-act",
    guideId: "workflow.review-and-act",
    route: R.WORKFLOW.APPROVALS,
    permissions: [],
    prerequisites: [
      "Confirm you are acting as yourself or through an authorized active delegation.",
      "Open the source record and gather the evidence required by the approval policy.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Review before recording a decision",
        body: "This walkthrough explains how to find and assess approval work. It never opens an item, chooses a decision, enters a reason, confirms a vote, or bypasses eligibility.",
        advance: "next",
      },
      {
        id: "filters",
        target: "workflow-approvals.filters",
        title: "Start with the right queue",
        body: "Choose a document type and whether you are viewing your own queue or items delegated on behalf of another approver. Counts reflect pending items you can currently act on.",
        placement: "right",
        advance: "manual",
      },
      {
        id: "queue",
        target: "workflow-approvals.queue",
        title: "Verify the request before Review",
        body: "Use the requester, document reference, active stage, and waiting time to identify the item. Review the source document and activity before making any decision.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "decision-boundary",
        title: "Approve, reject, and return have different outcomes",
        body: "Approve may advance or finish the workflow. Reject follows the template's terminal or return rule. Return asks the owner to correct and resubmit. Console requires your explicit confirmation for every choice.",
        advance: "next",
      },
      {
        id: "complete",
        title: "The walkthrough stops before the decision",
        body: "Open Review yourself, verify the document, workflow stage, approval rule, and audit history, then choose and confirm the authorized outcome. Never approve only to clear a queue.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.workflow.delegate-and-track",
    guideId: "workflow.delegate-and-track",
    route: R.WORKFLOW.DELEGATIONS,
    permissions: [],
    prerequisites: [
      "Choose an active approver who is authorized to cover the work.",
      "Agree the dates, document scope, and whether coverage is exclusive.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Delegate authority for a bounded period",
        body: "This walkthrough explains delegation scope and tracking. It never opens the form, selects a person, reads field values, saves or revokes a delegation, withdraws or resubmits a request, or performs an administrative recovery.",
        advance: "next",
      },
      {
        id: "new-delegation",
        target: "workflow-delegations.new",
        title: "Create coverage only when it is authorized",
        body: "New Delegation asks for the active approver, start and end dates, optional exact document type, exclusive setting, and reason. Review the summary before Save delegation.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "scope-tabs",
        target: "workflow-delegations.scope",
        title: "Separate authority you gave from authority you received",
        body: "My Delegations shows coverage you created. Delegated to me shows whose authority may place work in your On behalf of approval queue.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "records",
        target: "workflow-delegations.records",
        title: "Check status and scope",
        body: "Active and Scheduled delegations can be revoked by their owner. Expired and Revoked records remain visible. Confirm the dates, document type, and Exclusive label before relying on coverage.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "complete",
        title: "Track the result without bypassing the workflow",
        body: "Use My Submissions for your requests and authorized All Instances or Team Load views for administration. Cancellation and vote reversal remain exceptional, reasoned, explicit actions.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.workflow.build-template",
    guideId: "workflow.build-template",
    route: R.WORKFLOW.TEMPLATE_NEW,
    permissions: [P.VIEW_WORKFLOW_TEMPLATES, P.MANAGE_WORKFLOW_TEMPLATES],
    prerequisites: [
      "Write the approved stages, conditions, approver sources, rejection result, and notifications.",
      "Create required roles, approver groups, dynamic rules, and organogram positions first.",
      "Prepare representative requesters and document examples for validation.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Build the approval contract before publishing",
        body: "This walkthrough explains template identity, version scope, stage resolution, and validation. It never enters JSON, changes a field, adds or removes a stage, selects an approver, publishes, updates, forks, or switches a version.",
        advance: "next",
      },
      {
        id: "details",
        target: "workflow-template.details",
        title: "Set the stable identity and version context",
        body: "Name describes the path. Document type and Code identify it. Read the version banner carefully: Codex may publish a shared path, while a school adjustment creates that school's own version.",
        placement: "right",
        advance: "manual",
      },
      {
        id: "stages",
        target: "workflow-template.stages",
        title: "Resolve every stage deliberately",
        body: "For each Approval stage, verify its source, scope, advance rule, rejection result, empty-approver policy, and inclusion condition. Branch stages route without collecting votes.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "validation",
        target: "workflow-template.stages",
        title: "Preview representative requesters and branches",
        body: "Use Sample requester to check role, group, dynamic, and organogram resolution. Test specific conditions before fallback rules. New stages start with auto-skip on; switch it off unless approved policy explicitly permits an empty result.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "complete",
        title: "The final publish remains yours",
        body: "The walkthrough stops before Publish template. Review stages, routing JSON, notifications, tenant version, and validation evidence, then select the publish action yourself only when the contract is approved.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.finance.configure-foundations",
    guideId: "finance.configure-foundations",
    route: `${R.FINANCE.SETUP}/entities`,
    permissions: [P.FIN_VIEW_ENTITIES],
    prerequisites: [
      "Prepare the approved entity, base currency, fiscal calendar, chart structure, reference data, and posting mappings.",
      "Confirm which set of books should receive the configuration.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Build the accounting foundation in order",
        body: "This walkthrough explains the dependency order. It never creates an entity or account, changes reference data, saves a mapping, or performs a test posting.",
        advance: "next",
      },
      {
        id: "entity",
        target: "finance-setup.entities",
        title: "Start with one independent set of books",
        body: "Verify the entity code, reporting code, name, base currency, and fiscal calendar. Creating an entity also provisions a starter chart and its first calendar, so review all of those inputs before creation.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "chart",
        target: "finance-setup.heading",
        title: "Build the chart before transactions use it",
        body: "Use four-digit account codes: 1 Assets, 2 Liabilities, 3 Equity, 4 Income, and 5 Expenses. Decide which accounts are postable and keep parent accounts inside the same account type.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "reference-data",
        title: "Add only approved reference values",
        body: "Check FX direction and date, tax rates and posting accounts, cost-centre ownership, and constrained dimension values. These labels become journal and report inputs across Finance.",
        advance: "manual",
      },
      {
        id: "posting-defaults",
        title: "Map the services that will consume the chart",
        body: "Finance Settings maps stable posting roles to active postable accounts and controls document and banking defaults. A successful save takes effect for the next matching transaction in that entity.",
        advance: "manual",
      },
      {
        id: "complete",
        title: "The walkthrough stops before configuration",
        body: "Create and save each item yourself under its exact permission, then independently verify the calendar, chart, mappings, trial balance, and a controlled test result before live work begins.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.finance.create-and-post-journal",
    guideId: "finance.create-and-post-journal",
    route: R.FINANCE.LEDGER,
    permissions: [P.FIN_POST_DIRECT_ENTRY],
    prerequisites: [
      "Confirm the active entity and obtain approved evidence for the manual accounting entry.",
      "Prepare the accounts, debit and credit amounts, posting date, cost centres, and dimensions.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Use direct entry only for a real manual journal",
        body: "This walkthrough opens the editor and explains its checks. It never selects an account, reads or changes a field, adds a line, posts, submits, reverses, or voids anything.",
        advance: "next",
      },
      {
        id: "ledger",
        target: "finance-ledger.header",
        title: "Source documents should post their own journals",
        body: "Invoices, receipts, payroll, procurement, and bank work belong in their source screens. Use New journal only for an approved raw debit and credit entry that has no source-document workflow.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "open-editor",
        target: "finance-ledger.new-journal",
        title: "Open the editor without posting",
        body: "Select New journal to inspect the direct-entry form. Opening it changes no business data. The walkthrough will continue when the drawer opens.",
        placement: "bottom",
        advance: "target-click",
      },
      {
        id: "evidence",
        target: "finance-journal.header-fields",
        title: "Anchor the entry to evidence and an open date",
        body: "Confirm the active entity, choose the approved date inside an open posting period, and write a narration and reference that another reviewer can trace to the evidence.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "lines",
        target: "finance-journal.postings",
        title: "Build the accounting treatment line by line",
        body: "Each non-zero line needs one active postable account, a debit or credit side, an amount, and any required cost centre or dimensions. Balanced lines can still be wrong, so verify the accounting treatment separately.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "balance",
        target: "finance-journal.balance",
        title: "Balance is necessary, not sufficient",
        body: "Console requires equal debit and credit totals above zero. Recheck the entity, date, accounts, direction, amount, tags, narration, and evidence before the final action.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "complete",
        title: "Post entry remains your immediate action",
        body: "The walkthrough stops here. Post entry creates the posted journal immediately, without a draft or second confirmation. Select it yourself only after the complete review, then inspect the journal and report effect.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.finance.close-lock-or-reopen-period",
    guideId: "finance.close-lock-or-reopen-period",
    route: `${R.FINANCE.SETUP}/periods`,
    permissions: [P.FIN_VIEW_PERIODS],
    prerequisites: [
      "Confirm the active entity, fiscal year, period, approved close plan, and reconciliation evidence.",
      "Identify the owner of every draft journal, blocker, and warning before changing a period status.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Control the posting window deliberately",
        body: "This walkthrough explains the calendar, checklist, close, reopen, year-end, and permanent-lock boundaries. It never creates a year, selects a period for you, or confirms any state-changing action.",
        advance: "next",
      },
      {
        id: "calendar",
        target: "finance-periods.calendar-controls",
        title: "Work in one entity and fiscal year",
        body: "Verify the active entity and selected fiscal year. Create the next calendar before the last period expires, or every posting date beyond it will be rejected.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "period",
        target: "finance-periods.periods",
        title: "Select the exact posting period",
        body: "Open is ordinary posting, Soft-closed allows controlled close work, Closed is reopenable by permission, and Locked is permanent. Select the period you intend to inspect; opening it is read-only.",
        placement: "top",
        advance: "target-click",
      },
      {
        id: "checklist",
        target: "finance-periods.checklist",
        title: "Separate blockers from warning-only checks",
        body: "A failed blocker must be resolved before close. A warning remains visible for judgment but does not stop close. Reconcile the source records and evidence rather than forcing an offsetting entry.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "actions",
        title: "Each status action has a different consequence",
        body: "Soft close is reversible. Run close steps blocks posting after controls run. Reopen permits ordinary posting again and requires another full close. Lock cannot be reversed. Close the fiscal year before locking its final period.",
        advance: "manual",
      },
      {
        id: "complete",
        title: "Every confirmation remains with the authorized user",
        body: "The walkthrough stops before Soft close, Run close steps, Re-open, Close fiscal year, and Lock period. Verify scope, checklist, reports, approval, and correction plan, then confirm only the intended action yourself.",
        advance: "next",
      },
    ],
  },
] as const satisfies readonly Walkthrough[];

export function findWalkthrough(id: string): Walkthrough | undefined {
  return WALKTHROUGH_REGISTRY.find((walkthrough) => walkthrough.id === id);
}
